### ISSUE TITLE
Multiple docker-compose configuration files

### ISSUE THREAD

**Issue by radmiraal** [EugenMayer/docker-sync#106]
I wanted to drop a little question in here, I see the configuration override setup is using configuration values for 2 docker-compose files. The options I mean are 'compose-file-path' and 'compose-dev-file-path'.

This will be sufficient in most cases, but docker-compose itself supports adding more configuration files than 2. We use this to have a default setup for docker environments in a git submodule, and then use an override file for a specific project. In this setup we need a 3rd docker-compose file to allow custom configuration for a developer.

Currently we've a set of shell scripts that check if the 3rd file exists yes / no and builds the docker-compose command to execute.

I am now testing if docker-sync would be feasible to fix the performance issues with docker on mac, but the limitation of just 2 configuration files would be problematic to us. Is it in some way possible to pass an extra option? Or to extend the 'compose-dev-file-path' option to allow a list of files (that are only added to the docker-compose command if the file exists)?

**Comment by EugenMayer** [comment]
Docker-Sync is split into 2, maybe 3 parts. Sync, Stack (Compose starter), and compose itself.

To achieve what you need, you have 2 options:

*a) Scaffolding*
That is what we do at our company. We call those variations, so for specific features we start use something like `thor docksync:start --php7 --specialfeature`
Both of those options end up passing a additional compose-file to the `docker-compose` gem. In general, scaffolding is described here https://github.com/EugenMayer/docker-sync/wiki/7.-Scripting-with-docker-sync

What you end up is calling docker-compose manually, using a list of files you decided to be the docker-compose files like here `files=> compose_files` https://github.com/EugenMayer/docker-sync/blob/master/lib/docker-sync/compose.rb#L40

So what you do is:
writing a thor/rake task (i would use thor) and include docker-sync as a library, then start the sync like described in scripting and implement some custom logic to select the docker-compose files you want based on the thor-options the user passed on.
That sounds like work, yes it is, but no matter what you will do, you have to implement your custom logic. Docker-Sync is about the sync, not about being a development-all-in solution with any kind of stuff in it. Though, as told you above, we are ourself using docker-sync as a library in a tool handling the special docker-compose file variants.

b) User `docker-sync start` and after that, use `docker-compose -f docker-compose.yml -f docker-compose-dev.yml -f docker-compose-variantA.yml`

Hope that helps

**Comment by radmiraal** [comment]
Thanks for the info ;-) By quickly scanning the code / docs I assumed docker-sync start also used those variables, but as b is possible I can just do that.

**Comment by zxaos** [comment]
There's already overriding happening in `docker-sync-stack`, with the `compose-dev-file-path` option though. Could that argument be instead generalized to use take multiple overrides and run them in order? Something like:

```YAML
compose-override-paths:
  - '/path/to/foo.yml'
  - '/path/to/bar.yml'
```

That would still cover the normal use case for the single sync override, but would also allow more flexibility in cases like this.

**Comment by larslockefeer** [comment]
@zxaos I don't know if this is still relevant to you, however, I was looking for the same and this seems to be covered by #222 since early this year 🎉.
