### ISSUE TITLE
Discuss wether we should set '-prefer newer' by default on unison

### ISSUE THREAD

**Issue by mickaelperrin** [EugenMayer/docker-sync#108]
Hi,

@EugenMayer, I encountered  the issue you reported on Gitter: https://gitter.im/EugenMayer/docker-sync?at=57aa1046f7f11a7936afc5dc

In some undefined conditions (forgot to start docker-sync before editing?), files may have been changed on both sides. Using the additional parameter `-prefer newer` help a lot.

> **prefer xxx**
> Including the preference -prefer root causes Unison always to resolve conflicts in favor of root, rather than asking for guidance from the user. (The syntax of root is the same as for the root preference, plus the special values newer and older.) 
> This preference is overridden by the preferpartial preference.
> This preference should be used only if you are sure you know what you are doing!
- Should we include it by default ? 
- With ability to deactivate it ? 
- Do you see some edge cases where this feature may behave badly ?
- Should we add also '-copyonconflict' ?

> **copyonconflict**
> When this flag is set, Unison will make a copy of files that would otherwise be overwritten or deleted in case of conflicting changes, and more generally whenever the default behavior is overriden. This makes it possible to automatically resolve conflicts in a fairly safe way when synchronizing continuously, in combination with the -repeat watch and -prefer newer preferences.
- Should we introduce a `unison_prefer` parameter with for Unison (`newer` / `host` / `container`) ? `Host`and `container`would be simple alias of roots preventing to use the adaquate root syntax.

And BTW, we are missing some output [here](https://github.com/EugenMayer/docker-sync/blob/master/lib/docker-sync/sync_strategy/unison.rb#L80), which should highlight the syncing problem #109 .

**Comment by EugenMayer** [comment]
the issue with #109 is critical with this combination, admited. 

I will think about the other cases at the weekend, i would suggest ( as you ) to not "quick shot" this. Good find!

**Comment by EugenMayer** [comment]
@mickaelperrin this is one of the issues i am currently facint since switching from rsync to unison.

I think this all gets even worse when we deal with timezone issues, container then start to skip all the new syncs, also sometimes docker-sync does no longer start the sync at all, failing, only the compose stack continues to run.

More or less, multi-level issues, i did not yet not investigate those due to time pressure, but i guess this gets more critical right now in general - this makes unison much more fragile then rsync and we should deal with that

**Comment by RickFrom1987** [comment]
@mickaelperrin or @EugenMayer Thanks for the great work!

I am running into this issue and would like to force from host... is there a current suggested work around here?

**Comment by mickaelperrin** [comment]
According to [unison documentation](http://www.cis.upenn.edu/~bcpierce/unison/download/releases/stable/unison-manual.html), the `prefer` argument accept the `root` to use to resolve conflicts.

> prefer xxx
Including the preference -prefer root causes Unison always to resolve conflicts in favor of root, rather than asking for guidance from the user. (The syntax of root is the same as for the root preference, plus the special values newer and older.) 
This preference is overridden by the preferpartial preference.
This preference should be used only if you are sure you know what you are doing!

If you want to use the host to always resolve conflicts, I think you have to use the value set in the `src` option. Didn't test it, but should be something like:

    -prefer path/to/your/local/dir/synced

**Comment by mickaelperrin** [comment]
I use the `prefer newer` now for some months alongside `copyonconflict`, and I am really happy with it. So far, files edited on the host and files synced back to the host are never the same. This solves some troubles if `docker-sync` hangs or if we forgot to start docker-sync (I still don't use docker-sync-stack).
I think this should be append to the default config file.

**Comment by rogerkk** [comment]
We are using `-prefer newer`, but one of our devs is experiencing an issue where if checking out a branch where files have been deleted, those files still exist on the host afterwards.

Have any of you seen this?

_Disclaimer: I haven't been able to dig too much into this myself yet, as I am not an OSX user and don't have access to this (junior) dev's latop at the moment. If you can think of some things that would be particularly useful to check, then that would be much appreciated._

**Comment by mickaelperrin** [comment]
Sadly, if the checkout involves lot of changes, unison may fail to sync them in real time. The usual way to resolve this is to kill docker sync and restart it.

**Comment by RickFrom1987** [comment]
-prefer newer does/will work for me.

Here is my exact use case for documentation purposes, maybe it will help someone.
1) I ran docker-sync start, I don't know why but I see:
`UNISON 2.48.4 started propagating changes at 11:17:07.46 on 24 Jan 2017
[CONFLICT] Skipping myFileName.ext
  contents changed on both sides`

2) I tried running docker-sync clean, this fails.
`docker-sync clean
Error response from daemon: Unable to remove volume, volume still in use: remove ms-sync: volume is in use - [02e77b357ed69771dea429e09f95fe6dcc4cd2423d67144bfbbcb9f55b742756, c963dc42588ebd5b7c0b213b47efe709a0dcf4cd06e8de1f524894863654ac74]
     success  Finished cleanup. Removed stopped, removed sync container and removed their volumes`

3) I tried docker volume rm project-name-sync. This fails with same error as above

4) added -prefer newer to src, this bypasses the other issues and forces syncs and I am back to work:
`syncs:
name
  project-name-sync: # tip: add -sync and you keep consistent names als a convention
    src: './ -prefer newer'
    dest: '/src/app'
    sync_strategy: 'unison'`

Don't know if this is helpful at all, but it seems like sometimes docker-sync clean can't kill the volume also...

**Comment by EugenMayer** [comment]
@Rick i think your issue is most probably clock skew, probably our nount of localtime does not always work as expected

**Comment by rick** [comment]
![](https://images.moviepilot.com/images/c_fill,h_282,w_500/t_mp_quality_gif/nzpgxjxhnpgj9gha8zvw/show-creators-say-the-big-secret-in-rick-morty-won-t-be-revealed-in-season-3-792113.jpg)

**Comment by EugenMayer** [comment]
@mickaelperrin i would like to finish this one, this can help https://github.com/EugenMayer/docker-sync/pull/225 i guess and it actually does what we need - doing prefer src seems to be the best option, isnt it?

**Comment by ignatiusreza** [comment]
Agreed on prefer src to be the one that makes more sense.. `newer` or `older` are problematic when working in a version controlled space, especially when switching between branches.. ultimately, what user see and working with is what on the working directory of the host (src).. so it would be more obvious and easier for user to deal with in case of issue..

**Comment by mickaelperrin** [comment]
The choice over using `-prefer newer` or `-prefer src` depends largely on the end user use-case  and behaviour priority. 

Some systems may alter some files depending on user actions on the application, for example,  TYPO3 CMS store plugin configuration in a serialised file. With the option `-prefer src`, plugin configuration may be lost if a sync issue appears.

The use case of @ignatiusreza has surely a far broader audience, so I agree using `-prefer src` could be the default choice.

But, we should surely need to use the `-copyonconflict` option to avoid unwanted lost changes during sync conflict. I prefer to cleanup some unwanted files / folders than loose something.

Is this ok for you ?

**Comment by EugenMayer** [comment]
makes a lot of sense @mickaelperrin, so in the end we agree on

`--prefer src --copyonconflict` as a default`? could you implement this for 0.2.0?

**Comment by EugenMayer** [comment]
implemented
