### ISSUE TITLE
[unison] Initial sync output not displayed on error

### ISSUE THREAD

**Issue by mickaelperrin** [EugenMayer/docker-sync#109]
The output of the initial sync is not displayed and may prevent to display error messages  / syncing problems.

Example: https://gitter.im/EugenMayer/docker-sync?at=57aa1046f7f11a7936afc5dc

We are simply missing to display stdout [here](https://github.com/EugenMayer/docker-sync/blob/master/lib/docker-sync/sync_strategy/unison.rb#L80)

**Comment by mickaelperrin** [comment]
Mmm, too quick. In fact, it is displayed but only on `verbose` option.

Should we force the output ?

**Comment by EugenMayer** [comment]
for me, unison is a lot more verbose in syncs and i am not sure i like it. I find it behaves "verbose" in non verbose mode. If my opinion counts here, i would rather reduce "verbosity" and add more verbosity when verbose is activated.

**Comment by mickaelperrin** [comment]
The fix introduced in #109 simply echoes more (and what should be indeed displayed) **only when unison exit with exicode diffenrent than 0** (some conflicts for example). 

It doesn't introduce more verbosity for real-time syncs.

**Comment by EugenMayer** [comment]
oh! sorry, was not aware that its not on exit > 0, that makes a lot of sense then, sorry.
I will open an issue about general verbosity to discuss what you think about it

**Comment by mickaelperrin** [comment]
The title wasn't clear enough :)

**Comment by EugenMayer** [comment]
@mickaelperrin be bold and merge it guess, makes a lot of sense

**Comment by EugenMayer** [comment]
@
