### ISSUE TITLE
terminal-notifier hangs when run under tmux

### ISSUE THREAD

**Issue by fidothe** [EugenMayer/docker-sync#114]
the terminal-notifier command hangs when you try and notify the terminal from a process run under tmux, presumably a similar issue to the detached-from-user-namespace problems detailed here when talking about copy & paste: https://robots.thoughtbot.com/how-to-copy-and-paste-with-tmux-on-mac-os-x.

I'm not sure there's much you can do except add a note to the boilerplate and maybe default to `notify_terminal: false`...

I'll investigate this with the upstream terminal-notifier maintainer

**Comment by EugenMayer** [comment]
Well, not sure we can actually really deal with that, as you mentioned. You probably just have to disable notifications

**Comment by dustinmartin** [comment]
A fix for this would be great as it wasn't obvious what was going on. There are ways check if you're in a Tmux or Screen session. See here: http://unix.stackexchange.com/a/10690 

If in Tmux you could just disable the notifications.

Thanks

**Comment by EugenMayer** [comment]
Sorry, this is out of scope for me. If you like to have this in docker-sync, please provide a patch/pull request. Thanks!

**Comment by EugenMayer** [comment]
closing until someone picks it up
