### ISSUE TITLE
Migration Guide from rsync to unison as default

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-sync#115]
What steps need to be done when we change the default of docker-sync to unison?
- excludes need a different syntax or the usage of sync_excludes_type: 'Name'
- group-id mapping needs to be removed from the docker-sync.yml
- notify_terminal does only notify once on the initial not the subsequent syncs

**Comment by mickaelperrin** [comment]
- remove `fswatch_strategy` option to prevent issues like https://github.com/EugenMayer/docker-sync/issues/209
- remove other specific options of rsync
- use `sync_strategy: 'unison'`

**Comment by mickaelperrin** [comment]
BTW, while working daily with `unison` and really happy with it, `unison` has still some instabilities. I always have a log window with debug mode activated displayed on my screen to ensure files are correctly synced. Most of the time, a simple (or multiple) restart fix the issue, but unison + daemon will hide any information to the end user of eventual problems.

**Comment by EugenMayer** [comment]
Documented here https://github.com/EugenMayer/docker-sync/wiki/Migration-Guide - still need the code changes

**Comment by EugenMayer** [comment]
done
