### ISSUE TITLE
Read-only files cause unison to fail with permission denied

### ISSUE THREAD

**Issue by yannisc** [EugenMayer/docker-sync#124]
I try to use docker-sync with a Drupal installation. Drupal upon page load makes the settings.php unwritable. So, when trying to change that file on my Mac, unison fails with permission denied. Is there any workaround to this?

**Comment by mickaelperrin** [comment]
Unison normally syncs attributes also, so you can simply change the permissions on the host ?

**Comment by yannisc** [comment]
I'll have to change permissions before each change, right? If there's no other workaround, I'll go with this.

**Comment by mickaelperrin** [comment]
I thought Drupal was changing permissions only during the install process. If this is not the case, you could mauybe try to prevent the sync of attributes with the additional parameters `-owner false -group false`. I don't know how it will behave with the user/group assignment, but as Unison is running under the adequate user, it should be ok.

**Comment by EugenMayer** [comment]
After drupal installed it, change the setting.php to 777 and it will never be changed back by drupal.
This is a very application sepcific issue and i do not think this has anything to do with docker-sync at all.

I hope that helps

**Comment by yannisc** [comment]
I'll try it. Another workaround is to have the sites/default folder in another mounted volume, not synced with docker-sync. It doesn't slow things down much. Thanks anyway!

**Comment by EugenMayer** [comment]
@yannisc i ignore all sites folder actually, so ignoring sites/*.dev and also sites/default - it does not make a lot of sense syncing those anway

**Comment by yannisc** [comment]
Right!
