### ISSUE TITLE
help command line has docker-sync start twice

### ISSUE THREAD

**Issue by gcstang** [EugenMayer/docker-sync#127]
docker-sync -h
Commands:
  docker-sync clean           # Stop and clean up all sync endpoints
  docker-sync help [COMMAND]  # Describe available commands or one specific command
  docker-sync list            # List all sync-points of the project configuration path
  docker-sync start           # Start all sync configurations in this project
  docker-sync start           # Start all sync configurations in this project
  docker-sync sync            # sync - do not start a watcher

**Comment by EugenMayer** [comment]
Thank you for the hint! Fixed
