### ISSUE TITLE
unison-fsmonitor fails to install correctly with stock python but does not warn

### ISSUE THREAD

**Issue by zxaos** [EugenMayer/docker-sync#128]
Since #64 , the system will warn if unison-fsmonitor is not installed, and will attempt to download and install it.

Unfortunately, this install can fail partially, but will never be reported again.

Specifically, with a stock python that ships with El Capitan, the actual unison-fsmonitor script will download and be chmod'd properly but its dependencies (`macfsevents` ) will not be successfully installed. So future invocations of docker-sync will not warn about the issue (because the script itself exists) even though the environment is non-functional.

**Comment by EugenMayer** [comment]
This has already been fixed and is waiting for the next release. Thank you for reporting it! #112
