### ISSUE TITLE
Make 'Name' the default exclude_type in 0.2.0

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-sync#133]
@mickaelperrin i would change the current default from Path to Name, since it seems a lot more convenient to me and also matches the rsync behavior. One can already change this in 0.1.2 with #132 

Any vetoing?

**Comment by mickaelperrin** [comment]
None, it should have been the default since the beginning.

**Comment by mickaelperrin** [comment]
@EugenMayer Except changing this setting, how do you plan the migration ? do you want to echo a notice somewhere or do additionnal checks ?

**Comment by EugenMayer** [comment]
I implemeted a migration hook with 0.1.0 which allows me to show migration hints upon a start - what i basically did i save you current version, and when you run next time, i compare that and ask the hooks if any hooks is going to trigger on that upgrade, and well, that is what we will do here.

We will do this for several things, for the default new sync ( unison ), --prefer .. the new excludes like mentioned here.

When you start docker-sync you will get a confirmation asking you to opt in you got it, then you move on. I guess, beside we put that into the release nots, we obvisouly switch from 0.1.0 to 0.2.0 which should make people aware - and if not, and even that confirmation does not hit them - we have done more then enough :). 

What do you think?

**Comment by EugenMayer** [comment]
implemented hook and docs https://github.com/EugenMayer/docker-sync/wiki/Migration-Guide

**Comment by EugenMayer** [comment]
Code changes still needed

**Comment by EugenMayer** [comment]
done
