### ISSUE TITLE
Message say it doesn't support sync_user but it does

### ISSUE THREAD

**Issue by gagarine** [EugenMayer/docker-sync#136]
Docker-sync with unison do now support sync_user but if you use sync_group it will report it doesn't support sync_user. I guess it's simply a matter of updating the message.

```
$ docker-sync start
          ok  Starting unison
/usr/local/lib/ruby/gems/2.3.0/gems/docker-sync-0.1.2/lib/docker-sync/sync_strategy/unison.rb:122:in `sync_options': Unison does not support sync_user, sync_group, sync_groupid - please use rsync if you need that (RuntimeError)
```

Now it is: Unison does not support sync_user, sync_group, sync_groupid

Should be: Unison does not support sync_group, sync_groupid

**Comment by EugenMayer** [comment]
oh good catch!

**Comment by EugenMayer** [comment]
If you like, create a pull request and be part of the contributors

**Comment by EugenMayer** [comment]
actually now, this is correct, unison-onesided does not support it, only the unison (the new one) does
