### ISSUE TITLE
Implements a --version parameter 

### ISSUE THREAD

**Issue by mickaelperrin** [EugenMayer/docker-sync#138]
I didn't find an easy way to retrieve the version of docker_sync installed. There is the VERSION file, but where is the file when using the bundled `gem` install ?

Shouldn't we  need to implement a `--version` parameter to quickly spot the version used ? It would ve very helpful to spot if a user is using the latest version or not.

**Comment by mickaelperrin** [comment]
`gem list | grep docker-sync` may be sufficient.

**Comment by EugenMayer** [comment]
We have a function for that already, implementing this will be 2 min effort. Shall we?
