### ISSUE TITLE
rsync: failed to set permissions

### ISSUE THREAD

**Issue by sandrodz** [EugenMayer/docker-sync#143]
when I run command `docker-sync start` I get following errors: `rsync: failed to set permissions`

all errors are about `node_modules` dir

full error looks like this: 

`rsync: failed to set permissions on "teemo.dev/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/node_modules/request/node_modules/.bin/har-validator" (in volume): Not supported (95)`

Everything seems to work anyways. But errors are annoying. Any clues?

**Comment by EugenMayer** [comment]
.bin/har-validator mighty be a precompiled binary symlinked on OS X, please Check that, since that Canon be resolved after symlinking

**Comment by sandrodz** [comment]
it seems so yes, I should probably put `node_modules` in ignored list right?

<img width="770" alt="screen shot 2016-09-21 at 12 49 08 am" src="https://cloud.githubusercontent.com/assets/8479569/18688385/400308da-7f95-11e6-926e-14ac6457140b.png">
