### ISSUE TITLE
Intermittent permission errors on unison sync

### ISSUE THREAD

**Issue by timstallmann** [EugenMayer/docker-sync#144]
Hi y'all -- just curious if anyone might have insight into errors like the below which have been cropping up intermittently on a new docker-sync config. Sync will work fine for a certain period of time (maybe a few minutes? unclear if this is related to the number of syncs or to the time period), and then start failing with the error:

`Failed: Error in processing a transfer instruction:
Permission denied [open(/path-to-file/.unison.file.php.146799a726b89fa871e5de6c23e5b465.unison.tmp)]`

I imagine I must be configuring something wrong as `docker-sync` usually works great, but can't figure out what's going wrong. This is on version `0.1.2`, using `unison` sync strategy.

**Comment by timstallmann** [comment]
This was due to misconfigured permissions on my container!

**Comment by EugenMayer** [comment]
Great you got that @timstallmann - we are all traveling arround due to holidays, so response times are rather bad :)

**Comment by winglian** [comment]
@timstallmann what were the permission issues that need to be corrected? I'm having the same issue.

**Comment by mharbers** [comment]
@timstallmann @winglian Having the same issue. Looking forward to the solution.

**Comment by timstallmann** [comment]
@winglian @mharbers if only I had documented more clearly what the fix was 2 months ago :). But I think this had to do with my container processes running as a different, but non-root, UID from the docker-sync file ownership. The fix was to add a `usermod` line to the startup script for my webcontainer to force `www-data` to have UID 1000. Does that seem at all applicable to what you're running into?
