### ISSUE TITLE
Bump docker-compose to 1.0.1

### ISSUE THREAD

**Issue by MrMMorris** [EugenMayer/docker-sync#149]
Thanks for creating such a useful tool! The slowness of dealing with many files with docker on OSX with Dinghy has been a pain point for my developers.

I was wondering, however, if the hardcoded dependency on the `docker-compose` gem is necessary. For one, ruby is telling me `docker-compose requires Ruby version ~> 2.1` and I REALLY don't want to force all my non ruby developers to go down the hole of dealing with Ruby upgrades if they don't have to. We already install docker-compose with Homebrew so would it be possible for `docker-sync` to just check that the executable is available?

Also, because you have the `docker-compose` version pegged at 1.0.0, I will have to upgrade it separately anyways. 

The alternative is I can get everyone to pull the repo, change the gemspec, `gem install bundle` and then `bundle install`, but that is not a very nice solution either.

I don't want to stir anything up, but I thought I'd ask what is possible before choosing a solution.

**Comment by MrMMorris** [comment]
**Actually**, maybe you could just bump `docker-compose` to 1.0.1 so it no longer requires Ruby >=2.1 as per https://github.com/xeger/docker-compose/issues/34#issuecomment-250656877?

**Comment by EugenMayer** [comment]
missed thank, thank you for pointing that out, fixed
