### ISSUE TITLE
Feature: Suppress unison output?

### ISSUE THREAD

**Issue by wulftone** [EugenMayer/docker-sync#159]
This project seems to work great!  However, I'd like it if I could suppress the output somehow.  I want "regular docker-compose" style output without all of the extraneous watcher stuff.  Here's an example:

```
UNISON 2.48.4 finished propagating changes at 21:33:32.85 on 16 Oct 2016
Saving synchronizer state
Synchronization complete at 21:33:32  (1 item transferred, 0 skipped, 0 failed)
Looking for changes
  Waiting for changes from server
Reconciling changes
Nothing to do: replicas have not changed since last sync.
Looking for changes
  Waiting for changes from server
Reconciling changes
Propagating updates
```

There's a lot of that and it's interfering with my ability to see my app's normal log messages.  I looked at all the docs and example configs, and didn't see anything I could use.  How can I turn it off?

I should mention, I'm starting with `docker-sync-stack start`.

Thanks!

**Comment by mickaelperrin** [comment]
If your are talking about false sync messages, see #118. Unox have to be rewritten to take in account exclude patterns.

If you want to disable, all unison log, docker-sync have to be modified to introduce this feature.

However I will discourage you to go this way. From time to time, the sync hangs and you changes won't be synced. Without logs it could be really hard to discover it.

**Comment by wulftone** [comment]
You do have a good point.  I do appreciate the startup logs, but the rest of them don't seem that useful to me during normal operation... Perhaps if it just logged to a file instead, I could look at it whenever I wish instead of being forced to on stdout mixed in with the container logs. I will look at docker compose options to redirect the output to a file, thanks!

**Comment by cgpro** [comment]
Any news on this subject? I use Docker with Webpack for frontend development and the output of linters for CSS and JS would be better readable. (without the unison output)
