### ISSUE TITLE
Error on syncing symlinks with rsync? error code 95

### ISSUE THREAD

**Issue by trungtnm** [EugenMayer/docker-sync#161]
I got this error when run `docker-sync-stack start` using `rsync`, on many files :
`rsync: failed to set permissions on "front/bin/phpmd" (in volume): Not supported (95)`
`rsync: failed to set permissions on "admin/bin/phpunit" (in volume): Not supported (95)`

After investigating, i found that this happened when the files caused the error are symlinks. If i exclude these files from syncing or remove the symlinks, everything works fine.

**Comment by EugenMayer** [comment]
Are you syncing your node_modules?

**Comment by trungtnm** [comment]
@EugenMayer : no, i use nearly default configuration as [here](https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration) and do not have `node_modules` in my projects. It happens with some files generated by `PHP Composer` (see picture below)
![files with symlinks](https://lh3.googleusercontent.com/y0umVpYVJu9k4vB0T1bDgu65vJJrvkxS7uQSm9cNeQbASY_Cgw6fcrgZLL7uQb47GyWuwrkp21IZvdQp2u5ndehyp2qddnU3TQGichP1leYgqW3gr5X6CkKRz1pr8DIbU-jil9qG8qGIf8YrA7RtOZ2sCJmA9ZDcOcGSSlb7ugAfuDwTSfChEMha4NZG3eNMsxqIRQZQsPhQzMRSkZ8JWrJBg6TJh2m4It5HMsJ3MoDLTtFMa3Xvb0FjfZ1XCOFdLS4YQYqeZvyvwo3A9OsvLBQigoEAMmpkP79VRbJWlshbX-ZXG8SqS2xTkVHY8F0dghVdtfzIxAg9vBOlKG2dk1dwYliBA-F9PWfCyn522HkE4TvCDkZEXQH2GFWojO4_sQw1wNK8VLHAsicGbbzjsK-O39iCBsejyDlpZsX74IdffO2reuK-qz_APb7ICz2ObFwqX_3KtpcdonAhXznjN6GYLMpdgF1nfBg7Gi5wYKpwfakvMscmKV1yEycanE0cZG_QNlaobmFDKS8JaqZpjaaMzq80LnKR6YBQsgU0AudRQ0CqZT7VCy8-7LxMkh6qF6_2D0bZUsgMeZNwcZ4OWE6I2aM6h4kiZTmWA8fTQhL_eVyJ=w2174-h406-no)

**Comment by EugenMayer** [comment]
please check if those binaries are compiled binaries, if yes, they might be symlinks on your OSX to a different location and if synced, they do not accists.

"Not supported" is most probably an issue that the symlink is simply broken on the container, please also see the issue queue for issues like https://github.com/EugenMayer/docker-sync/issues/162

**Comment by anthwinter** [comment]
you could try including -L within the sync_args options of the docker-sync.yml

From the rsync docs: "When symlinks are encountered, the item that they point to (the referent) is copied, rather than the symlink."

There are also other options to attempt if you check -l, -L, -k and -K on this page: https://linux.die.net/man/1/rsync

**Comment by trungtnm** [comment]
thanks @anthwinter , it works well with `-L` arg.

**Comment by kallehauge** [comment]
@trungtnm have you tried to delete a file and see if it gets removed in the container? Because that is not the case for me :)

**Comment by trungtnm** [comment]
@kallehauge yes, this is the issue with symlinks :). I think you can try with `--delete` arg.

**Comment by kallehauge** [comment]
That's brilliant @trungtnm - I didn't even think of that :smile:

**Comment by EugenMayer** [comment]
Yes delete is not used with rsync intentionally, because there are too many edge cases. If you want to use delete, you should thing about using unison not rsync as a strategy.

**Comment by EugenMayer** [comment]
Is this issue still open actually, or did you solve it by now?

**Comment by trungtnm** [comment]
Yes, it resolved! I will close this.
