### ISSUE TITLE
Add support for docker-compose --abort-on-container-exit

### ISSUE THREAD

**Issue by mrfelton** [EugenMayer/docker-sync#163]
We'd like to see support for running docker-compose with the `--abort-on-container-exit` flag set which will bring down the stack if any one service aborts.

**Comment by EugenMayer** [comment]
@mrfelton please check with https://github.com/xeger/docker-compose if this feature is implemented there. If yes, we need to think about how we would activate that in docker-sync

**Comment by mrfelton** [comment]
@EugenMayer It's part of docker-compose, but it doesn't look like it's implemented in the repo that you linked to.

**Comment by EugenMayer** [comment]
since we are using that gem and not the docker-compose cli directly, we need this first there.
