### ISSUE TITLE
Failed to start unison

### ISSUE THREAD

**Issue by karneaud** [EugenMayer/docker-sync#167]
Having an issue using unison based sync

>      ok  Starting unison
>       ok  ether-unison-sync container still running, restarting unison in container
>  command  docker exec ether-unison-sync supervisorctl restart unison
>       ok  starting initial sync of ether-unison-sync
>  command  docker inspect --format=" {{ .NetworkSettings.Ports }} " ether-unison-sync | /usr/bin/sed  -E "s/.*map\[5000[^ ]+ ([0-9]*)[^0-9].*/\1/"
>  command  unison -ignore='Path .gitignore' -ignore='Path .git/' -ignore='Path .dockerignore' -ignore='Path node_modules/' -ignore='Path build/' -ignore='Path target/' -ignore='Path *.yml' -ignore='Path *.xml' -ignore='Path *.md' -ignore='Path .DS_Store' /Users/kendallarneaud/Documents/Git/ehter-truff -auto -batch socket://192.168.99.100:32769
>    error  Error starting sync, exit code 0
>  message  
>  message  Contacting server...
> Fatal error: Failed to connect to the server on host 192.168.99.100:32769
> success Unison server started
> command docker inspect --format=" {{ .NetworkSettings.Ports }} " ether-unison-sync | /usr/bin/sed -E "s/.map[5000[^ ]+ ([0-9])[^0-9]./\1/"
> command unison -ignore='Path .gitignore' -ignore='Path .git/' -ignore='Path .dockerignore' -ignore='Path node_modules/' -ignore='Path build/' -ignore='Path target/' -ignore='Path *.yml' -ignore='Path *.xml' -ignore='Path *.md' -ignore='Path .DS_Store' /Users/kendallarneaud/Documents/Git/ehter-truff -auto -batch socket://192.168.99.100:32769
> error Error starting sync, exit code 0
> message
> 
> message Contacting server...
> Fatal error: Failed to connect to the server on host 192.168.99.100:32769
> command docker inspect --format=" {{ .NetworkSettings.Ports }} " ether-unison-sync | /usr/bin/sed -E "s/.map[5000[^ ]+ ([0-9])[^0-9]./\1/"
> command unison -ignore='Path .gitignore' -ignore='Path .git/' -ignore='Path .dockerignore' -ignore='Path node_modules/' -ignore='Path build/' -ignore='Path target/' -ignore='Path *.yml' -ignore='Path *.xml' -ignore='Path *.md' -ignore='Path .DS_Store' /Users/kendallarneaud/Documents/Git/ehter-truff -auto -batch socket://192.168.99.100:32769 -repeat watch
> Contacting server...
> Fatal error: Failed to connect to the server on host 192.168.99.100:32769

I too had a rsync container before I switched so I just shutdown everything and restarted....but still no dice even though I changed the name.

I'm using latest docker-sync(0.1.4)

**Comment by EugenMayer** [comment]
please clean all containers and volumes first, then retry with unison. Ensure you have unison/unox installed and if it does not work, please post your docker-sync.yml. Thank you!

**Comment by EugenMayer** [comment]
reopen the issue if you move on with the issue
