### ISSUE TITLE
Specify single file in src/dest?

### ISSUE THREAD

**Issue by dojohnso** [EugenMayer/docker-sync#172]
I have a base directory "/path/to" which contains a ton of directories and files, but I only need one file, "/path/to/file.ini"

I would love to do something like:
`src: '/path/to/file.ini'`
`dest: '/path/to/file.ini'`

But when docker-sync starts up, I see it's adding a slash to the path like: 
`rsync [options] /path/to/file.ini/ [destination]`

It then throws a "Not a directory" error which makes sense there. 

Is there any way to support syncing a single file like this? Or is it always assumed to be a directory?

**Comment by EugenMayer** [comment]
Well rsync wise there should not be a limitation, maybe we transform the path during the code.
Since it is a very rare corner-case i would not work on this actively, but surely i would support a pull request and try to get this feature on board

Do you mind working on this yourself? Thanks!

**Comment by dojohnso** [comment]
That's understandable. I'll see what I can come up with. Thank you!

**Comment by cupojoe** [comment]
Was this ever implemented?

**Comment by EugenMayer** [comment]
No it wasnt @cupojoe
