### ISSUE TITLE
fswatch problems (rsync not updating)

### ISSUE THREAD

**Issue by sathomas** [EugenMayer/docker-sync#174]
macOS Sierra Version 10.12.1
Docker for Mac Version 1.12.3 (13776)
fswatch 1.9.3
(stock rsync in macOS)

Clean Install

```
docker rm $(docker ps -a -q)
docker rmi $(docker images -q)
```

Test using docker-sync-boilerplate
```
cd docker-sync-boilerplate/rsync
docker-sync-stack start
```

App runs and correctly shows `index.html` contents
```
Every 3s: cat /var/www/index.html                           2016-11-16 14:21:22
your-app     | 
your-app     | Some random HTML file hereasdasd
your-app     | NEW
```

In separate terminal window
```
cd docker-sync-boilerplate/rsync/app
sed -i.bak s/NEW/NEWER/ index.html
```

The `index.html` file is changed, but the output remains the same on the original window.

Manually forcing an rsync in the second terminal window
```
docker-sync sync
```
Does update the output in the original window.

**Comment by EugenMayer** [comment]
Do you have extensive excludes? please see https://github.com/EugenMayer/docker-sync/issues/68

**Comment by sathomas** [comment]
Think I found the problem. I installed `docker-sync` locally instead of for all users. Running my own app in verbose mode:

```
Sync exceed-app-sync  xargs: docker-sync: No such file or directory
```

**Comment by sathomas** [comment]
Confirmed the problem was with local path. Going to close this issue.

**Comment by EugenMayer** [comment]
Great you sorted this one out!
