### ISSUE TITLE
sync_excludes not working in unison bidirectionally 

### ISSUE THREAD

**Issue by stuyam** [EugenMayer/docker-sync#181]
I will admit, I have tried this many different ways and still can not get the ```sync_excludes``` to work with ```unison```.

This is my docker-sync.yml file
```
# docker-sync.yml
syncs:
# this name has to be unique and is used in docker-compose.yml as well
  icechi-web-data-sync:
    src: '.' # the directory on the host system
    dest: '/myapp' # the directory on the container
    sync_host_ip: 'localhost' # localhost for docker for mac
    sync_host_port: 10872 # unique port
    sync_strategy: 'unison'
    sync_excludes: [ 'tmp' ]
    sync_excludes_type: 'Path'
```

I am to the point where I really can not determine if this is a bug or I am totally misunderstanding something.
I am using rails, when I have these excludes set up, it "seems" to work because I don't see that it copies it on start up (I do see it copy it on startup when I don't have the excludes). However the ```tmp/pids/server.pid``` file along with other tiles always reapers in my tmp directory.

Now that I am writing this I am realizing, does the sync_exclude only work in one direction when using the bidirectional unison? I am trying to exclude files that are generated on the container and synced back to my computer.

**Comment by EugenMayer** [comment]
@stuyam please see https://github.com/EugenMayer/docker-sync/issues/118 - i will close this as a dupe, lets go on in the other ticket. Short answer, yes there seem to be an issue
