### ISSUE TITLE
Error: Service "X" mounts volumes from "Y", which is not the name of a service or container.

### ISSUE THREAD

**Issue by bocharsky-bw** [EugenMayer/docker-sync#182]
I get the next error when I run `$ docker-sync-stack clean`:

> Service "X" mounts volumes from "Y", which is not the name of a service or container.

Full stack trace:
```
Service "X" mounts volumes from "Y", which is not the name of a service or container.
/Library/Ruby/Gems/2.0.0/gems/docker-compose-1.0.2/lib/docker/compose/session.rb:235:in `run!': 'down' failed with status 'pid 47445 exit 1': Service "X" mounts volumes from "Y", which is not the name of a service or container. (Docker::Compose::Error)
	from /Library/Ruby/Gems/2.0.0/gems/docker-compose-1.0.2/lib/docker/compose/session.rb:89:in `down'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.1.5/lib/docker-sync/compose.rb:57:in `clean'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.1.5/tasks/stack/stack.thor:87:in `clean'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.1.5/bin/docker-sync-stack:26:in `<top (required)>'
	from /usr/local/bin/docker-sync-stack:23:in `load'
	from /usr/local/bin/docker-sync-stack:23:in `<main>'
```

**Comment by EugenMayer** [comment]
Please post your docker-sync.yml and your docker-compose.yml

Also please ensure you understand the basic examples in the boilerplate:  https://github.com/EugenMayer/docker-sync-boilerplate

**Comment by bocharsky-bw** [comment]
Actually, I use this example for Symfony: https://github.com/timglabisch/symfony_docker_sync .

I also noticed that this error occurs when I run `$ docker-sync-stack clean` twice or more times

**Comment by EugenMayer** [comment]
Well this is not a real issue here, its just the way the container depend on volumes exposed by other containers, which already have been stopped. He uses the old container-name based mount, i created an issue so he can improve on that and this issue will no longer be present
