### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by vladislavs1321** [EugenMayer/docker-sync#183]
I try to run composer inside container to install vendors 
`ls -la` inside container
```
drwxr-xr-x  4 www-data users    4096 Nov 21 17:22 src
drwxr-xr-x 49 root     root     4096 Nov 23 15:08 vendor
drwxr-xr-x  2 www-data users    4096 Nov 21 10:46 web

```

and in there is from ide 
<img width="562" alt="screen shot 2016-11-23 at 16 31 37" src="https://cloud.githubusercontent.com/assets/2521819/20567794/5fb25884-b19a-11e6-8d55-6e0110d84fe6.png">

```syncs:
  app-docker-sync:
    src: '.'
    dest: '/var/www/html'
    sync_strategy: 'unison'
    notify_terminal: true
    sync_args:
        - "-ignore='Path .idea'"
        - "-ignore='Path .DS_Store'"
        - "-ignore='Path .git'"
        - "-ignore='BelowPath .git'"
        - "-ignore='Path bower_components/*'"
        - "-ignore='Path docker-config/*'"
        - "-ignore='Path ezpublish_legacy/var/cache/*'"
        - "-ignore='Path ezpublish/cache/*'"
        - "-ignore='Path ezpublish/logs/*'"
        - "-ignore='Path ezpublish/sessions/*'"
        - "-ignore='Path node_modules/*'"
        - "-ignore='Path web/var/cache/*'"
        - "-ignore='Path web/var/indexes/*'"
        - "-prefer newer"
    max_inotify_watches: 100000
```
how to get normal vendor folder outside container?

**Comment by EugenMayer** [comment]
- Please use sync_excludes to define excludes

I do not understand, what you expect and what you have - please describe what actually is wrong

**Comment by vladislavs1321** [comment]
inside container i have 'vendor' folder, outside container i have '.unison.vendor.2e69bad744a4779e5e7a3fbe7eb3778b.unison.tmp' instead

**Comment by EugenMayer** [comment]
That is odd and unexpected - do you get any errors when using the verbose mode?

@mickaelperrin did you encounter such when using composer?

**Comment by vladislavs1321** [comment]
/usr/lib/python2.7/site-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2016-11-21 18:19:07,225 CRIT Supervisor running as root (no user in config file)
2016-11-21 18:19:07,225 WARN Included extra file "/etc/supervisor.conf.d/supervisor.unison.conf" during parsing
2016-11-21 18:19:07,233 INFO RPC interface 'supervisor' initialized
2016-11-21 18:19:07,233 CRIT Server 'unix_http_server' running without any HTTP authentication checking

**Comment by EugenMayer** [comment]
that is not critical - i mean rather on the host (OSX) - try to activate the verbose mode in docker-sync

**Comment by vladislavs1321** [comment]
there is no errors in verbose mode, but files, that comes from syncing container becomes not writable. Simple example: i've created 1.txt file in container, and can not edit it coz its created under root

**Comment by EugenMayer** [comment]
Fix your uid group settings in the dk
,

**Comment by mickaelperrin** [comment]
Mmm, forgot to retype my answer here as I lost it due to a battery issue...

Sadly and definitely yes. I encounter this error often, and still doesn't have a proper way to resolve it.

It happens when syncing tasks are heavy. Temporary unison directories are created.

Fortunately, restarting docker-sync has always resolved the issue for me.

You can safely delete the .unison directories. Unison should automatically delete them but the grace period is rather important.

**Comment by vladislavs1321** [comment]
@mickaelperrin thanks for reply, you are late for 2 hours))) today i've solve it with same way: remove all trash, stop container, run clean command, and resync all.
