### ISSUE TITLE
mv file leaves copy in sync container?

### ISSUE THREAD

**Issue by steveinatorx** [EugenMayer/docker-sync#186]
my compiler was complaining about dupe classnames - when i do a 'mv foo bar' outside of my properly (latest build) sync'd container docker-sync seems to leave a copy of the original file in the container. 

-OS X El Capitain 10.11.6
-Docker version 1.12.3, build 6b644ec, experimental  (docker for mac)
- latest docker-sync image

any ideas? bug? 
lmk if i can supply any more info

**Comment by steveinatorx** [comment]
switching to unison strategy resolved this for me - closing.

**Comment by EugenMayer** [comment]
FTR - rsync has been used at first, but this is a one-way sync, so changes in the container do not get reflected but also, a move is in terms of rsync a delete + create, and the default settings of rsync are configured to never delete anything ( can be forced using sync_args though )

great you solved it yourself - currently unison is by far the more robust variant and will be the new default with 0.2.0
