### ISSUE TITLE
docker compose.yml portability

### ISSUE THREAD

**Issue by luigi69** [EugenMayer/docker-sync#187]
Hi.

File sharing with Docker on OSX can be really irritating.
This tool helps a lot, so thank you for all your efforts.

I would just like to notice, that presented boilerplate code doesn't really seem that portable.
I'm reffering to this:

https://github.com/EugenMayer/docker-sync/wiki/Keep-you-docker-compose.yml-portable

Why? I think we can safely assume, that by default:
* `docker-compose.yml` file dedicated for dev env should have configured a shared volume with app source code
* an Linux based developer should run thath config file without any modifications (since Docker is a Linux based tool, and it works well without any additional tools/hacks)
* only an OSX based developer should pass additional config file (via `-f` option) with `docker-sync` overrides (since he uses additional tool)

It seems, that Docker handles merging `volumes` section configuration in a way, which overrides a setting only if both driver and internal path matches (on the container).

So we cannot do this:
* have a dev env `docker-compose.yml` with default settings (good enough for Linux based developers)
* have a `docker-compose-sync.yml` with overrides for docker-sync developers (OSX based developers)

Why? Because Docker won't override `volumes` settings during configuration merge.
It will add them, resulting in having both. This results in errors (thrown by rsync).
And it's a shame, because this setup seems very nice (at least for me).

Documentation/boilerplate proposes this:
* have a prod env dedicated` docker-compose.yml` without any shared volumes
* have a dev env dedicated `docker-compose-dev.yml` with overrides for docker-sync developers (OSX based developers)

This ignores developers using Linux.

My proposition would be to pick and recommend one of following setups:

1.

* have a dev env dedicated `docker-compose.yml` without any shared volumes
* have an additional `docker-compose-volumes.yml` with volume sharing setup for Linux based developers
* have an additional `docker-compose-sync.yml` with docker-sync volume sharing setup for OSX based developers

2.

* have a `docker-compose.yml.dist` with template settings - good enough for Linux based developers
* have an additional `docker-compose-sync.yml` with volume sharing for OSX developers overrides
* instruct Linux based developers to `cp docker-compose.yml.dist docker-compose.yml` and just run it
* instruct OSX based developers to `cp docker-compose.yml.dist docker-compose.yml`, remove volumes sharing, and run it with `-f docker-compose-sync.yml`

What do you think, @EugenMayer ?

**Comment by EugenMayer** [comment]
You slighty got it wrong, docker-compose.yml is not the base for developers, it's the base for production, that's why no code mounts are needed.

You should have 2 -dev files deriving from dc.yml, one for Linux and one for osx. Or you even build one ontop of the other

Your POV is not wrong, it's different and also reasonable.

**Comment by luigi69** [comment]
You wrote:

> You slighty got it wrong, docker-compose.yml is not the base for developers, it's the base for production, that's why no code mounts are needed.

I wrote:

> Documentation/boilerplate proposes this:
have a prod env dedicateddocker-compose.yml without any shared volumes

So... uhm... I've noticed.
It's just that I think it should be set up a bit differently (to be as much portable and comfortable as it can). It seems more reasonable to use default `docker-compose.yml` file for default and most common usage (I guess Linux based developer), and require overrides/additional config files for users using additional tools/hacks or automated environments (prod/ci).

But you are right - it's kind of a matter of preferences.
If you don't agree I guess the issue can be closed ;)

**Comment by EugenMayer** [comment]
I neither can agree nor disagree, what you stated is equaly right - you think out of the pure developer POV - i think from the full stack POV - means there is not only a development env, there is also a production env. 

And its by nature of it it goes down like

(lower based on upper)
1. production-definition (docker-compose.yml)
2. general development definition (docker-compose-dev.yml)
3a) Linux developer definition (docker-compose-dev-linux.yml)
3b) OSX (docker-sync) developer definition  (docker-compose-dev-osx.yml)

so running osx woudl be
```docker-compose -f docker-compose.yml -f docker-compose-dev.yml -f docker-compose-dev-osx.yml```

linuux
```docker-compose -f docker-compose.yml -f docker-compose-dev.yml -f docker-compose-dev-linux.yml```

and production
```
docker-compose -f  -f docker-compose.yml
```

3a) / 3b) will only add volume definition, while 2. will add port exposing, extra ENV and so on, which need to be shared on all dev envs, OSX or linux ( or windows ).

---------
Thats my POV, but i am not enforcing anything with docker-sync - the boilerplate has a pattern, but feel free to implement yours - i do not want to force anybody into a framework . Whatever works best for you ( as long as you know what you are doing :) )

**Comment by luigi69** [comment]
Well, thanks for feedback :)
