### ISSUE TITLE
Remove the option sync_user since it just spreads confusion

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-sync#192]
As by the discussion in the chat, we shall remove sync_user, only leave sync_uid.

We might want to inform the users, since this might break sync_user only setups.

This change needs also to be done in our images
 - https://github.com/EugenMayer/docker-sync/issues/192
 - https://github.com/mickaelperrin/docker-unison-unox/issues/2

**Comment by EugenMayer** [comment]
done for unison:unox

**Comment by mickaelperrin** [comment]
@EugenMayer could you tell where it's done ? there are still a lot of references to sync_user: https://github.com/EugenMayer/docker-sync/search?utf8=✓&q=sync_user

**Comment by mickaelperrin** [comment]
BTW, am I wrong or it looks like there is a typo here: https://github.com/EugenMayer/docker-image-unison-unox/blob/develop/entrypoint.sh#L27. Shouldn't we have to use `UNISON_OWNER` instead of `dockersync` as user name ?

**Comment by EugenMayer** [comment]
there is no "owner" anymore, since i completely removed "sync_user" - since this user is just a name on the sync-container, and never will be shown to any user or visible, it does not even make sense introducing it. Basically, what we want is to map a UID on a existing user int he app-container, which has whatever name it has. On the sync container, it even could stay  plain numeric, but since we have to, i have chosen a stack name.

Does that clear that one up?

**Comment by EugenMayer** [comment]
removed
