### ISSUE TITLE
Use case: only sync with unison manually

### ISSUE THREAD

**Issue by rubenfonseca** [EugenMayer/docker-sync#202]
Hey thanks for your awesome project! I've the following use case and I wanted to ask you if it's possible:

I use docker locally on my Mac to develop a huge rails app, with many files. I want to develop during the day with the data in my docker volumes, so it's super fast. However, I'm not interested in any syncing during work, since I do my development inside a docker container. I'm just interested in syncing the data from the containers back to my Mac drive at the end of the day.

What I've tried:
- setup unison strategy
- use "watch_strategy: disable"
- tried "docker-sync start" to start up the volume containers

That seems to start the containers, but then results in a `#<NoMethodError: undefined method 'watch_fork' for #<Docker_Sync::WatchStrategy::Dummy:0x007faa641ba600>`.

My ideia is that `docker-sync start` would start the volume containers. Then I would use `docker-compose` normally, and at the end of the day, just issued a `docker-sync sync` to sync the data back from the containers into my Mac drive.

Is this possible?

**Comment by EugenMayer** [comment]
watch_strategy: dummy to disable watching on the host, though, this disabled watching on the host side ( host to container ) and not yet on the container. So it would stop syncing host->container, but not container->host, and the latter you are interested in.

We would need to parametrize either https://github.com/EugenMayer/docker-image-unison-unox/blob/develop/supervisor.unison.conf#L2 or create a different supervisor service. Thats quiet a redesign here, would actually not work myself on such feature. If you like, try it yourself.

Probably, in your case, docker-sync does just not make sense. Just use `docker cp` to copy files back to your host whenever you (rarely) need this

**Comment by rubenfonseca** [comment]
@EugenMayer I guess I never heard about "docker cp"! Seems that it would solve my problem much better :) Thanks so much!!! You rock!

**Comment by EugenMayer** [comment]
Your welcome. Yeah `docker cp` is rather unknown, but extremely powerful.
