### ISSUE TITLE
How can I use docker-sync with docker for mac.

### ISSUE THREAD

**Issue by abdulwahid24** [EugenMayer/docker-sync#204]
Hi, 

I saw the wiki documentation and its seems like its been explained the configuration with docker-composer but in my case I am not using docker-composer instead using [docker for mac](https://docs.docker.com/engine/installation/mac/). Please let me know how can I configure docker-sync with docker for mac.

Thanks,
Abdul Wahid

**Comment by EugenMayer** [comment]
please read the docs and learn the docker basics. You are heavily mixing terms and seem to have huge issues with covering dockers basic terminology. Providing a docker guide is out of scope for this issue queue, sorry
