### ISSUE TITLE
Excluding folders

### ISSUE THREAD

**Issue by kbonnin** [EugenMayer/docker-sync#205]
I tried to use `sync_excludes: ['.git/', 'log/', 'tmp/']` like stated in the [wiki](https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration#docker-syncyml), but folders are not excluded by unison. 

`sync_excludes: ['.git', 'log', 'tmp']` does work though, so you might need to update the wiki and remove the ending `/`.

**Comment by EugenMayer** [comment]
If you are using unison, be aware that it has a different syntax then rsync:

https://github.com/EugenMayer/docker-sync-boilerplate/blob/master/unison/docker-sync.yml#L9

Use the name mode https://github.com/EugenMayer/docker-sync-boilerplate/blob/master/unison/docker-sync.yml#L10 which should then be very similar to rsync

**Comment by markoshust** [comment]
@EugenMayer how do you exclude directories with `native_osx`? i tried both ways and neither works.

**Comment by Flyrell** [comment]
@EugenMayer I'm also interested in what @markoshust has asked you. Is there any way to exclude folder(s) with native_osx?

**Comment by EugenMayer** [comment]
you can use excludes in native_osx the same way was in unison.

**Comment by bparise** [comment]
I encountered the same issue and found it was caused by `src` in my `docker-sync.yml` file having a trailing slash:

I changed `src: '../api/'` to `src: '../api'` and it works!
