### ISSUE TITLE
Rsync freezes with sync excludes

### ISSUE THREAD

**Issue by Limess** [EugenMayer/docker-sync#207]
Hi, thanks for a cracking tool.

I'm having some issues with `node_modules` folders and `rsync`. When `node_modules` are _not_ excluded, the sync works fine except with permissions errors on symlinks (i.e. https://github.com/EugenMayer/docker-sync/issues/161). The containers start and the application works to a degree though.

When I add `node_modules/` to `sync-excludes` I find `docker-sync-stack start ` just hangs on 
```shell
$ docker-sync-stack start
          ok  Starting rsync
          ok  account-sync container still running
          ok  account-sync: starting initial sync of $PATH_TO_APP
     command  rsync  --exclude='node_modules/' -ap -v $PATH_TO_APP/ rsync://127.0.0.1:10871/volume
```

I get no further output, even when trying to add extra flags such as `--progress` and `--stats` to `rsync`. The `sync_excludes` option _does_ work for other files/directories.

Settings: 
```
    sync_host_ip: '127.0.0.1'
    sync_host_port: 10872
    sync_excludes: [
      'node_modules/'
    ]
    sync_excludes_type: 'Path'
    sync_args: '-v'
    sync_strategy: 'rsync'
```

This is a docker-compose setup with 3 applications and an apache http server (2 docker images).

Any ideas what's up here? Happy to provide further info.

**Comment by EugenMayer** [comment]
please remove `sync_excludes_type: 'Path'` since its for unison only. 

The exclude looks pretty ok to me, i could imagine, thats quiet a lot of files and you probably use the very outdated rsync bundled in OSX. 

what does `rsync -v` tell you? You might want to upgrade rsync using `brew install rsync` - this helps a lot.

I would also tend to adivce you to use unison, it will also become the new standard in 0.2.0 - i switched from rsync to unison about 4 months ago and in the end, unison provides a more robust experience.

You can go either ways, but i would ensure to use a gnu rsync.

**Comment by Limess** [comment]
There are a lot of files - what I don't understand though is why a configuration which _doesn''t_ exclude `node_modules` copies relatively quickly, whereas upon adding it to `sync_excludes` it hangs indefinitely with no further output.

Rsync version is `3.1.2` via `brew`.

I'll give unison a go and see if it allows me to continue.

**Comment by Limess** [comment]
Unison seems to experience similar issues with directories on my machine. When ignoring certain directories, the `unison` command hangs, if they ignore is removed, progress is visible and the sync eventually completes successfully.

The problematic directories seem to vary per application (although each application has a similar structure) so I'm questioning whether there are permissions issues at play here?

Example top level permissions:
```
drwxr-xr-x   26 user  staff    884 Jan  8 18:57 .
drwxr-xr-x   35 user  staff   1190 Dec  2 15:52 ..
-rw-r--r--    1 user  staff     51 Aug 30 16:47 .babelrc
-rw-r--r--    1 user  staff    154 Dec 24 16:37 .dockerignore
-rw-r--r--    1 user  staff     72 Jan  8 18:57 .eslintrc
drwxr-xr-x   15 user  staff    510 Jan  8 19:45 .git
drwxr-xr-x    3 user  staff    102 Jul 12 17:01 .github
-rw-r--r--    1 user  staff    583 Sep 26 15:54 .gitignore
-rw-r--r--    1 user  staff    416 Jan  8 19:02 Dockerfile
-rw-r--r--    1 user  staff   3177 Aug  9 10:27 README.md
drwxr-xr-x   19 user  staff    646 Nov 22 14:23 bake-scripts
drwxr-xr-x    6 user  staff    204 Nov 22 14:23 config
drwxr-xr-x    5 user  staff    170 Dec  9 11:49 coverage
drwxr-xr-x    3 user  staff    102 Aug 15 16:02 documentation
drwxr-xr-x    3 user  staff    102 Sep 27 09:13 gulp-tasks
-rw-r--r--    1 user  staff   2878 Sep 27 09:13 gulpfile.js
drwxr-xr-x    3 user  staff    102 Jul 12 17:01 infrastructure
drwxr-xr-x    9 user  staff    306 Dec 24 17:06 logs
drwxr-xr-x  628 user  staff  21352 Dec  9 11:48 node_modules
-rw-r--r--    1 user  staff   2586 Dec 24 17:39 npm-debug.log
-rw-r--r--    1 user  staff  44357 Dec  9 10:37 npm-shrinkwrap.json
-rw-r--r--    1 user  staff   2250 Jan  8 18:57 package.json
-rw-r--r--    1 user  staff    423 Jul 28 14:32 project.json
-rw-r--r--    1 user  staff    262 Jan  8 18:57 server.js
drwxr-xr-x   18 user  staff    612 Jan  8 18:57 src
drwxr-xr-x   20 user  staff    680 Jan  8 18:57 test
```

here `bake-scripts` seems to prevent unison syncing:
```
drwxr-xr-x  26 user  staff   884 Jan  8 18:57 ..
-rwxr-xr-x   1 user  staff   628 Jul 12 17:01 00_app-name
-rwxr-xr-x   1 user  staff   111 Jul 12 17:01 01_chmod-config
-rwxr-xr-x   1 user  staff   204 Jul 28 14:32 02_cloudwatch_metrics.sh
-rwxr-xr-x   1 user  staff   833 Aug  2 09:49 10_node-environment
-rwxr-xr-x   1 user  staff  1039 Sep 20 09:54 20_ulimit
-rwxr-xr-x   1 user  staff   428 Jul 12 17:01 30_httpd
-rwxr-xr-x   1 user  staff  1092 Sep 20 09:54 31_httpd_worker
-rwxr-xr-x   1 user  staff   251 Aug 15 16:02 32_httpd_mode_deflate
-rwxr-xr-x   1 user  staff   678 Jul 12 17:01 40_datadog
-rwxr-xr-x   1 user  staff  1703 Aug  2 09:49 50_statsD
-rwxr-xr-x   1 user  staff   483 Nov 22 14:23 55_log_rotate
-rwxr-xr-x   1 user  staff   870 Jul 12 17:01 60_site-info
-rwxr-xr-x   1 user  staff   455 Jul 15 14:42 70_mfa_sshd
-rwxr-xr-x   1 user  staff  1230 Jul 15 14:42 71_mfa_duo
-rwxr-xr-x   1 user  staff   204 Sep  8 17:16 80_connections
drwxr-xr-x   6 user  staff   204 Sep  6 10:55 assets
-rw-r--r--   1 user  staff   445 Aug  2 09:49 bakeHelpers.py
```

**Comment by EugenMayer** [comment]
Well it must be some fs / permission related thing, probably rsync gets into a symlink loop.

I can at least tell you that:
 - i ran rsync with node_module excludes and do currently run unison with node_modules and a lot more excludes, without any issues
 - we have huge node_modules folders, so that is not the issue in general

It might depend of specific node_module plugins like nativ build ones with links into the local filesystem.

for now, i am not sure how to help you. try to isolate the issue, try to create a minimal node_module based project and put it on github - one you can reproduce this issue with. Add the docker-sync.yml and whatever needed to it, so i can reproduce it.

**Comment by Limess** [comment]
Thanks @EugenMayer. I'll try to reduce it down to a minimal set when I get time. Checked again with unison today and `-link false` as an argument to ignore symlinks(but still not excluding `node_modules`) and all three applications sync as expected so it's something in there.

**Comment by EugenMayer** [comment]
no progress
