### ISSUE TITLE
Be able to do docker-compose run?

### ISSUE THREAD

**Issue by greggilbert** [EugenMayer/docker-sync#210]
Hey there. First, I want to say that this is the most viable solution I've found for speeding up Docker for Mac, so thanks for putting this out.

I have a use case where we do `docker-compose run -e FOO=BAR app` to invoke a one-off command. It uses the app service defined in docker-compose.yml as the basis, and then does the `-e` to add more environment variables and so on.

Is there a way to do this within docker-sync? If not, what would it take to implement it?

**Comment by EugenMayer** [comment]
What do you mean with 'within'?

**Comment by greggilbert** [comment]
Sorry - I meant like, to be able to do this using docker-sync. Something like `docker-sync-stack run -e FOO=BAR app`, for example.

**Comment by EugenMayer** [comment]
Yet not possible, but would be not to hard to implement since we use Thor. We would need to check if the docker-compose gem supports that. 

Other then that, you can still start only docker-sync and then docker-compose manually using the ENV vars.

In addition providing those ENV vars in the docker-compose file will always work

**Comment by greggilbert** [comment]
Oh huh, I guess the `docker-compose run` thing does work. Not sure why it wasn't working for me before, but it seems okay now. So I guess we could close this, but it might be handy/useful to reimplement the docker-compose stuff through docker-sync. Or maybe it's overkill. Anyway, thanks!

**Comment by EugenMayer** [comment]
I think that it would need quiet some effort to channel all the things through docker-sync.

Anybody in need for a custom behavior should use docker-sync as a lib, like described here https://github.com/EugenMayer/docker-sync/wiki/7.-Scripting-with-docker-sync - this is what we also do. 

That way everybody can implement this 5% of individual customization he really is in need for
