### ISSUE TITLE
sync fails if current path has spaces

### ISSUE THREAD

**Issue by dipnlik** [EugenMayer/docker-sync#211]
My project is located at my Google Drive folder. `docker-sync start` tries to run `rsync -ap /Users/dip/Google Drive/Developer/sample-project/ rsync://localhost:10872/volume` and fails because it does not quote the first argument.

I tried changing https://github.com/EugenMayer/docker-sync/blob/master/lib/docker-sync/sync_strategy/rsync.rb#L70 locally then using the `deploy_locally.sh` script to install a custom version of the gem, but it did not change the output at all.  Unsure of how to test the change to be able to submit a PR, I thought it was best to at least report the issue.

**Comment by guice** [comment]
I just ran into this issue, too. My site is also on Google Drive.

**Comment by EugenMayer** [comment]
Thanks for reporting this. We will try to fix it, if its urgent, join the team and provide a PR :)

**Comment by EugenMayer** [comment]
@guice or @dipnlik could one of you guys try the new 0.2.0-beta1 release, its quickly to be installed see https://github.com/EugenMayer/docker-sync/wiki/How-to-install-the-new-0.2.0-prior-the-release 

If your setup works with that, close this issue please!

**Comment by EugenMayer** [comment]
tested using https://github.com/EugenMayer/docker-sync-boilerplate/blob/release/0.2.0/rsync/docker-sync.yml#L4 and it works. Ensure you notice the trailing-slash, it changed with 0.2.0, see https://github.com/EugenMayer/docker-sync/wiki/Migration-Guide
