### ISSUE TITLE
Rails quitting due to "pid" existing already.

### ISSUE THREAD

**Issue by kotowick** [EugenMayer/docker-sync#213]
Hello,

New to using docker-sync. But I see one issue so far - and maybe there is a fix for this?

For the first time of running docker-sync-stack start, rails starts up fine. If I stop docker-sync-stack (using control c), the rails server PID persist on the eugenmayer/rsync container under the project path (in this case, /webapp/tmp/pids/server.pid.

When I run it again, it fails because that server.pid file still exists.

Any solutions to this?

**Comment by EugenMayer** [comment]
This is out of scop. It would fail the same way using a regular volume, it basically has nothing to do with docker sync - for general docker support please use other channels, thank you

**Comment by maletor** [comment]
What is the resolution here?
