### ISSUE TITLE
File group wrong inside volume mount

### ISSUE THREAD

**Issue by greggilbert** [EugenMayer/docker-sync#216]
Hey. One of my colleagues was using the rsync strategy, but he switched over to Unison. Now when we look in the mounted volume, the permissions are a mess: some are correct (in our case, `root:root`) but others are wrong (it says `root:dialout`, where the gid of `dialout` matches the local user's gid).

Is it possible that there's a permissions issue when switching over from rsync to unison? I know that the unison stuff doesn't necessarily need permissions, but I see in the config you can specify a userid. Can you also do that for group?

**Comment by EugenMayer** [comment]
Hey, yet we do not manage the group in unison see https://github.com/EugenMayer/docker-sync/issues/40 .. just because its not implemented yet. Primary this tough should be enough for dev-purposes, i guess.

If you need that one urgently, feel free to contribute :)

**Comment by mickaelperrin** [comment]
@kadaan has done most of the work in the PR https://github.com/EugenMayer/docker-image-unison-unox/pull/2

**Comment by kadaan** [comment]
If someone could get this over the finish line, that would be great.  I moved on to a different solution, so probably won't be finishing this PR.

**Comment by EugenMayer** [comment]
@kadaan just curious, since docker-sync is probably the only solution offering uid or gid mapping and it seems important to you, what did you pick?
