### ISSUE TITLE
[QUESTION] Sync on remote server

### ISSUE THREAD

**Issue by mickaelperrin** [EugenMayer/docker-sync#218]
I am currently thinking about using a remote development server to benefit from a better bandwidth  and reduce latency while working on webhooks.

I was wondering if some of you have think about this and already try to use docker-sync to sync the host with a container running on remote machine.

I think that with some ssh tunnels it should work. Any feedback on this ?

**Comment by EugenMayer** [comment]
I would never do this in such an environment. Since i know you use IntelliJ, use a scp deploymentserver with "auto-deploy on" - this is much more efficient since the IDE knows what you have changed. You can also doe a sync, a merge sync and much more.

**Comment by mickaelperrin** [comment]
@EugenMayer Indeed, this is what I thought about initially. But the issue is still  the same, how do you sync back dependencies (composer) and CMS generated content ?

Maybe it's easier to write some rsync scripts, but I would love to keep my current workflow as much as possible. In theory, unison was written to sync remote servers, the question, of course, is to know how it performs on poor DSL connections.

**Comment by EugenMayer** [comment]
Intellij has sync, 2 ways, just press the sync button and it will do that. If you want that "automatically" thats not possible, but you most probably always know when you run composer on remote or similar?

**Comment by mickaelperrin** [comment]
Ah great ! I didn't know IntelliJ syncs two ways !
