### ISSUE TITLE
Make startup asynchronous?

### ISSUE THREAD

**Issue by baohx2000** [EugenMayer/docker-sync#220]
I have a somewhat complex environment which takes about 8 different sync containers since different folders end up living in the same place on the end-product containers.

This means spinning up `docker-sync start` can take a few minutes because it spins up each one in order.  I'm guessing this would be much faster if it were asynchronous. Granted, the initial output would probably be somewhat ugly, but that could probably be fixed by using a logger which attaches context to the output.

**Comment by EugenMayer** [comment]
See https://github.com/EugenMayer/docker-sync/pulls or use docker-sync as a library and background the way you want, see https://github.com/EugenMayer/docker-sync/wiki/7.-Scripting-with-docker-sync
