### ISSUE TITLE
[UNISON] Filename case change not synced in container

### ISSUE THREAD

**Issue by mickaelperrin** [EugenMayer/docker-sync#221]
Given you want to change a filename from `test.txt` to `Test.txt`.

The case is changed on the host but not propagated in the container.

**Comment by rodrigoaguilera** [comment]
Maybe is related to the fact that HFS+ is case insensitive and the only solution is to convert to case-sensitive but that breaks other apps.
http://www.cio.com/article/2868393/linus-torvalds-apples-hfs-is-probably-the-worst-file-system-ever.html

**Comment by mickaelperrin** [comment]
@rodrigoaguilera Tanks.

Interesting, I did'nt take the time to do any search so far.

Currently, the workaround is to backup the file under a different name, delete the file in the container, rename.

**Comment by EugenMayer** [comment]
Sorry but this is unfixable, that is exactly  what @rodrigoaguilera supposed. Its like the same issue with git under OSX

You can fix it by using case sensitive HFS partition, but be sure that you do not do this for the root partition..or you will have hard times.
