### ISSUE TITLE
safegard to avoid bad sync (not unique name)

### ISSUE THREAD

**Issue by gagarine** [EugenMayer/docker-sync#227]
If you have multiple project you can do something very messy with 2-way sync if you not careful and use the same name for two different project. Specially if you didn't destroy the sync volume.

Right now the doc is pretty clear:
```
syncs:
  # IMPORTANT: this name must be unique and should NOT match your real application container name! 
  fullexample-sync:
```

But I was wondering if we can make it impossible to do this mistake
- generate the name with a  hash?
- generate the name with project path?
- store every used names in a files in the home directories, and do not allow duplicate?
- ...

**Comment by EugenMayer** [comment]
well that is no good way to do that, we already tried something like namespacing and things like that.

In general, this is a tool for developers which should read the docs and also understand the concept at least fundamentally. Docker-sync will never be that DAU tool to be run without using the own brain :) It would be cool, but hardly anybody will put that  kind of effort into that, rather new feature or robustness will be implemented.

Anyway thanks for the feedback!

**Comment by gagarine** [comment]
I understand. Perhaps an enterprise will be interested to work on that to minimize juniors error..

**Comment by gagarine** [comment]
What about an option to automatically run `docker-sync clean` when docker-sync is stopped? So it will rebuild the volume each time avoiding any risk of collision. I guess the problem is the volume will be used by the containers.

**Comment by EugenMayer** [comment]
No people want to start and stop the stack without flushing the whole data. Docker-sync shall be a tool for people with advanced needs, this said, a automatic clean is nothing what we shall do.

Detecting when a conflict might happen is a lot of work and by far not bullet proof, false positives included.

If you want, you can work on it, at least for me, i do not focus this, sorry

**Comment by gagarine** [comment]
ok!
