### ISSUE TITLE
Name daemon.output daemon.log

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-sync#233]
I would expect the log file to be suffixed with .log - any reason you have chosen .output?

**Comment by masterful** [comment]
`.output` was the default - and I didn't see anything in the [documented params](https://github.com/thuehlinger/daemons/blob/master/lib/daemons.rb#L283) when I last looked for changing that. But I have to imagine there is one ...

**Comment by EugenMayer** [comment]
Thank you!
