### ISSUE TITLE
In non-daemon mode print a hint as the last line to tell the user how to use the daemon mode

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-sync#234]
I would not make the daemon mode the new default right away ( even though that will make sense in the end ) - nevertheless we should make the users aware of its existent. 

We should print something like "to run this in the background start `docker-sync start -d`"

**Comment by masterful** [comment]
I'm thinking about using the global config to only show this message once, or would you prefer it shows up periodically like `UpdateCheck`, or simply every time?

**Comment by EugenMayer** [comment]
I guess it won't harm putting it on the end of every non daemon mode startup, it's just one line more. No strong feeling here either way is ok

**Comment by EugenMayer** [comment]
Also here, great work!
