### ISSUE TITLE
create docker-sync-daemon bin-stub

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-sync#235]
Beside we will offer `docker-sync -d` we could also offer docker-sync-daemon as a stub enforcing this paramter. 

Any thoughts on that @mickaelperrin @masterful ?

**Comment by EugenMayer** [comment]
@masterful i have implemented the stub and changed the documentation to now use `docker-sync-daemon` ... in general it is a much cleaner interface now, only offering start/stop/clean/log since this is the only thing matters for daemon mode.

Just check the docks and have a look at https://github.com/EugenMayer/docker-sync/blob/release/0.2.0/tasks/daemon/daemon.thor

Be bold to change option descriptions, adding banners or whatever

**Comment by masterful** [comment]
Thank you 😄 

Why did we remove `log` from `Sync`, though? Wouldn't it be easier to leave `log` in `Sync` and stub the method in `Daemon` the same way we're stubbing the other methods?

**Comment by EugenMayer** [comment]
@masterful arg, you right, with both. You volunteer patching this? :)

**Comment by masterful** [comment]
lol - sure

**Comment by EugenMayer** [comment]
@masterful i moved the logs and commited it, no need for you to dive into that. Thanks for the hint

**Comment by masterful** [comment]
:+1: Sorry I couldn't get to it sooner

**Comment by EugenMayer** [comment]
no worries, i worked on some other issues anyway, it was just a little task anyway
