### ISSUE TITLE
Add --version command

### ISSUE THREAD

**Issue by gagarine** [EugenMayer/docker-sync#242]
`docker-sync --version` can be useful to quickly check which version is running. Specially if you try to help someone...

**Comment by EugenMayer** [comment]
no as easy to implement as you might suggest, but feel free to PR this. I bet you can do this also :)

**Comment by EugenMayer** [comment]
I will help you with that, thank you for the idea

**Comment by EugenMayer** [comment]
Note to myself: use VERSION which should now be packaged into the gem. Allow --version and -v on sync and stack

**Comment by mickaelperrin** [comment]
Great to see #138 reborn :)

**Comment by EugenMayer** [comment]
yeah, as stated above, we had this, but not using VERSION but rather "gem" as a source is not even slightly trivial, see the upgrade code :) i managed to do this in the meantime but forgot about this feature. Makes a lot of sense to have it.

But in the end, we have auto-upgrade on by default, so right no the version distribution is like 95% on latest version - thats why i actually never ask for the docker-sync version and thus this command will not be a game changer

**Comment by EugenMayer** [comment]
implemented
