### ISSUE TITLE
Option to set default sync_host_ip from command line

### ISSUE THREAD

**Issue by jankonas** [EugenMayer/docker-sync#245]
Hi, thanks for this awesome piece of SW :-) I have one feature request - could you please add a command line option (or something similar - see the use case) to set default value for the sync_host_ip configuration directive?

Use case: In our team, we are working on many projects and use docker-machine and docker-sync on all of them. Since the tech-savviness of the team members varies and also it is more convenient for all, we have a custom startup script that loads docker-machine environment, starts docker-sync and docker containers (using docker-compose) and prepares the project environment. For now, we all use just one docker-machine on our computers so the host IP is the same and can be in the sync configuration file, but I would like to make it more error-prone and configure the host IP in the startup script. Of course I can modify the configuration file there, but it is indexed in git, so that is not the way I want to go.

Thank you

**Comment by EugenMayer** [comment]
@JanKonas pull requests are accepted regularly :)

Just update the global_config which is already in ~/.docker-sync-globaly.yml .. add your value and then try to consume it at the strategies like https://github.com/EugenMayer/docker-sync/blob/master/lib/docker-sync/sync_strategy/rsync.rb#L71

using Config.global_config to load the configuration beforehand

For this feature is out of scope, so without community effort, that will not going to happen. So join us :)

**Comment by EugenMayer** [comment]
Closing this, reopen if somebody wants to pick this up, thanks
