### ISSUE TITLE
Write changelogs for 0.2.0

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-sync#246]
We are about to release, so we need to grasp what is new, what has changed, what has fixed

**Comment by EugenMayer** [comment]
Could you guys help me a bit with that? making short entries for each topic we covered in the 0.2.0 milestone  https://github.com/EugenMayer/docker-sync/milestone/10?closed=1

just put it here https://github.com/EugenMayer/docker-sync/wiki/5.-Changelog

**Comment by EugenMayer** [comment]
i made a first shot, feel free to correct/add/remove whatever is wrong

**Comment by masterful** [comment]
:+1: Looks good to me so far - added some links and a bullet point about unison starting slightly faster now

**Comment by EugenMayer** [comment]
done, added some minor stuff, thanks for reviewing @masterful
