### ISSUE TITLE
windows/cygwin problems with docker-sync start with 0.2.0

### ISSUE THREAD

**Issue by pushontom** [EugenMayer/docker-sync#248]
Version 0.1.5 worked well under cygwin if disabling the watch task. 

Version 0.2.0 will not start due to dependencies on macfsevents and doesn't recognise fsevents being installed on the system. 

I understand docker-sync is for OS X, however until 0.2.0, it's been working well for me under Windows 10 & cygwin. 

The following error is return on "docker-sync start": ImportError: No module named fsevents

**Comment by EugenMayer** [comment]
Well you already noticed that we do only osx, if you really want to get it running, you will need to put a lot of effort into it debugging it. I am open to implement patches, but working on Linux / cygwin support myself I cannot offer sorry

**Comment by pushontom** [comment]
I've manually applied this patch and I can confirm it allows me to use the rsync method still. I will test with unison asap.

**Comment by EugenMayer** [comment]
@pushontom any way you would make a small wiki page on how to get your setup up and runngin? It would have 2 reasons: i would understand how / what you do to be able to follow you, but also others being able to reproduce or even utilize this for windows development

**Comment by pushontom** [comment]
@EugenMayer sure thing, I'll get that together as soon as I can

**Comment by EugenMayer** [comment]
Closing this for now,feel free to reopen it when you move on
