### ISSUE TITLE
Container Log for Sync Volume shows errors: 

### ISSUE THREAD

**Issue by pushontom** [EugenMayer/docker-sync#258]
---- beginning of output ---

user with uid 0 already exist and its root
/entrypoint.sh: ignoring /docker-entrypoint.d/*
/usr/lib/python2.7/site-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2017-02-21 16:27:45,283 CRIT Supervisor running as root (no user in config file)
2017-02-21 16:27:45,283 WARN Included extra file "/etc/supervisor.conf.d/supervisor.daemon.conf" during parsing
2017-02-21 16:27:45,291 INFO RPC interface 'supervisor' initialized
2017-02-21 16:27:45,292 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-02-21 16:27:45,292 INFO supervisord started with pid 1
2017-02-21 16:27:46,294 INFO spawned: 'rsync' with pid 20
2017-02-21 16:27:47,306 INFO success: rsync entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

---- end of output ---

Used to see the rsync files being listed in the log as it copied the files across, no loner have any output so not sure if sync has finished

**Comment by EugenMayer** [comment]
which errors are you refering to ?

> /usr/lib/python2.7/site-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
> 'Supervisord is running as root and it is searching '
> 2017-02-21 16:27:45,283 CRIT Supervisor running as root (no user in config file)
> 2017-02-21 16:27:45,283 WARN Included extra file "/etc/supervisor.conf.d/supervisor.daemon.conf" during parsing
> 2017-02-21 16:27:45,291 INFO RPC interface 'supervisor' initialized
> 2017-02-21 16:27:45,292 CRIT Server 'unix_http_server' running without any HTTP authentication checking
> 2017-02-21 16:27:45,292 INFO supervisord started with pid 1
> 2017-02-21 16:27:46,294 INFO spawned: 'rsync' with pid 20
> 2017-02-21 16:27:47,306 INFO success: rsync entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

None of those are critical, you can safely ignore them
