### ISSUE TITLE
Versions before 0.2.0 are broken

### ISSUE THREAD

**Issue by alkazar** [EugenMayer/docker-sync#259]
Attempting to start the sync container gives:
```
        ok  Starting rsync
rsync: did not see server greeting
rsync error: error starting client-server protocol (code 5) at main.c(1719) [sender=3.1.2]
       error  Error starting sync, exit code 5
```

`docker-sync` uses a `latest` tag and the image is updated on every run. This means after the 0.2.0 release, older versions were borked due to an incompatibility of older docker-sync versions with newer rsync container. It is unknown if the same issue affects people using unison.

This was solved by upgrading to docker-sync 0.2.0.

In any case, docker-sync should reference a specific version of the rsync and unison containers instead of `latest`. That way future updates will not break old versions.

**Comment by EugenMayer** [comment]
Thank you for the suggestion.

I am not planning to do so, that is why auto-update is in place. The reasons are fairly simple:

 - i am not going to support any old version in this issue queue and i am not going to find myself in the position to ask everybody "which version" "but that has been fixed"
 - maintain the infra for each version forces me to add a lot more to the project - from CI to a buildsystem across different components - and i am simply not willing to put this time into it

That said, i was and i fully aware of docker-sync has been broken for anybody running with auto-update ( so updating the images ) but not docker-sync. I do not want to support this kind of version variarity - there shall be only one, and thats the latest.

If people do not like this, they might either build their own CI, use / copy the image ( docker-sync allows you to define you own images ) and build whatever is needed to maintain a older version - but i guess i wont. Its just an extra effort i cannot offer - sorry.

**Comment by alkazar** [comment]
I understand. Thanks for clarifying your position.
