### ISSUE TITLE
Undefined local variable `cmd2`

### ISSUE THREAD

**Issue by tdkn** [EugenMayer/docker-sync#264]
When I run `$ docker-sync-stack start`:

```
$ docker-sync-stack start
     warning  Could not find unison-fsmonitor (for file watching) binary in $PATH. We try to install unox now (for manual instracutions see https://github.com/hnsl/unox.)
Shall I install unison-fsmonitor for you? (y/N) N
       error  undefined local variable or method `cmd2' for Preconditions:Module
Did you mean?  cmd1
```

I found problems at [line #58](https://github.com/EugenMayer/docker-sync/blob/28e0397c511cb9fec9e5d209049426ce8a301a06/lib/docker-sync/preconditions.rb#L58).

**Comment by EugenMayer** [comment]
no,  && #{cmd2} needs to be removed

**Comment by EugenMayer** [comment]
fixed, thanks for reporting this.

Out of curiosity, why people press "N" here? What is the motivation?
