### ISSUE TITLE
ability to configure sync manager with yaml string instead of config_path

### ISSUE THREAD

**Issue by eelkevdbos** [EugenMayer/docker-sync#267]
The ability to supply a (yaml formatted) config string is a welcome addition when composing your own sync script. It prevents writing a file to disk and makes dynamic configuration a more viable strategy.

**Proposal**: 
- Do not raise an exception if an inline configuration was supplied during initialisation
- Add a method to the ConfigTemplate class that will 'just' YAML load the config_string supplied

**Comment by EugenMayer** [comment]
Great addition, thank you for taking care!
