### ISSUE TITLE
sync_excludes and watch_excludes don't work

### ISSUE THREAD

**Issue by sandrodz** [EugenMayer/docker-sync#272]
<img width="692" alt="screen shot 2017-03-16 at 11 26 00 am" src="https://cloud.githubusercontent.com/assets/8479569/23986093/dfeab9a2-0a3b-11e7-9235-98eb1661abc1.png">

**Comment by EugenMayer** [comment]
Read the unison-documentation on how to create the excludes on how they are working. In addition, right now, we have no watch_excludes

**Comment by sandrodz** [comment]
@EugenMayer sync_excludes I've .git, and as far as I understand default of docker-sync `sync_excludes_type` is `Name` - shouldn't my config be working as intended?
