### ISSUE TITLE
docker-sync goes out of sync errors accumulate and nothing is being synced

### ISSUE THREAD

**Issue by sandrodz** [EugenMayer/docker-sync#273]
I've to restart docker-sync (unison) every hour practically. When working with large file sets, at some point, errors start to appear - cannot sync etc. And nothing is being synced anymore.

I can replicate this easily when deleting files on host. for example gulp build that clears build directory and recreates in 50% of cases breaks docker-sync.

What info can I provide to further diagnose this issue? its becoming really annoying.

**Comment by mickaelperrin** [comment]
How many files are you watching ?

Have you correctly configured `max_inotify_watches` ?

**Comment by sandrodz** [comment]
@mickaelperrin I have 400921 files in synced dir (find . -type f | wc -l).

`max_inotify_watches ` is this kernel feature?

**Comment by mickaelperrin** [comment]
This is a docket sync config option

**Comment by sandrodz** [comment]
Sorry but there is nothing about it here: https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration

Where can I read up more about it? to what number do I set it? why do I set it?

**Comment by sandrodz** [comment]
I'm not getting the same error though: https://github.com/EugenMayer/docker-sync/issues/125

I found this: https://github.com/EugenMayer/docker-sync/blob/c4e9f21bc4c6510e8186e25765a1f786e31ad470/example/docker-sync.yml#L78

**Comment by EugenMayer** [comment]
400921 is just way too much, use excludes and max_files - i am not sure you will ever be able to stablize this amount of files

**Comment by sandrodz** [comment]
@EugenMayer working with `node_modules` unfortunately they are huge. What is recommended file size that you've test and is workable? under 100K?

**Comment by EugenMayer** [comment]
About 45k, beside that there is no reason to sync node_modules

**Comment by sandrodz** [comment]
@EugenMayer my aim is to dockerize all dev tools including nodejs. So if I'm running node inside container, same speed problems arise if I don't use docker-sync.

**Comment by sandrodz** [comment]
Besides, default laravel install has about 120k files.

**Comment by EugenMayer** [comment]
You should overthink you POV.

You sync what you potentially will be changing, not the entire dependency tree. Anything else is thoughts about how you build your image.

We are not setting any hard limits for "how many files you can watch until unison goes crazy" but well, apparently they are some in terms of speed, CPU usage and reliability.

So i would say, without you limiting the files you SYNC to a reasonable number, we cannot really help you.

**Comment by sandrodz** [comment]
Okay lets overthink my POV.

Laravel has Vendors dir which contains most of the files. It doesn't need to be synced, and changes only occasionally. But it needs to be inside volume container, otherwise app won't run, but it doesn't need to be synced or watched at all.

How do I make this work?

**Comment by EugenMayer** [comment]
Those are basic docker concepts on how to make an image, how to have an intelligent image bootstrap with provisioning and things like this - very much out of scope for docker-sync. 

I am pretty sure you find some of those googling arround

**Comment by sandrodz** [comment]
I found this in wiki, is this still relevant?

if I understand correctly this is exactly what I need, docker-sync will create volume copy ALL files, but won't sync those dirs back and forth?

```
# docker-sync.yml
syncs:
  appcode-unison-sync:
    ...
    sync_args:
        - "-ignore='Path .idea'"          # no need to send PHPStorm config to container
        - "-ignore='Path .git'"           # ignore the main .git repo
        - "-ignore='BelowPath .git'"      # also ignore .git repos in subfolders such as in composer vendor dirs
        - "-ignore='Path var/cache/*'"    # don't share the cache
        - "-ignore='Path var/sessions/*'" # we don't need the sessions locally
        - "-ignore='Path node_modules/*'" # remove this if you need code completion
        # - "-ignore='Path vendor/*'"     # we could ignore the composer vendor folder, but then you won't have code completion in your IDE
```

**Comment by EugenMayer** [comment]
Do yourself a favour, step 2 steps back, take your time understanding how docker images work. This will help you massively solving this issue, finding the right concept. Docker sync won't help you with all the tasks, that's the point
