### ISSUE TITLE
Can not create or remove files in base-directory

### ISSUE THREAD

**Issue by matleh** [EugenMayer/docker-sync#276]
All synced files and directories are owned by user `dockersync` but the synced directory itself is owned by `root`. The unison process also runs as user `dockersync`. This leads to failures when files within the top-level directory are created or removed.

```
UNISON 2.48.4 started propagating changes at 11:05:09.28 on 22 Mar 2017
[BGN] Deleting htmlcov from //381ee662c025//app
[BGN] Deleting errors.txt from //381ee662c025//app
Failed: Error in creating directory:
Permission denied [mkdir(/app/.unison.htmlcov.fe86110a336f164e0dbdeddcf3cf220f.unison.tmp)]
Failed: Error in deleting:
Permission denied [unlink(/app/errors.txt)]
UNISON 2.48.4 finished propagating changes at 11:05:09.28 on 22 Mar 2017
Saving synchronizer state
Synchronization incomplete at 11:05:09  (0 items transferred, 0 skipped, 2 failed)
  failed: htmlcov
  failed: errors.txt
```

Maybe I am missing a configuration option.

If not, I see two possible solutions:
- chown the base-directory in some entrypoint script
- go one step further and not only make the "dest" parameter optional but remove it and make sure that the `/sync` directory is owned by `dockersync` user in the Docker image - Docker volumes take over the permissions of existing files/directories within a Docker image

For some reason, file creation and deletion does work when I stop and restart `docker-sync` - is there a different mechanism at work?

**Comment by EugenMayer** [comment]
Please paste your docker-sync.yml and your docker-compose.yml. .. the relevant option is are sync_useruid

**Comment by EugenMayer** [comment]
reopen the issue if you find time to work on this issue or keep it closed if it has been solved in the meantime. Thanks!
