### ISSUE TITLE
Group Two way sync

### ISSUE THREAD

**Issue by anaelChardan** [EugenMayer/docker-sync#279]
Hi ! 

Sorry to open an issue for that, but I wanted to know how it is possible to manage group mapping with unison or how do you arrive to deal with it ?

I need to have all my files with docker:docker permissions :) (I found a way using the chown on this folder but it's not cool)

Thanks :)

**Comment by EugenMayer** [comment]
Yet not possible and mainly not needed, since fixed the user permission is sufficient and basically all cases i have yet seen.

There has been some work started to support this, but hardly any real focus on that - so if you really need this, join the team, implement it :)

**Comment by anaelChardan** [comment]
Ok, thanks :)
