### ISSUE TITLE
Run docker-compose command with docker-sync

### ISSUE THREAD

**Issue by bilby91** [EugenMayer/docker-sync#280]
Hello,

It is possible to run commands with `docker-sync` the same way we do with `docker-compose` ?

I frequently do `docker-compose run app rspec .` for example, with `docker-sync` installed it started to failed because it can not find the files, I guess they are not synced correctly due to not using the `docker-sync` commands.

Is there any workaround ?

Thanks!

**Comment by EugenMayer** [comment]
yes you could, but you would do it a different way.

You start `docker-sync-daemon start` which does only setup the volumes and the sync, then you use docker-compose with all the magic you used before - just be sure the sync has finished ( wait 10 seconds ) so you are pretty free in this regard

**Comment by bilby91** [comment]
@EugenMayer Thanks!
