### ISSUE TITLE
Performance difference between a freshly rebooted mac and one that's slept a bit

### ISSUE THREAD

**Issue by schniper** [EugenMayer/docker-sync#282]
On a regular Laravel app I was getting around 300ms times using docker-sync. Compared to about 4 times that without it.
After updating Mac OS and rebooting, the time dropped to 80ms.
One day later, the time is back to a consistent 300ms.

Any idea why that is or how can I help debugging?
Thanks.

**Comment by EugenMayer** [comment]
That is rather a docker for Mac issue in general, we have the same here leading to reboot in ever office day start.

Nothing we could do about on the docker-sync part, you should notice the same performance degration with docker sync
