### ISSUE TITLE
Syncing failing after docker-sync restart

### ISSUE THREAD

**Issue by Vizualni** [EugenMayer/docker-sync#283]
After starting first `docker-sync start` command everything is fine. After stopping it, I am getting the following error:
```
     info            Error starting sync, exit code 0
     message
     message  Contacting server...
Fatal error: Lost connection with the server
```
This is the command that caused it. After running it manually (copy & pasting from docker-sync output) it appears to be working.
```
unison /some-path -auto -batch -prefer '/some-path' -copyonconflict socket://127.0.0.1:32781
```

(I have removed real path and put `/some-path` instead).

**Comment by EugenMayer** [comment]
Paste your docker-sync.yml please
