### ISSUE TITLE
Cannot use Unison

### ISSUE THREAD

**Issue by jerome-arzel** [EugenMayer/docker-sync#284]
When I start my configuration with rsync, everything is OK. When I change the strategy to unison, there is an error:

~~~sh
docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' myapp-sync
# Error getting mapped port, exit code 0
~~~

I looked at your code, and port 5000 is hardcoded since February (and the port argument is not used).

When I run docker inspect myapp-sync, here what I got: there is the port 873 only.

~~~
    "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "12e1c2882999bc71bc3e418454bca9535ddd7f347faac79a378913ac5c70dc97",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "873/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "10871"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/12e1c2882999",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "8b8791a93a10d5e11455ffca273f4a1ba123cd6eef7335f0162a0a6bc80b819d",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "6b58dc3542649d28dc7b58ecdf3f678739388619b3790fd41d8792215ae4733d",
                    "EndpointID": "8b8791a93a10d5e11455ffca273f4a1ba123cd6eef7335f0162a0a6bc80b819d",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "[...]"
                }
            }
        }
~~~

**Comment by EugenMayer** [comment]
The port is inside the container, not the host. On the host a random port is used, this is what this code is for

Which docker-version are you using? Are you using docker for mac? Which OS-Version are you using?

Please paste your docker-sync.yml

**Comment by jerome-arzel** [comment]
Docker for mac yes, Docker version 17.03.0-ce, build 60ccb22

~~~
version: '2'
options:
  verbose: false
syncs:
  myapp-sync:
    src: './www/'
    sync_host_ip: '127.0.0.1'
    sync_host_port: 10871
    sync_strategy: 'rsync'
    sync_excludes:
      - '.DS_STORE'
      - '.git/'
      - '.gitignore'
      - '.gitmodules'
      - '.idea/'
      - 'phpunit.xml'
    watch_excludes:
      - '.DS_STORE'
      - '.git/'
      - '.gitignore'
      - '.gitmodules'
      - '.idea/'
      - '.tmp/'
      - 'build/'
      - 'phpunit.xml'
      - 'var/'
      - 'vendor/'
      - 'node_modules/'
~~~

**Comment by EugenMayer** [comment]
- watch excludes are not possible this way with unison, remove it for now
- sync_exclude syntax is different with unison, the default is Name mode, please use the docs to find a better understanding and adjust your setup
- remove verbose: false - the defaulted
mor import:
 - remove host_port completely this will fix you issue

**Comment by jerome-arzel** [comment]
sync_host_port removed, and issue solved for me. So we cannot set `sync_host_port` at all?

**Comment by EugenMayer** [comment]
You do no longer need to choose a specific port, a random free port will automatically be used. This avoids conflict of syncs if the same port would have been used in the config, the port should simply not be something you are interested in

**Comment by dima-loburec** [comment]
@EugenMayer Please provide some comments for the "watch_excludes". It is very confusing, when we have a setting, which not understandable for using. For native os x strategy I also don't now how to exclude some directory from watching. Thanks for the repo!

**Comment by EugenMayer** [comment]
watch excludes cannot be used with unison or native_osx right now, only sync_excludes

For the rest, its http://www.cis.upenn.edu/~bcpierce/unison/download/releases/stable/unison-manual.html#ignore

**Comment by dima-loburec** [comment]
@EugenMayer Thanks!
