### ISSUE TITLE
Poll: Rewrite in golang at some point

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-sync#29]
Are there any strong feelings against rewriting docker-sync into golang? It has some pros:
 - no dependency on the host ( no ruby needed )
 - Better type support, interfaces, abstract classes .. since we have a strategy patter, it could make sense
 - ?

Cons:
 - probably less people know golang ( but i bet a lot want to start using it :) )
 - missing gems (are there any?)
 - ?

**Comment by gagarine** [comment]
On my side, I'm not a big fan of gem (certainly because I'm don't really know ruby). When I see I have to do a gem install to get a tool, I'm always worried it's going to break my system at some point. Definitely more interested to learn more golang than ruby.

**Comment by EugenMayer** [comment]
gems are pretty stand-alone, even though they fetch dependencies, several version of each dependency can exist on one system. Thus, every tool can pick its versions and they do not conflict. Breaking a system by installing a gem is something i yet never heard of, you should not worry about that.

Thanks for the feedback though

**Comment by EugenMayer** [comment]
Closing this effort for now - too much ruby based contributions and language integrations. Reopen if someone has good points on moving the focus on this again
