### ISSUE TITLE
Unison support for group mapping

### ISSUE THREAD

**Issue by pcambra** [EugenMayer/docker-sync#292]
Is there any way for unison to support a group the same way that sync_userid is done? or maybe modify the mapping permissions?

I've tried to use rsync instead as the docs say you do if you need groups mapping but I get errors on connecting. Reviewed #201 but trying to change the host ip by 127.0.0.1 or removing 'sync_host_ip' did not help.

Output from `docker-sync start`

```
     command  rsync -ap '/my_folder' rsync://localhost:10871/volume
rsync: failed to connect to localhost (::1): Connection refused (61)
rsync: failed to connect to localhost (127.0.0.1): Connection refused (61)
rsync error: error in socket IO (code 10) at clientserver.c(125) [sender=3.1.2]
       error  Error starting sync, exit code 10
```

I'm on OSX and unison works fine but I need the files mapped to a different user. Also tried different ports.

Thanks!

**Comment by EugenMayer** [comment]
Please search the issue queue, th ere is a FR but yet no work has been done. User mapping works with unison though, and that's usually enough for development purposes

**Comment by pcambra** [comment]
Hi, there are only 7 issues open and I don't think any refers to this.

In the case I have here, just the user mapping is not enough, that's why I asked

**Comment by EugenMayer** [comment]
https://github.com/EugenMayer/docker-image-unison/pull/2 its just not yet implemented and i am currently not focussing on it.

You can try to test it and write a docker-sync PR for the option, but for know, not planning to put my work into this - pull requests are of course very welcome. Feel free to reopen this issue if you really start working on this
