### ISSUE TITLE
docker-sync not running after upgraded to MacOS sierra

### ISSUE THREAD

**Issue by baiyu-brandboom** [EugenMayer/docker-sync#296]
Upgraded to Sierra and docker-sync stopped working. It gives the following error message:

error  Error starting sync, exit code 0
     message  
    message  Fatal error: Preference file default not found
     success  Unison server started
       error  Error starting sync, exit code 0
     message  
    message  Fatal error: Preference file default not found
Fatal error: Preference file default not found

When I run it as sudo, this error message disappears but the files are not syncing. It says module fswatch-moniter not found.

**Comment by EugenMayer** [comment]
Please uninstall docker-sync and install it again, before installing remove `rm ~/.docker-sync-global.yml`

If that does not help, please install watchdog instead of macfsevents, see https://github.com/EugenMayer/docker-sync/pull/290

**Comment by EugenMayer** [comment]
please reopen the issue if you continue working on the issue

**Comment by EugenMayer** [comment]
i took care of this by creating a homebrew formula https://github.com/EugenMayer/homebrew-dockersync/blob/master/Formula/unox.rb and fixing unox to support setuptools/pip install https://github.com/hnsl/unox/tree/0.2

In addition, with 0.3.0 people are forced to reinstall unox and use the new one, including the watchdog fix
