### ISSUE TITLE
End_of_file exception raised in loading archive... Unison issue?

### ISSUE THREAD

**Issue by okashino** [EugenMayer/docker-sync#298]
I'm getting this issue when starting up my stack and the sync process stops working:
```
$ docker-sync-stack start
       note:  You can also run docker-sync in the background with docker-sync --daemon
          ok  Starting unison
       error  Error starting sync, exit code 0
     message
     message  Contacting server...
Connected [...]
Looking for changes
Fatal error: Server: End_of_file exception raised in loading archive (this indicates a bug!)
     success  Unison server started
       error  Error starting sync, exit code 0
     message
     message  Contacting server...
```
My environment:
mac: OS X 10.11.6
docker-sync: 0.2.3
ruby: 2.2.2p95
unison: 2.48.3

**Comment by EugenMayer** [comment]
This is a unison issue, please search in their issue queue or Google. My smell is, you are syncing something like Dev/random, a stream and not a file. Try to enable verbose and see on which file it fails.

In any case, try our boilerplate to ensure docker sync is working in general

**Comment by r00takaspin** [comment]
`docker-sync clean && docker-sync start` helped for me.

**Comment by elvinristi** [comment]
for me helped following:

- remove on both client and dev profile files from `~/.unison/`
  - cudos to http://ocditimban1.blogspot.com/2014/01/fatal-error-endoffile-exception-raised.html

On mac location is `~/Library/Application\ Support/Unison/`

Re-run sync.
