### ISSUE TITLE
docker-sync creates a directory for each of external volumes inside project root directory

### ISSUE THREAD

**Issue by rashidul0405** [EugenMayer/docker-sync#311]
docker-sync creates a directory for each of external volumes inside project root (http://d.pr/i/9wrwu). This affects editor indexing and so on.

Excerpt of docker-compose.yml file

        services:         
              web:
                    container_name: web
                    build:
                        context: .
                        dockerfile: .docker/docker-web.dockerfile
                    volumes:
                        - ezpublish5-sync:/var/www/ezpublish5:rw
                        - ubb-sync:/var/www/www.terrengsykkel.no:rw
                        - ffshop-sync:/var/www/www.ffshop.no:rw
                    working_dir: /var/www/ezpublish5
                    depends_on:
                        - db
                    networks:
                        - app-back
                        - app-front
        volumes:
            ezpublish5-sync:
                external: true
            ffshop-sync:
                external: true
            ubb-sync:
                external: true

docker-sync.yml

        version: "2"
        
        options:
            verbose: true
            # default: docker-compose.yml if you like, you can set a custom location (path) of your compose file like ~/app/compose.yml
            compose-file-path: 'docker-compose-mac.yml'
        
        syncs:
            #IMPORTANT: ensure this name is unique and does not match your other application container name
            ezpublish5-sync: #tip: add -sync and you keep consistent names als a convention
                src: '.'
                dest: '/var/www/ezpublish5'
                sync_excludes: ['.docker']
                watch_excludes: ['.*/.git', '.*/node_modules', '.*/bower_components', '.*/sass-cache', '.*/.sass-cache', '.*/.sass-cache', '.coffee', '.scss', '.sass', '.gitignore']
        
            ubb-sync: #tip: add -sync and you keep consistent names als a convention
                src: '../ubb'
                dest: '/var/www/www.terrengsykkel.no'
                watch_excludes: ['.*/.git', '.*/node_modules', '.*/bower_components', '.*/sass-cache', '.*/.sass-cache', '.*/.sass-cache', '.coffee', '.scss', '.sass', '.gitignore']
        
            ffshop-sync: #tip: add -sync and you keep consistent names als a convention
                src: '../ffshop'
                dest: '/var/www/www.ffshop.no'
                watch_excludes: ['.*/.git', '.*/node_modules', '.*/bower_components', '.*/sass-cache', '.*/.sass-cache', '.*/.sass-cache', '.coffee', '.scss', '.sass', '.gitignore']

**Comment by rashidul0405** [comment]
looks like `docker-sync clean` and `docker-sync-daemon start` fixes the above issue. It might be related to some update and misconfiguration.

**Comment by EugenMayer** [comment]
remove ./dest please, its no longer supported nor needed

**Comment by rashidul0405** [comment]
Thank you very much for the information. BTW this project is really awesome : )

**Comment by EugenMayer** [comment]
Thank you!
