### ISSUE TITLE
Allow for docker-sync to run in background and add a docker-sync stop command?

### ISSUE THREAD

**Issue by timstallmann** [EugenMayer/docker-sync#32]
Hi! I'm having great results with this but we use a makefile to script docker environment creation locally, and the blocking UI for docker-sync is not so compatible with that. What about adding a command-line option to `docker-sync start` to run in the background and then a separate `docker-sync stop` command to stop the process?

**Comment by EugenMayer** [comment]
Well this sounds easier then it is, i cannot cleanly reconnect to the thread and i wont start to save pids and things to do so - that is just overcomplicating things.

There is an alternative though, use docker-sync as a ruby library and use threads there, like i have done it for docker-sync-stack, see here:

You run the sync manager with run : https://github.com/EugenMayer/docker-sync/blob/master/tasks/stack/stack.thor#L37

But you do not call .join_threads after that like her https://github.com/EugenMayer/docker-sync/blob/master/tasks/sync/sync.thor#L36

You just continue doing what you want to script, in my case, i start a new blocking task - docker-compose. But you could do anything.

In your rubyr project,

```
require 'docker-sync/sync_manager'
config_path = DockerSyncConfig::project_config_path
@sync_manager = Docker_Rsync::SyncManager.new(:config_path => config_path)
@sync_manager.run()

# do something else here, if it is non blocking, call @sync_manager.join_threads on the end


```

**Comment by EugenMayer** [comment]
I rather tend to not tackle this - at least i do not know how. Feel free to implement something and pull-request it, but please think over proper thread cleanup, not just "background and leave it there".

And thanks for the kudos!

**Comment by timstallmann** [comment]
Ok cool -- thanks for the background! We're not ruby developers over here (although maybe this is a good chance to learn!), so I may just live with it for now if nobody else out there is wanting this functionality.

**Comment by EugenMayer** [comment]
@timstallmann well you do not really need to be a ruby developer for this, just see here: https://github.com/EugenMayer/docker-sync/wiki/Docker-sync-as-library

Copy past it, insert your shell scripts, done :)
