### ISSUE TITLE
Spaces in src path lead to issues with unison

### ISSUE THREAD

**Issue by lucasstark** [EugenMayer/docker-sync#322]
Getting the same error as reported here:   https://github.com/EugenMayer/docker-sync/issues/200

Profile does not exist. 

```
docker-sync start
       note:  You can also run docker-sync in the background with --daemon
          ok  Starting unison
          ok  docker-sync-unison container still running, restarting unison in container
       error  Error starting sync, exit code 0
     message  
     message  Usage: unison [options]
    or unison root1 root2 [options]
    or unison profilename [options]

For a list of options, type "unison -help".
For a tutorial on basic usage, type "unison -doc tutorial".
For other documentation, type "unison -doc topics".

Profile /Users/lucasstark/Library/Application Support/Unison//Users/lucasstark/Box.prf does not exist
     success  Unison server started
       error  Error starting sync, exit code 0
     message  
     message  Usage: unison [options]
    or unison root1 root2 [options]
    or unison profilename [options]

For a list of options, type "unison -help".
For a tutorial on basic usage, type "unison -doc tutorial".
For other documentation, type "unison -doc topics".

Profile /Users/lucasstark/Library/Application Support/Unison//Users/lucasstark/Box.prf does not exist
Usage: unison [options]
    or unison root1 root2 [options]
    or unison profilename [options]

For a list of options, type "unison -help".
For a tutorial on basic usage, type "unison -doc tutorial".
For other documentation, type "unison -doc topics".

Profile /Users/lucasstark/Library/Application Support/Unison//Users/lucasstark/Box.prf does not exist
```

**Comment by donnykurnia** [comment]
@lucasstark can you add more information:
- the content of your `docker-sync.yml`
- version of `docker-sync` (`docker-sync -v`)
- version of unison (`unison -version`)

**Comment by lucasstark** [comment]
This is all on a fresh install from yesterday, using https://github.com/wodby/docker4wordpress/blob/master/docker-compose.yml

Here's my docker-sync.yml

```
version: "2"

syncs:
  docker-sync-unison:
    src: './'
    dest: '/var/www/html'
    sync_userid: '82'
    sync_excludes: ['.gitignore', '.git/', '.idea/']
#  docker-sync-unison-another-project:
#    src: '/absolute/path/to/project/codebase'
#    dest: '/var/www/html'
#    sync_userid: '82'
#    sync_excludes: ['.gitignore', '.git/', '.idea/']
```

docker-sync -v:    0.3.5
unison -v:  unison version 2.48.4

**Comment by lucasstark** [comment]
Also notice in the path it is looking for for the profile there seems to be an empty variable, or a string concatenation which is going wrong. Seems to be a problem between /Unison and /Users.   

Profile /Users/lucasstark/Library/Application Support/Unison//Users/lucasstark/Box.prf does not exist

**Comment by EugenMayer** [comment]
Fix your unisono Installation, use brew to do so. Remove dest, its not suppoted and not needed. Ensure you unterstand thr exclude syntax of unison, since its wrong in your case. Default type is Name

**Comment by lucasstark** [comment]
Not sure I understand, unless this reference is incorrect:

https://github.com/EugenMayer/docker-sync-boilerplate/blob/master/unison/docker-sync.yml

Also "fix unison':

```
brew upgrade unison
Error: unison 2.48.4 already installed
```

**Comment by lucasstark** [comment]
Ah, you can not have a space in your host's path to the source files.  I moved my project to /Users/lucasstark/Projects/docker.rivier.edu and now things work fine.

**Comment by EugenMayer** [comment]
That is odd, lets see if we can fix this actually.

Still remove dest and think about the excludes - thanks for the hint in the boilerplate, ill fix that.

**Comment by EugenMayer** [comment]
Fixed, thank you for reporting
