### ISSUE TITLE
native_osx does not work with docker-machine vbox / fusion

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-sync#346]
I seems like vboxfs does not trigger fsevents on the receiving end, making it a bad companion for the unison watcher, since no inotify events are triggered.

I do not think we can do anything about this.

docker-machine + fusion does work though

**Comment by EugenMayer** [comment]
Fo anybody with fusion, you can use fusion, just do

docker-machine create --driver vmwarefusion --vmwarefusion-cpu-count=2 --vmwarefusion-disk-size=50000 --vmwarefusion-memory-size=8000 default

you might want to use a different name then default if you want to keep the vbox machine - using default usually simplifies cli things though

**Comment by EugenMayer** [comment]
added this to https://github.com/EugenMayer/docker-sync/wiki/8.-Strategies

**Comment by EugenMayer** [comment]
Seems to be in fact a deal breaker - https://groups.google.com/forum/#!topic/vagrant-up/ZZpM1nTCSSQ both, vmware fusion and virtualbox do not implement file system events

**Comment by mike-potter** [comment]
Yeah, I think something else is wrong.  I also just tried it with docker-machine + xhyve and it also didn't work.

**Comment by greggilbert** [comment]
Just jumping in. Docker 4 Mac, OSX 10.12.4. Tried 0.4.1 with `native_osx`, and while all the containers came up and unison was running in the sync containers, it wasn't actually syncing.

**Comment by EugenMayer** [comment]
@mike-potter it does work with docker for mac, since they use osxfs - which xhyve on docker machine does not use.

That said, i corrected the strategie guide to reflect the docker-machine issue

**Comment by EugenMayer** [comment]
Thats known for a very long time already, not sure how i missed that: https://groups.google.com/forum/#!topic/vagrant-up/ZZpM1nTCSSQ

**Comment by infostreams** [comment]
You can work around this issue and get the `native_osx` strategy working by making a change to the `options` in your `docker-stack.yaml`, like this:

```yaml
version: "2"
options:
  native_osx_image: 'infostreams/docker-sync-unison'

syncs:
  code_sync:
    sync_strategy: 'native_osx'
    src: '/my/path/to/my/code'
    sync_excludes: ['node_modules', 'vendor']
    sync_args: "-copyonconflict"
```

If you add the `native_osx_image` key as described above, it will run a background program inside the docker-sync container to trigger the missing filesystem events. More info [here](https://hub.docker.com/r/infostreams/docker-sync-unison)
