### ISSUE TITLE
[idea] Migrate docs to https://readthedocs.org/

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-sync#355]
The wiki becomes pretty painful already, including missing features like proper toc, deep links, stable links but also a proper navigation.

I would like to migrate them into https://readthedocs.org/

Does anybody want to help with this task - this would be great!

I want to change the structure a bit - we have 2 main topics:

a) Beginners / Starters / Common Case
b) Advanced

Into a) i want only deal with describing things you do on top of the default sync strategies. So no special selection of those here, not read advanced things like sync_args and so on. 
Just how to get on board, what you need to look at ( like sync_userid ), ho to create your compose files, how to name things.

b) describe all strategies, for each, the available configurations. Describe the global configuration, scaffolding, development/contribution, matter of autoupgrades and so on

**Comment by EugenMayer** [comment]
signed up the project https://readthedocs.org/projects/docker-sync/

**Comment by unnawut** [comment]
Could this start primarily as a reshuffle of Wiki content into your mentioned groupings?

If so I'd like to tackle this.

**Comment by EugenMayer** [comment]
This would be _awesome_, i would so much love to see that happen - and yes, moving the content as is makes the most sense right.

I created a project already, do i need to forward you any permissions? Let me know.

You made my day!

**Comment by EugenMayer** [comment]
We need to ensure 

- that all links we have right now are directed into the new docs, at least from the wiki. 
  - http://docker-sync.io has some links
  - README.md
  - ?

- We need to ensure that the wiki gets removed ASAP so we do not end up to update / read the wrong docs in the end
- do we have any other external links ?

**Comment by EugenMayer** [comment]
So i updated the entrypoint of the wiki and backed it up to https://github.com/EugenMayer/docker-sync/wiki/Backup-home if we are going to use it. I also updated all the links on http://docker-sync.io and also in the repo readme

**Comment by EugenMayer** [comment]
I know checked out https://github.com/EugenMayer/docker-sync.wiki.git and created a branch backup and moved all docs there, flushed the master. So the wiki is empty now

**Comment by EugenMayer** [comment]
Actually i reverted removing all the wiki docs (kept the backup) and rather replaced the content of each site with the link to the new docs so we keep all the external links functional.

I think that is it, thank you so much @unnawut for helping out and putting so much time into it!

See https://github.com/EugenMayer/docker-sync/releases/tag/0.5.11 - i release 0.5.11 today including the docs. So this is live

**Comment by unnawut** [comment]
Keeping the wiki pages was a good idea! Thanks!

If you have any further tasks/ideas to do with the docs, feel free put them up. I'll grab them when I have some down time. ;)
