### ISSUE TITLE
Changing src or dest in configuration do not apply

### ISSUE THREAD

**Issue by gagarine** [EugenMayer/docker-sync#36]
I'm using unison don't know if it apply with rsync.

If you launch the docker-sync and then after change the configuration and relaunch it, the sync folders are still going to be at the same place.

**Comment by EugenMayer** [comment]
you need to clean the sync first

```
docker-sync clean
or
docker-sync-stack  clean
```

then you can change the source or change the sync strategy.

**Comment by gagarine** [comment]
Oh I see now. The volume was still in use by my containers.

```
➜  Docker docker-sync clean
Error response from daemon: Unable to remove volume, volume still in use: remove code-sync: volume is in use - [c220ee512b85db43e81d656bfd408529c584b3397512153f42ae47e8b846d352, 0d9cc5b9f761cc7a25eb3a3823160f12e46cbe4702ed69194c80d5006175997b]
     success  Finished cleanup. Removed stopped, removed sync container and removed there volumes
```

I just read the green "sucess" the first time I tried. 

I'm force to delete my container? I wish I can stop my container, cleanup, change the config and start again my container.

**Comment by EugenMayer** [comment]
please explain, what your "container" is, the container rsync runs on, we call them sync-container ,or the app container

**Comment by gagarine** [comment]
I want to keep the app container (In my case their is 3 containers for my app).

**Comment by EugenMayer** [comment]
No you cannot do this, docker does not allow this.

You do not need, of course, to delete the app containers when you stopped ur synced and started again - the volumes / containers will be reused. But when you swap the sync strategy,  you have to do this.

**Comment by gagarine** [comment]
ok, thanks for your help!

**Comment by EugenMayer** [comment]
your welcome :)
