### ISSUE TITLE
Docker(moby?) for Windows (d4w) Support/Driver

### ISSUE THREAD

**Issue by rwilliams** [EugenMayer/docker-sync#368]
### Docker for Windows support 
Not only will it significantly speed up code execution but it should allow inotify to properly function on the Docker (mobi) host containers as this is currently not supported with the volume shares used in d4w. 

### Prerequisites(?)
Cygwin
Unison
Inotify-Win(?)

### Initial Thoughts
This may work with Cygwin and Unison already but it has not been fully documented yet. 

Inotify-Win might allow for a "Windows Native" driver providing a more familiar file watcher API than common windows file watching strategies.

**Comment by EugenMayer** [comment]
There are people using docker sync under cygwin. Since 0.3.4 we have a better Linux support, so it should work out even better.

Actively working on Windows support is nothing I will do. So if nobody volunteers here, I would close this ticket

**Comment by rwilliams** [comment]
I've made a bit of progress with Cygwin and Unison so far. It looks like https://github.com/EugenMayer/docker-sync/commit/fe0126b4935995967b4fa79844a9cc6662add462 broke the initial working state on windows as `OS.linux?` is false on Cygwin. `OS.posix?` is true on Cygwin and Cygwin plays decently with the linux preconditions so far.

**Comment by EugenMayer** [comment]
I guess then we need to add a precondition strategy for cygwin?

**Comment by rwilliams** [comment]
The current linux strategy may work verbatim. Once i get the watcher working i'll share a PR for you to look at.

**Comment by rwilliams** [comment]
Yeah. Once I get the file watcher working i'll share PR and document what I did to get it up and running.

**Comment by rwilliams** [comment]
The file watcher is working now. I'm running into an issue when compose tries to start.

>           ok  starting compose
> EXCEPTION: #<RuntimeError: can't get Master/Slave device>
> MESSAGE: can't get Master/Slave device

**Comment by codycraven** [comment]
@rwilliams why Cygwin? If you're running D4W you're on Windows 10 Pro, wouldn't it make better sense to use the Microsoft supported/served Windows Subsystem for Linux?

**Comment by rwilliams** [comment]
@codycraven For WSL I'm really curious how the interactions between filesystems is going to work if you are running docker-sync on Ubuntu and editing files in editor running on windows. I'll play with it if i get some time. Cygwin + Unison is working already it just needs some minor tweaks.

**Comment by codycraven** [comment]
@rwilliams I haven't needed docker-sync yet on my Windows machine (I don't have any high file host mounts... yet).

However I can share my setup:
- In my windows user directory I have a folder "Projects" to house all of my code.
- In Ubuntu I've symlinked $HOME/Projects to /mnt/c/Users/codyc/Projects
- Docker4Windows is running in the host
- In my ~/.bashrc I have `export DOCKER_HOST=tcp://127.0.0.1:2375`

**Comment by rwilliams** [comment]
@codycraven The reason windows support interests me is the possibility of inotify working properly on the host containers. When they are shared with windows it breaks inotify so live reloading has to be done by polling.

**Comment by rwilliams** [comment]
WSL is looking super promising. I got docker sync up and running much faster and cleaner then with Cygwin. I'll do a write up after I do a bit more testing.

**Comment by ignatiusreza** [comment]
I wonder how the native mount performance are on both cygwin and WSL.. if either of them can use native volume strategy similar to the default one we us on linux, or if we need to do something like native_osx strategy..

Regarding `os`, it seems like there's a `OS.cygwin?` method which we can use to detect if we're running under cygwin environment.. but, i'm not so sure of how we can detect WSL?

**Comment by rwilliams** [comment]
@ignatiusreza Yep, `OS.cygwin` is what I was using. WSL behaves nearly identical to linux and docker-sync probably doesn't have to differentiate between the two.  With cygwin you're stilling using widows binaries (maybe the pure python version of docker-compose) so i don't believe native volume mounting is going to be a thing. With WSL you can/should use linux docker client and docker-compose but most use cases would have their projects data on the Windows filesystem which again probably means no native mount.

**Comment by rwilliams** [comment]
Docs and benchmarks coming soon for WSL.

**Comment by rwilliams** [comment]
Here's detailed instructions on getting docker-sync running on WSL

This assumes you have a working docker setup already on your Windows machine. d4w, Virtualbox, etc.
Windows 10 Pro 1703 (creators update) is recommended
Docker for Windows 17.03.1-ce-win10 (11972) stable

#### 1. Enable Windows subsytem for linux
	Windows Control Panel - Turn Windows Features on of Off
	Check Windows Subsystem for Linux (beta) near the bottom
#### 2. Make sure developer mode is enabled
	Settings -> For Developers -> Make developer mode is selected	
#### 3. Install Bash for Windows
	Open command prompt and type 'lxrun /install'
#### 4. Launch and update Ubuntu
	Bash on Ubuntu Windows is now an 'app' on your system. Launch it
	Update the OS - `sudo apt-get update
                     sudo apt-get upgrade`	
#### 5. Install Docker
	https://docs.docker.com/engine/installlation/linux/ubuntu/
	Note the docker server doesn't work on WSL so we're esentially just using client
#### 6. Install Docker Compose
	https://docs.docker.com/compose/install/
#### 7. Install Ruby and Ruby-dev
	sudo apt-get install ruby ruby-dev
#### 8. Install docker-sync
	sudo gem install docker-sync
#### 9. Set your docker host as an ENV variable	
	Add 'export DOCKER_HOST=tcp://127.0.0.1:2375' or whatever your docker host is to your .bashrc
	*note on docker for windows setting I had to check 'Expose daemon on tcp://localhost:2375 without TLS' 
#### 10. Install Unison
	sudo apt-get install ocaml
	sudo apt-get install make
	wget https://github.com/bcpierce00/unison/archive/2.48.4.tar.gz
	tar xvf 2.48.4.tar.gz
	cd unison-2.48.4
	make UISTYLE=text
	sudo cp src/unison /usr/local/bin/unison
	sudo cp src/unison-fsmonitor /usr/local/bin/unison-fsmonitor
#### 11. Profit?
	docker-sync should now work with the unison strategy.
#### 12. Sample docker-syc.yml
```
	version: "2"
	options:
	  verbose: true
	syncs:
	  app-unison-sync: # tip: add -sync and you keep consistent names als a convention
	    sync_args: ['-perms=0'] #required for two way sync
	    sync_strategy: 'unison' 
	    sync_host_ip: '127.0.0.1' #host ip isn't properly inferred
	    sync_excludes: ['.gitignore', '.idea/*','.git/*', '*.coffee', '*.scss', '*.sass','*.log']
	    src: './'
```

**Comment by EugenMayer** [comment]
@rwilliams please put that into the wiki - so much effort, make it worth it!

Thank you very much!

**Comment by rwilliams** [comment]
I'm going close this and we can add more info to the wiki as needed.

**Comment by rwilliams** [comment]
@ignatiusreza If there was ever a need for WSL specific code `uname -r` is "Microsoft"
