### ISSUE TITLE
invalid mode: no-copy

### ISSUE THREAD

**Issue by dennisschneider** [EugenMayer/docker-sync#371]
### Error/Feature Requestion/Docs
?

Just followed your upgrade guide from 0.4.0 to 0.4.2, added the no-copy flag to each volume and get this error: 

ERROR: for CONTAINER_NAME Cannot create container for service SERVICE_NAME: invalid bind mount spec "applications-sync:/srv/path:no-copy": invalid mode: no-copy

When I try unison instead, I get the following error: 

Error getting mapped port, exit code 0

I ran docker-sync clean in advance.

### Docker Driver
? (d4m or docker-machine+vbox/fusion)

d4m

### Sync strategy
? (default/native_osx/unison/rsync)

native_osx

### OS
? (OSX Version/Linux)

OSX 10.12.4

**Comment by dennisschneider** [comment]
after running docker-sync a second time and having changed the syncing strategy back to unison all containers were created as expected, so pls consider the unison port issue being resolved.

**Comment by EugenMayer** [comment]
Its not no-copy ,it nocopy https://github.com/EugenMayer/docker-sync-boilerplate/blob/master/default_with_user/docker-compose-dev.yml#L8

**Comment by dennisschneider** [comment]
thx, sorry 😄
