### ISSUE TITLE
symlinks using osx_native strategy copying the symlink instead of the linked files/folder

### ISSUE THREAD

**Issue by kritop** [EugenMayer/docker-sync#378]
Is there a way to change that behaviour?
also does it watch files linked via symlink?

**Comment by EugenMayer** [comment]
a) probably, see http://www.cis.upenn.edu/~bcpierce/unison/download/releases/stable/unison-manual.html#symlinks but since you "mount" src, if the symlink does not point to anything inside src, it obviously wont work

b) no
