### ISSUE TITLE
Feature: A bit more Docker Compose Abstraction

### ISSUE THREAD

**Issue by rwilliams** [EugenMayer/docker-sync#380]
I would be nice for docker-sync-stack to allow more that just the 'start' command. Users are encouraged to use a bit more complex docker-compose setup than normal it would be nice to add at least a run method for docker-sync-stack (or docker-sync). This is especially useful when folks are using generators with `docker compose run`  and they forget to include the dev.yml. 

### Example
Assume docker-sync is already running

#### Doing it wrong
`$ docker-compose run web rails g migration test_stuff`
This migration file will get orphaned in a one off container

#### The right way
`$ docker-compose -f docker-compose.yml -f docker-compose-dev.yml run web rails g migration test_stuff`
Acts as expected

### Proposal
Add someting like 'docker-sync-stack run'  as it already contains all the logic for the extra compose config.

This is probably overkill as you can easily just create bash aliases to handle this but it shouldn't be much work and it's should be pretty handy. 

Extra points
We could also check to see if docker-sync is currently running and start if it not and then run the docker run command.

**Comment by EugenMayer** [comment]
I suppose some would rather use docker-sync start + docker-compose up if such an interface is needed, what do you think?

**Comment by rwilliams** [comment]
Yeah. Honestly less abstraction might be the way to go. The you never have to worry about breaking compose changes etc.

**Comment by EugenMayer** [comment]
i actually really think about removing the docker-compose gem and doing shell calls on docker-compose only - so people can rely on what they know / use

**Comment by rwilliams** [comment]
Along those lines I don't think it's necessary to recommend that folks split their docker-compose.yml into two files. I think that should documented if their use case includes using the docker-compose.yml in production but i don't think it should be the default best practice. Most people understand that their docker-compose.yml is only for development anyway. Production configurations 'should' have more detailed service definitions for docker-swarm instead of docker-compose or a docker-compose-production.yml file. Thoughts?

**Comment by ignatiusreza** [comment]
There's also another use case for CI.. on which docker-sync is not required..

**Comment by rwilliams** [comment]
CI should be using images anyway right?

**Comment by ignatiusreza** [comment]
not necessarily, since you can also use CI to build new images.. and for application code, you still potentially need docker-compose to setup all the networking.. see also https://circleci.com/docs/2.0/docker-compose/

**Comment by rwilliams** [comment]
Gotcha. Given that docker-compose can take arbitrary compose files and people can chose how they want to setup each of their environments I retract my previous sugestion (single compose file). I still support doing away with docker-sync-stack.

**Comment by rwilliams** [comment]
Should we close this one and open a new feature removal request for docker-sync-stack to drive more user feedback on that subject?

**Comment by EugenMayer** [comment]
i am not aiming to remove -stack, rather aiming to remove the docker-compose gem, which adds abstraction which adds incompatibility.

I want -stack to be just a docker-compose up runner for convenience, not much more though.

Closing this one, opening the other when time has come, for now, things are cooking with native_osx, i do not think we have bandwidth left :)

**Comment by rwilliams** [comment]
> i am not aiming to remove -stack, rather aiming to remove the docker-compose gem, which adds abstraction which adds incompatibility.

Gotcha

**Comment by donnykurnia** [comment]
@rwilliams put this line in `.env` file:
`COMPOSE_FILE=docker-compose.yml:docker-compose-dev.yml`
then you can just do:
`docker-compose run ...` or other command. No need for using `-f docker-compose.yml -f docker-compose-dev.yml` in your command, and no need for docker-sync to create new command just to wrap `docker-sync` functionality.
References:
https://docs.docker.com/compose/environment-variables/#the-env-file
https://docs.docker.com/compose/reference/envvars/

**Comment by rwilliams** [comment]
@donnykurnia Thanks. That's perfect.
