### ISSUE TITLE
The sync container crash after docker-sync-stack start

### ISSUE THREAD

**Issue by beshkenadze** [EugenMayer/docker-sync#382]
### Error
**In console:** ```Sync Log:  rpc error: code = 2 desc = oci runtime error: exec failed: cannot exec a container that has run and stopped```
**In container (*-sync)**: 
![image](https://cloud.githubusercontent.com/assets/167288/25912136/ecf984d0-35be-11e7-93ad-800361a8fcfe.png)

### Docker Sync Version
```docker-sync-stack --version > 0.4.4.beta1```
```docker-sync --version > 0.4.4.beta1```
### Docker Driver
d4m

### Sync strategy
native_osx

### your docker-sync.yml
```version: "2"

options:
  verbose: true
syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  ${PROJECT_NAME}-sync: # tip: add -sync and you keep consistent names also a convention
    src: '${APP_PATH}'
    sync_excludes: ['']
```
### OS
OSX 10.12.4

**Comment by EugenMayer** [comment]
upgrade to 0.4.0 and enable auto upgrade - or do not create issues

**Comment by beshkenadze** [comment]
Do I need to downgrade?
[Here](https://github.com/EugenMayer/docker-sync/issues/374#issuecomment-300553113) you told to upgrade to beta-1.

**Comment by EugenMayer** [comment]
You mean in the closed issue, 2 days ago? :)

Please upgrade to the current stable. Do you have upgrades disabled?

**Comment by EugenMayer** [comment]
after you properly upgraded, this issue will not exist there is no such line even left anymore https://github.com/EugenMayer/docker-image-unison/blob/feature/unison-hostsync/entrypoint.sh#L75

**Comment by beshkenadze** [comment]
auot-updated to version 0.4.4 and sync is not working as in version #374 .

**Comment by EugenMayer** [comment]
please open a new issue, since thats for sure not this one, paste your docker-sync.yml and you ~/.docker-sync-global.yml

also paste your synccontainer:/tmp/unison.log and the docker logs of the sync container
