### ISSUE TITLE
Formalize Windows support

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-sync#387]
- how to setup https://github.com/EugenMayer/docker-sync/wiki/docker-sync-on-Windows
- benefit / performance? put it here https://github.com/EugenMayer/docker-sync/wiki/4.-Performance
- clues / what does not work ( strategy guide )
- does daemon mode work? 
- does -stack work?

**Comment by EugenMayer** [comment]
i updated the sync guide https://github.com/EugenMayer/docker-sync/wiki/8.-Strategies and the installation guide https://github.com/EugenMayer/docker-sync/wiki/8.-Strategies and the home https://github.com/EugenMayer/docker-sync/wiki to fit the splitting

**Comment by rwilliams** [comment]
Thanks @EugenMayer 
The more i'm reading about unison it looks like we dont even need WSL or Cygwin. I think when i first started researching this I was looking at a file watcher that required a posix OS so I made this way more complicated than it needs to be. I'll probably dig in to this over the weekend.

**Comment by EugenMayer** [comment]
closing this for now, looks good for the time being, think we will improve this when moving over to readthedocs

**Comment by rwilliams** [comment]
I didn't want to go crazy documenting either WSL or Cygwin if getting docker-sync working on Windows without a posix environment isn't going to be a huge deal. The requirements for WSL are very specific and in a lot of corporate environments folks aren't going to be able to upgrade their Windows build until IT rolls it out.

**Comment by EugenMayer** [comment]
Well if a company forces its developers to follow DAU-specific enterprise policies to have them securely boxed in a "safe environment" like the rest of the users in the company - i am very happy to ignore those needs until the developers finally step up and explain why this is horrible practice.

So do not worry about those cases, the last thing we will focus here is support stupid enterprise setups which do not differ between there user roles and demands.
