### ISSUE TITLE
Files not synchronizing after initial copy (native_osx sync strategy)

### ISSUE THREAD

**Issue by mpriscella** [EugenMayer/docker-sync#395]
### Error/Feature Requestion/Docs
After initial copy, I don't see changes made on my host machine reflected in the docker machine.

### Docker Driver
Docker for Mac Version 17.03.1-ce-mac12 (17661)
Docker-Sync version is 0.4.5

### Sync strategy
native_osx

### your docker-sync.yml
docker-sync.yml
```
version: "2"

options:
  verbose: true
syncs:
  cms-sync:
    notify_terminal: false
    src: "./cms/CMS"
```
docker-compose.dev.yml
```
version: "2"

services:
  cms:
    volumes:
      - cms-sync:/var/www/html/production:nocopy

volumes:
  cms-sync:
    external: true
```

### OS
OSX 10.12.4 (16E195)

**Comment by EugenMayer** [comment]
please upgrade to 0.4.6

**Comment by mpriscella** [comment]
Updated to version 0.4.6, stopped all of my running containers, ran `docker system prune`, ran `docker-sync clean`, and then restarted my containers - unfortunately my issue hasn't been resolved.

**Comment by EugenMayer** [comment]
i at least cannot reproduce it, i need your docker-sync.yml and your log  please, thank you!

include the docker logs of the sync container or use ```docker-sync start --foreground```

**Comment by EugenMayer** [comment]
tested with https://github.com/EugenMayer/docker-sync-boilerplate/tree/master/default and it does work without any issues, very similar docker-sync.yml as here

**Comment by pagameba** [comment]
had a similar issue, turned out I had switched to RVM but not properly cleaned up - once I got ruby working properly with RVM and cleaned the sync volumes, it started working nicely.

**Comment by EugenMayer** [comment]
I am currently not sure i really want to mess with peoples RVM setup and issues. 

I understand the need of it, we are using rbenv, but RVM seems to create a lot of issues, which chruby and rbenv seem to actually not - and no matter which multi-ruby toolkit you are using, you should probably know the way to deal with.

We had a RVM related fix in 0.4.4 already, if that becomes a regular case, we have to discuss if that becomes rather a topic of "RVM not supported, please use system ruby", or we get some contributor who dedicates time to support RVM in docker-sync long term ( which a i suppose wont happen )

**Comment by pagameba** [comment]
heh - I'm not a ruby person but I ran into problems with the system ruby not being new enough for something and just threw on RVM.  After researching more today, seems like I should have gone with rbenv but I'm not familiar enough with the ruby eco-system to know which is better or how to switch.  In any case, it works fine with RVM now that I have it set up correctly and don't have old versions of docker-sync hanging around in unexpected places :)

**Comment by mpriscella** [comment]
Okay so I went ahead and removed all old versions of docker-sync and I'm getting it to work, I am however experiencing a long lag at initial sync. When I say "initial sync" I don't mean all of the files being copied over to the sync container, I expect that to take a little longer as noted in your documentation. I mean after docker-sync has returned a success message and said it's okay to begin editing. After receiving that message, when I make a change on my host machine it's taking ~2 minutes to sync to the sync container. After that first change things seem to be fairly quick. Here's a subset of my docker-sync logs:

```
       note:  Starting in foreground mode
          ok  Starting native_osx for sync cms-sync
          ok  cms-sync container not running
          ok  creating cms-sync container
          ok  Starting precopy
Contacting server...
Looking for changes
Reconciling changes
Nothing to do: replicas have been changed only in identical ways since last sync.
real    1m 48.44s
user    0m 3.84s
sys     0m 7.41s
          ok  Starting container
     command  docker run -d -v cms-sync:/app_sync -v /Users/mikepriscella/workspace/{company}/platform-cms-docker
/cms/CMS:/host_sync -e HOST_VOLUME=/host_sync -e APP_VOLUME=/app_sync -e TZ=${TZ-`readlink /etc/localtime | sed -e 's,
/usr/share/zoneinfo/,,'`} -e UNISON_EXCLUDES="-ignore='Name .idea'" -e UNISON_ARGS="" -e UNISON_SYNC_PREFER="-prefer /
host_sync"  --name cms-sync eugenmayer/unison:hostsync_0.2
          ok  starting initial sync of cms-sync
     success  Sync container started
     success  Showing unison logs from your sync container: cms-sync
   Sync Log:  UNISON 2.48.4 started propagating changes at 10:44:38.61 on 16 May 2017
   Sync Log:  [BGN] Updating file web/profiles/{company}/config/sync/core.extension.yml from /host_sync to /app_sync
   Sync Log:  [END] Updating file web/profiles/{company}/config/sync/core.extension.yml
   Sync Log:  UNISON 2.48.4 finished propagating changes at 10:44:38.62 on 16 May 2017
   Sync Log:  Synchronization complete at 10:44:38  (1 item transferred, 0 skipped, 0 failed)
   Sync Log:  UNISON 2.48.4 started propagating changes at 10:44:46.88 on 16 May 2017
   Sync Log:  [BGN] Copying web/profiles/{company}/config/sync/.core.extension.yml.swp from /app_sync to /host_sync
   Sync Log:  [END] Copying web/profiles/{company}/config/sync/.core.extension.yml.swp
   Sync Log:  UNISON 2.48.4 finished propagating changes at 10:44:46.89 on 16 May 2017
   Sync Log:  Synchronization complete at 10:44:46  (1 item transferred, 0 skipped, 0 failed)
   Sync Log:  UNISON 2.48.4 started propagating changes at 10:44:49.10 on 16 May 2017
   Sync Log:  [BGN] Deleting web/profiles/{company}/config/sync/.core.extension.yml.swp from /host_sync
   Sync Log:  [END] Deleting web/profiles/{company}/config/sync/.core.extension.yml.swp
   Sync Log:  UNISON 2.48.4 finished propagating changes at 10:44:49.11 on 16 May 2017
   Sync Log:  Synchronization complete at 10:44:49  (1 item transferred, 0 skipped, 0 failed)
   Sync Log:  UNISON 2.48.4 started propagating changes at 10:45:03.72 on 16 May 2017
   Sync Log:  [BGN] Updating file web/profiles/{company}/config/sync/core.extension.yml from /host_sync to /app_sync
   Sync Log:  [END] Updating file web/profiles/{company}/config/sync/core.extension.yml
```

**Comment by EugenMayer** [comment]
@mpriscella so the lag issue is something else then, feel free top open a different issue for that.

Please ensure to include the file count you are syncing and your hardware specs. Generally speaking, 2 minutes is horrible long, never seen that.

**Comment by mpriscella** [comment]
@EugenMayer sounds good! I'll test on a couple different machines first to see if it's something unique to my machine.

Thanks!

**Comment by websharp** [comment]
Hi guys,

I have the same issue but I do not understand the discussed solution with ruby or RVM.
I started using docker-sync with v0.4.5 and installed it with _gem_, have upgraded to v0.4.6 today. 

I run _docker-sync start_ first and then start up my containers. 

The start command gives me the following output:
```
          ok  Starting native_osx for sync myproject-appdata-sync
          ok  myproject-appdata-sync container not running
          ok  starting myproject-appdata-sync container
     command  docker start myproject-appdata-sync && docker exec myproject-sync supervisorctl restart unison
          ok  starting initial sync of myproject-appdata-sync
     success  Sync container started
     success  Starting Docker-Sync in the background
```

I cannot run the _logs_ command:
```
       error  docker-sync is not running in daemon mode for this configuration
```

my configuration of _docker_sync_ looks like this:
```
version: "2"

options:
  compose-file-path: 'docker-compose.yml'
  compose-dev-file-path: 'docker-compose-osx.yml'
  verbose: true
  max-attempt: 30
syncs:
  myproject-appdata-sync:
    notify_terminal: true
    src: '.'
    sync_excludes: ['puppet', '.tmp', '.vagrant', 'backup', '.git', '.idea', '.DS_Store']
    sync_userid: 0
    sync_strategy: 'native_osx'
```

After _docker-sync start_ I start up my containers with _docker-compose start_,
initially created them with _docker-compose -f docker-compose.yml -f docker-compose-osx.yml up -d --build_

Any idea, why the sync does not apply further besides on startup?

**Comment by EugenMayer** [comment]
remove sync_userid: 0 and sync_strategy: 'native_osx

**Comment by iverberk** [comment]
I think this is somehow related to running the edge version of docker for mac. I was experiencing the same issues (only initial sync) and reverting to the stable channel fixed it for me. Not sure what the exact issue is with the edge version.

**Comment by websharp** [comment]
Hi,
I changed the configuration like @EugenMayer suggested, but I am not clear why, docker-sync did not use unison correctly as default, so I adapted the configuration a little bit.

For me working is to clean the docker-sync container at startup and start kind of new, which does not take long with unison strategy.

So my configuration looks like this:
```
version: "2"

options:
  compose-file-path: 'docker-compose.yml'
  compose-dev-file-path: 'docker-compose-osx.yml'
  verbose: true
  max-attempt: 30
syncs:
  myproject-appdata-sync:
    notify_terminal: true
    src: './'
    sync_strategy: 'unison'

    sync_excludes: [
      '.docker',
      '.docker-sync',
      '.vagrant',
      '.git',
      '.idea',
      '.DS_Store',
      'docker',
      'puppet',
      'sessions'
      ]

    watch_excludes: [
      '.gitignore',
      '.docker',
      '.docker-sync',
      '.vagrant',
      '.idea',
      '.DS_Store',
      'backup',
      'docker',
      'node_modules',
      'sessions'
    ]

    watch_args: '-v'
```

And I am running the following commands on startup:
```
docker-compose down
docker-sync clean -c docker-sync.yml
docker-sync start -c docker-sync.yml
docker-compose -f docker-compose.yml -f docker-compose-osx.yml up -d
```

**Comment by EugenMayer** [comment]
@websharp did you read the upgrade notes and the cli questions? with 0.4.x the default nowdays is native_osx, not unison.

I am not sure why you pick unison before native_osx - yet the only reason to do so should be you are not using docker-for-mac but rather docker-toolbox.

If you you do use d4m, you should really consider use native_osx
