### ISSUE TITLE
Start stucking if docker pull asking for login

### ISSUE THREAD

**Issue by pn-y** [EugenMayer/docker-sync#398]
### Error/Feature Requestion/Docs
`docker-sync start` stuck if `docker pull` asking for credentials from docker hub

### Docker Driver
d4m

I had a problem with one of macs, where docker-sync always stucked at start. I've investigated and found what it waiting results from docker pull, but it waits input from user. So in this case `docker-sync start` will never finish.

**Comment by EugenMayer** [comment]
well even though i understand that this is inconvinient this is nothing we will be able to handle.

People have to ensure that they do not run into a hub. rate limit or whatever, requiring a login ( which is normally not the case )
