### ISSUE TITLE
gem install docker-sync error

### ISSUE THREAD

**Issue by J-Fricke** [EugenMayer/docker-sync#399]
We keep getting this error when trying to install:
```
ERROR:  Error installing docker-sync:
        backticks requires Ruby version ~> 2.0.
```
We are using RVM to manage ruby versions and it's set to 2.0.0

We have been following the instructions to install on windows using the linux sub system.
https://github.com/EugenMayer/docker-sync/wiki/docker-sync-on-Windows

* This URL for step 5 has one to many l in installation: `https://docs.docker.com/engine/installlation/linux/ubuntu/`

Also on the installation page, it mentions docker server not working on WSL which is how windows is able to install this bit, so I'm a bit confused how to proceed as we also are not able to run docker-compose from within the WSL bash line since docker daemon will not start per this thread:
`https://github.com/Microsoft/BashOnWindows/issues/85`

And if I run docker-compose from cmd, I'm missing my since volume since I'm not loading using docker-sync which is not available in cmd.

Maybe I'm missing something here?

**Comment by rwilliams** [comment]
@J-Fricke The docker engine will be running on Windows via docker-for-windows. It will not be running under WSL. You're essentially only installing the docker client under WSL as the docker daemon won't run anyway. Is there a reason you're using such an old Ruby? Can you test a later version and see what happens?

**Comment by rwilliams** [comment]
@J-Fricke What build of Windows are you running? (this may not work without the creators update) I was able to install docker-sync with ruby-2.0.0 under RVM without issue.

**Comment by EugenMayer** [comment]
@rwilliams if you like, the clarification about where the docker-engine runs and what WSL is used for could be interesting to have in the docs.. guess that will be a question again and again. You decide, you have the overview here. I am just reading closely :)

**Comment by J-Fricke** [comment]
@rwilliams  Windows 10 build 1607 - Upgrading to the creators update now to test.

As to why the older versions of Ruby, initially when running `sudo apt-get install ruby ruby-dev` in the WSL bash terminal it installed a 1.9.x version and when the error was seen about needing 2.0 or greater, initially attempt was to install ruby2.0 from apt-get and then tried RVM setting 2.0.0 as the default.

**Comment by rwilliams** [comment]
@EugenMayer Good point. I'll add a FAQ at the top of the instructions.

**Comment by J-Fricke** [comment]
@rwilliams So even after updating Windows to the creator update the issue we are seeing is that when running `sudo apt-get install ruby ruby-dev` it's attempting to install ruby1.9.1 and even when we remove that and install ruby2.0 which is in apt-get along with the 1.9.1 version (default) it still gives the Ruby 2.0.0 min required for backticks error.

Do you have any other repositories connected by chance to apt-get? I'm curious which version of ruby `sudo apt-get install ruby ruby-dev` is installing for you?

We also tried removing ruby via apt-get and only using rvm to use ruby2.4.0, but then we were missing gem.

**Comment by rwilliams** [comment]
@J-Fricke Did you upgrade your distro in WSL after the update? You may have to [blow it away](`lxrun /uninstall` in cmd or powershell) and restart because it has the old OS from the anniversary update. When I installed ruby I got `2.3.1p112 (2016-04-26) [x86_64-linux-gnu]`.

**Comment by rwilliams** [comment]
Closing this one. Adding Creators update as a requirement and will add a FAQ of needing to re-install WSL to get the latest Ubuntu distro.

**Comment by J-Fricke** [comment]
@rwilliams Yes, that definitely fixes it. Just finished with the newer version of Ubuntu on WSL and it's indeed ruby2.3.x

**Comment by rwilliams** [comment]
@J-Fricke Awesome!

**Comment by EugenMayer** [comment]
Great teamwork here! thank you for adjusting the docs @J-Fricke and nice finding @rwilliams !
