### ISSUE TITLE
Windows: Sync volume not mounting to container (windows bash issue)

### ISSUE THREAD

**Issue by J-Fricke** [EugenMayer/docker-sync#402]
Keep getting this error when starting docker-sync-stack
### Error
```
ERROR: for web  Cannot start service web: error while mounting volume 
'/var/lib/docker/volumes/web-sync/_data': 
error while mounting volume with options: 
type='none' device='/home/User/Documents/dev/' o='bind': no such file or directory
Encountered errors while bringing up the project.
EXCEPTION: #<Docker::Compose::Error: 'up' failed with status 'pid 68 exit 1': Starting web>
MESSAGE: 'up' failed with status 'pid 68 exit 1': Starting web
```
Nothing exists here on this path `/var/lib/docker/volumes/web-sync/_data`
### Sync strategy
default

### docker-sync.yml
```
version: "2"
options:
  verbose: true
syncs:
  web-sync:
    src: '~/Documents/dev/'
    sync_host_port: 10871
    sync_excludes: ['.git', 'node_modules', '.idea', '.DS_Store']
    watch_excludes: ['current', 'logs', 'sphinx/var', 'xdebug']
    watch_args: '-v'
```
### docker-compose.yml - relevant parts
```
  web:
    container_name: web
    image: web:latest
    build:
       context: ./
    networks:
      - net
    volumes:
      - web-sync:/web:nocopy
    ports:
      - "80:80"
      - "443:443"
volumes:
  web-sync:
    external: true
```

### OS
Windows WSL - Linux

**Comment by donnykurnia** [comment]
@J-Fricke try replace this line:
`src: '~/Documents/dev/'`

with absolute path
`src: '~/Users/......../Documents/dev/'`

or relative path starting with `.`
`src: './Documents/dev/'`

**Comment by EugenMayer** [comment]
@donnykurnia AFAIR we use expand to deal with ~, so that should actually work. But that needs to be debugged. but in the logs above, we see `/home/User/Documents/dev/` and that looks like properly expaneded i guess - but the path looks strange. Which OS is that @J-Fricke ?

Also, why do you set sync_host_port: 10871 ?

**Comment by J-Fricke** [comment]
@donnykurnia Tested hard coding the user's path for this machine and it still gives the same error, so ~ is confirmed not the issue.

@EugenMayer This is Ubuntu on WSL Windows.

Unsure where that sync_host_port setting was derived, but it works fine on OSX version running elsewhere. Could remove that entry if it's not needed or change it to something else.

**Comment by EugenMayer** [comment]
port is auto-guessed so usually no need to set it usually

**Comment by J-Fricke** [comment]
@EugenMayer That's what I thought and how I initially had it, then one system complained so I added that in there.

**Comment by EugenMayer** [comment]
@J-Fricke seems like a compose issue, or more bash on windows. I will rename the issue and keep it open for people coming by until the issue has been fixed.

Are you going to track it?

**Comment by J-Fricke** [comment]
Yes, I've had to put it on hold a bit. I'll track this for now and update if I find a solution.

**Comment by MichaelFurtner** [comment]
Any updates here? We're currently stuck here as well.

**Comment by J-Fricke** [comment]
@MichaelFurtner No update currently, this project was put on hold and recently we simply decided to move forward with dev on another osx machine instead of attempting to get working with Windows.

@EugenMayer Note as of right now, I will no longer be working on this one.

**Comment by EugenMayer** [comment]
closing this issue since we have no movement but also nothing to grip and work on

**Comment by avremel** [comment]
Running this docker implementation of Magento: 
https://github.com/markoshust/magento-docker

```
**ERROR: for magento2_app_1  Cannot start service app: driver failed programming external connectivity on endpoint magento2_app_1 (359a0841e71cefd160dae84db9c0db3289ac924b3738f10e39c5f3abba5480cf): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)

ERROR: for app  Cannot start service app: driver failed programming external connectivity on endpoint magento2_app_1 (359a0841e71cefd160dae84db9c0db3289ac924b3738f10e39c5f3abba5480cf): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)
Encountered errors while bringing up the project.
EXCEPTION: #<Docker::Compose::Error: 'up' failed with status 'pid 5943 exit 1': Starting magento2_db_1 ... >
MESSAGE: 'up' failed with status 'pid 5943 exit 1': Starting magento2_db_1 ... **
```

**Comment by donnykurnia** [comment]
@avremel the error that you got means that there are programs that already listen in port 80.
It's not related to docker-sync. Please read the docker documentation and learn about port binding.

**Comment by EugenMayer** [comment]
thanks @donnykurnia
