### ISSUE TITLE
delay on sync after upgrading 0.4.6

### ISSUE THREAD

**Issue by speedupmate** [EugenMayer/docker-sync#405]
### Error/Feature Requestion/Docs
after updating to latest 0.4.6 sync become delayed. Hit save on file and wait 20 secs for sync to starts

### Docker Driver
? (d4m or docker-machine+vbox/fusion)

Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 365
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby

### Sync strategy

unison 

### your docker-sync.yml
version: "2"
options:
 unison_image: 'eugenmayer/unison'
 cli_mode: 'auto'
syncs:
  datahost-sync: #tip: add -sync and you keep consistent names als a convention
    src: '~/data/app'
    sync_strategy: 'unison'

### OS
? (OSX Version/Linux)

OSX 10.11.6

**Comment by EugenMayer** [comment]
0.4.6 did not change anything for unison. What you probably facing is the watchdog vs macfsevent issue see https://github.com/EugenMayer/docker-sync/issues/308 ... consider migrating to native_osx since you use d4m

**Comment by speedupmate** [comment]
ok thanks for this info will try out. could not get native_osx to sync a thing and i'm not able to get this to work so reverted back to unison
