### ISSUE TITLE
configuring Docker-sync from mac directory to container on running (or) stopped containers during start 

### ISSUE THREAD

**Issue by vranganatha2** [EugenMayer/docker-sync#408]
i need to do docker sync on the stopped container, which means my containers were already created using swarm, i want to sync my mac directory to the container directory on stop and start . I think docker-sync only works when you create it new am i right ?

**Comment by EugenMayer** [comment]
docker-sync does pickup available containers, if they have the right name.

But what are you actually doing ? Seems like not the normal docker-sync case right

**Comment by vranganatha2** [comment]
if it picks the available containers thats great, thats what i need  . when i try to see the examples given  in docker-sync-boilerplate, i am getting an error stating that my docker is in swarm mode. Could you help me out ?? 
I am running my containers in swarm mode. which means a service from swarm perspective which in turn starts the containers. what i am trying to do is , i want my local mac directory
 /Users/vranganatha2/sharingdata to get synced with <container-ID>:/opt/folderInContainer.

**Comment by EugenMayer** [comment]
i have no idea how to do what you want - you tell me :)

**Comment by vranganatha2** [comment]
can we use docker-sync in swarm mode ?

**Comment by EugenMayer** [comment]
i have no idea, you are free to try but do not expect support here :) You are doing something which it has not been designed for. It might work, it might not

**Comment by vranganatha2** [comment]
according to my understanding docker-sync is to sync the data between the local system and the docker containers right ?

**Comment by EugenMayer** [comment]
http://docker-sync.io is what you start with, then you start using it as its designed - understand it and then you can stretch the limit. There is no shortcut to this
