### ISSUE TITLE
app_sync permission changes to root when using workdir in Dockerfile

### ISSUE THREAD

**Issue by iverberk** [EugenMayer/docker-sync#411]
### Issue

I'm not sure that this is an issue with docker-sync but I couldn't find any relevant information on the problem so I'm hoping someone has more insight. I've created a simple test repository to recreate the issue: https://github.com/iverberk/docker-sync-perm-test

1. Start docker-sync with ```docker-sync start```
2. Build Dockerimage ```docker build -t ds-perm-test .```. Observe that the Dockerfile has a WORKDIR set to /opt/app.
3. Check permissions of the app_sync folder ```docker exec test-sync ls -la /```. Observe that the app_sync folder has permission 1000 (dockersync) as expected.
3. Start new container with volume from sync container: ```docker run -it --rm -v test-sync:/opt/app ds-perm-test /bin/sh```
4. Check permissions of the app_sync folder ```docker exec test-sync ls -la /```. Observe that the app_sync folder has permission 0 (root) which is not expected.

The permissions will be altered if you mount the sync volume on the same path as the WORKDIR. Leaving out the WORKDIR command from the Dockerfile or mounting to a different path than WORKDIR will leave the permissions intact. I'm not sure what is causing the permission change, but it might be Docker.

In my case the WORKDIR command is important because I have a build image where the entryscript expects to be in a certain directory. Is there any way to overcome this issue without adding logic to the start script to change directories?

Thanks.

### Docker Driver
Docker for Mac 17.03.1-ce-mac12 (17661)

### Sync strategy
native_osx

### your docker-sync.yml
```yaml
version: "2"

options:
  verbose: true
syncs:
  test-sync:
    src: '.'
    sync_userid: '1000'
```

### OS
MacOS Sierra 0.12.5 (16F73)

**Comment by EugenMayer** [comment]
you forgot :nocopy 

```
docker run -it --rm -v test-sync:/opt/app ds-perm-test:nocopy /bin/sh
```

**Comment by iverberk** [comment]
ok, awesome! I did see that flag in my research but I didn't make the connection. Also, it's not really easy to find in the Docker docs as well. Anyway, thanks for the quick response, this solves my issue!

**Comment by EugenMayer** [comment]
see https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration  .. https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration#why-nocopy-is-important
