### ISSUE TITLE
Create debugging guide in the wiki

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-sync#413]
create a guide on how to gather informations why sync did not work:
 - how to access the sync container, how to identify the right one
 - host/app sync check
 - how to restart unison using supervisord - any changes
 - how to verify that host_sync works first
 - how to verify if app_sync worked
 - how to verify timestamps and potential conflicts
 - how to put unison into a more transparent mode when it feels a conflict happend (copyonconflict) - so how to make it more visiable
 - to the check the unison log

**Comment by codycraven** [comment]
https://github.com/EugenMayer/docker-sync/wiki/8.1.-native_osx-sync-strategy-debugging-guide

**Comment by EugenMayer** [comment]
That is already awesome! Trying to fill it above ASAP!

**Comment by codycraven** [comment]
I've determined that the culprit is Unison failing to synchronize (I don't know why yet).

However I've written a script that will repair a broken Unison sync.

```
curl -s \
  https://gist.githubusercontent.com/codycraven/5faf08a194d28059d6bdd16d64baae00/raw/ca1805784de16ad5d65600841c187ce1e26bf31a/docker-sync--osx-native--repair.sh \
  | bash -s your-sync-name
```

_Replace `your-sync-name` with the name of your broken sync from docker-sync.yml._

**Comment by EugenMayer** [comment]
@codycraven interesting - would it also just help, running `supervisorctl restart unison` instead of killing?

**Comment by codycraven** [comment]
@EugenMayer I'd imagine it would have the same effect. I'll have to wait until I encounter it again to verify.

**Comment by EugenMayer** [comment]
@codycraven i think the basic guide is good for a go right now, closing this ticket for now. Just reopen if we have anything bigger to work on anytime
