### ISSUE TITLE
Quick Test: can we ensure sync works using rspec

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-sync#414]
we had this talk already, but how fast can we bootstrap this for https://github.com/EugenMayer/docker-sync/issues/410#issuecomment-305107924 ?

We would need to verify that a resync works and or, where it failed ( app sync or host sync? )

We probably need the bash plugin + probably inspec as i wrote in https://github.com/EugenMayer/docker-sync/issues/23#issuecomment-302794146

since you both are way ahead in rspec then i am, i really ask kindly to help me out - i help were i can.

**Comment by michaelbaudino** [comment]
![](https://media.giphy.com/media/1zTqgW6bS2jWU/giphy.gif)

**Comment by EugenMayer** [comment]
suit up! :)

**Comment by ignatiusreza** [comment]
sorry, I don't have much space now for anything urgent, but I'll be happy to review the PR when it come

**Comment by EugenMayer** [comment]
@michaelbaudino did you have anything done no this regard already Michael?

**Comment by michaelbaudino** [comment]
I actually could start to work on it this morning in the train, I'll post something tonight 👍

**Comment by EugenMayer** [comment]
@michaelbaudino _awesome_!

**Comment by michaelbaudino** [comment]
This should actually have been addressed by #422 now.
