### ISSUE TITLE
[idea] Memory usage issue on large diff - ability to set mem_limit and restart: on-failure docker options?

### ISSUE THREAD

**Issue by dcosson** [EugenMayer/docker-sync#416]
### Error/Feature Requestion/Docs

Sometimes when I have a large working directory change at one time (such as checking out a different git branch that has a lot of changes), the CPU and memory usage spike in my sync container (memory usage goes from ~30M to > 1G as shown by ctop). I haven't looked too much into it but it seems like some kind of error or possibly infinite loop, at this point files are not syncing and it doesn't finish whatever it's doing after a few minutes of waiting so I `docker-sync stop` and then start again at which point it starts working normally at back to ~30M of memory usage.

Ideally this bug can be fixed, but as an easy workaround it seems like it would work to be able to set docker settings for the sync container like `mem_limit=64m` and `restart: on-failure` so that in the case of any memory leak the sync process will just restart. Is this possible to do?

### Docker Driver
docker 4 mac, latest stable

### Sync strategy
native_osx

### OS
MacOS 10.12.5

**Comment by EugenMayer** [comment]
Interesting point actually to make docker-sync a bit more self-healing. Yet not planning to work on this, but i think that is a valuable  addition!

**Comment by codycraven** [comment]
@dcosson this may correlate with #410. I have noticed that the docker-sync failure usually coincides with or shortly after making many changes (such as changing branches).

Next time this occurs for you, run the following (replace "your-sync-name" with the name of your sync container) to get the log and attach it to this thread.

```
SYNC_CONTAINER=your-sync-name docker exec "$SYNC_CONTAINER" cat "/tmp/$( echo $( docker exec "$SYNC_CONTAINER" ls /tmp/ | grep ^unison-stdout-- ) )"
```

**Comment by EugenMayer** [comment]
we could actually also use the new implement monit to deal with that from the inner of the container, just restarting unison as we do with CPU usage since 0.5.2+

**Comment by EugenMayer** [comment]
@codycraven are you willing to work on this and provide a PR? Would be great?

**Comment by tmbdrogba** [comment]
+1 for this feature!

**Comment by EugenMayer** [comment]
Closing as non critical issue / feature and i'am not going to work and further nice to have features for now. Be sure to reopen this issue if you want to work on this issue yourself and provide a PR. Happy to review those
