### ISSUE TITLE
Error when checking for new version : update_check.rb:49:in `iso8601': invalid date 

### ISSUE THREAD

**Issue by tpoindessous** [EugenMayer/docker-sync#417]
Hi

I have a customer which uses docker-sync under macOS (I don't know which version).
When he launch docker-sync, he gets an error :
```
update_check.rb:49:in `iso8601': invalid date 
```

Here is  this docker-sync-global.yml :
```
---
update_check: true
update_enforce: true
upgrade_status: |
  0.2.1
```

It seems that he is missing this line : `update_last_check: '2017-03-15T12:09:06.273994000+01:00'`, I don't know why.

But docker-sync should test this line before trying to use the value.

Thanks !

**Comment by tpoindessous** [comment]
I think he is using last version, because the full line of the error is : 
```
/Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/update_check.rb:49:in `iso8601': invalid date (ArgumentError)
```

**Comment by EugenMayer** [comment]
rm `~/.docker-sync-global.yml` and try again
