### ISSUE TITLE
speed issues

### ISSUE THREAD

**Issue by vladislavs1321** [EugenMayer/docker-sync#419]
just update from 0.2.* to latest and for me and my colleagues it start to work slowly with old version in comparison.. is it possible to speed up?

### Docker Driver
d4m

### Sync strategy
unison 

### docker-sync.yml
syncs:
    end-docker-sync:
        src: '.'
        sync_strategy: 'unison'
        notify_terminal: true
        sync_excludes:
            - '.idea'
            - '.DS_Store'
            - '.git'
            - 'app/cache/*'
            - 'app/logs/*'
            - 'node_modules/*'
            - 'provisioning'
            - 'docker'
        sync_args:
            - "-ignore='BelowPath .git'"
            - "-prefer newer"
        max_inotify_watches: 100000

### OS
OSX

**Comment by EugenMayer** [comment]
0.4.6 did not change anything towards unison except if you reinstalled unox, which nowdays uses watchdog not fswatch.

If you want to speed up, use native_osx as the strategy.
