### ISSUE TITLE
Add warning + confirm when running docker-sync-stack clean

### ISSUE THREAD

**Issue by jenswegar** [EugenMayer/docker-sync#423]
A couple of times now I've run `docker-sync-stack clean`, when I was supposed to run `docker-sync clean`. I if understand it correctly, the difference is that with the `docker-sync-stack` version of the clean command, the cleanup also potentially deletes volumes that have been created by docker-compose up (depending on docker-compose settings) because it runs `docker-compose down`, whereas the `docker-sync` version just deletes volumes actually created for use by docker sync. Since 99% of my commands are `docker-sync-stack` related, I always forget about the `docker-sync` commands.In my case my mistake meant the database that I was using for local development also went bye bye, which I didn't want, and of course I don't have my backup with me (which obviously is a stupid user error).

So I'd suggest adding a confirm step to the docker-sync-stack version of the clean command, warning the user of potential data loss, with an optional flag (e.g. `-y`) for users that are always sure they want to actually run the `down` command of docker-compose in addition to removing the volumes and containers that docker-sync needs itself.

**Comment by EugenMayer** [comment]
i understand your point - but whatever there is that is deleted by using `docker-compose down` is _designed_ to be that way. If you use anon volumes which you actually want to be persisted over docker container reset ( delete create ) you have to use named volumes.

The reason you actually have issues is, that you miss designed your volume setup.

Please understand dockers philosophy is, that removing containers can happen anytime and is similar to restart a vm/barebone. 
Thus, anon-volumes should only be used for things which should not be persisted over container restarts to use it as a rule of thumb ( even though a container stop / start will reused the anon image ).

Container stop/start is used very rarely, you will find that most orchestrators will remove the containers and create new
