### ISSUE TITLE
Can not install docker-sync

### ISSUE THREAD

**Issue by RouvenHills** [EugenMayer/docker-sync#428]
Hi there,

kind of a newbee so maybe I just don't see the obvious solution, but really need this for an upcoming project. My problem ist that I cannot install docker-sync at all. As soon as I write in my Terminal (OSX 10.12.2) the install line I get this:

rouvenhills$ gem install docker-sync
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4

What do I do to fix this?

Cheers

**Comment by kducharm** [comment]
You'd need sudo gem install docker-sync

**Comment by EugenMayer** [comment]
since you are using system ruby, you need admin rights -> sudo as @kducharm outlined

**Comment by RouvenHills** [comment]
It worked, thx!
