### ISSUE TITLE
Not functionnal when linked in /usr/local/bin

### ISSUE THREAD

**Issue by mickaelperrin** [EugenMayer/docker-sync#44]
I made a link from the `docker-sync` exe to `/usr/local/bin`

When I run `docker-sync sync -n src --config='/path/to/config/docker-sync.yml'`, I got the following error:

    /Users/mickaelperrin/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- docker-sync/update_check (LoadError)
	from /Users/mickaelperrin/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/bin/docker-sync:5:in `<main>'

This also prevents the sync to be done on `fsevents`.

Using an absolute path works.

**Comment by EugenMayer** [comment]
that makes sense resolving the symlink, i guess some people will do what you have done, eventhough the gem should be installed into the executable path already.

**Comment by EugenMayer** [comment]
We need the same fix for docker-sync-stack, could you include that one @mickaelperrin ?

**Comment by EugenMayer** [comment]
thank you @mickaelperrin
