### ISSUE TITLE
Have warning exit with 0

### ISSUE THREAD

**Issue by MrMMorris** [EugenMayer/docker-sync#441]
## Feature Request
Have `warning  docker-sync already started for this configuration` exit with 0

### Docker Driver
docker-machine

### Sync strategy
default

### your docker-sync.yml
N/A

### OS
OSX

So when docker-sync is already started, and you run `docker-sync start`, you get a warning:

`warning  docker-sync already started for this configuration`

This is all well and good, but it exits with code 1, which doesn't make sense to me. It also means running `docker-sync start` in a Makefile will always fail if it's already running.

Would it be possible to exit with 0? Is there a reason docker-sync should error out when it's just essentially an informational message?

https://github.com/EugenMayer/docker-sync/blob/3c41c1164dee6c67463ddc798204f1641ce36f35/tasks/sync/sync.thor#L158-L159

**Comment by EugenMayer** [comment]
1 means partial success, or in other meaning, you command could not run, since there was an issue. It could not be "started" - it was already running. So -1 is pretty valid in this case.

You seem to use docker-sync in a automated environment and i doubt that is ever a good idea though.
