### ISSUE TITLE
get_host_ip_default in sync_process.rb returns null on linux presets, causing unison error

### ISSUE THREAD

**Issue by aarjona-rootstack** [EugenMayer/docker-sync#444]
### Error
On line 73 sync_process.rb if run on linux the function will return blank, instead of 127.0.0.1 (due to both presets returning false). This causes unison to be run like so:
```command  unison -testserver /app_sync "socket://:32771"```
who in turn errors out:
```Uncaught exception Prefs.IllegalValue("socket://:32771: missing host")```

docker-sync however does not show this message (it's displayed running the command manually), instead the error on docker-sync side is:

/var/lib/gems/2.3.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_strategy/unison.rb:191:in 'block in start_container': Failed to start unison container in time, try to increase max_attempt in your configuration. See https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration for more informations (RuntimeError)
	from /var/lib/gems/2.3.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_strategy/unison.rb:187:in 'loop'
	from /var/lib/gems/2.3.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_strategy/unison.rb:187:in 'start_container'
	from /var/lib/gems/2.3.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_process.rb:107:in 'start_container'
	from /var/lib/gems/2.3.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:92:in 'block in start_container'
	from /var/lib/gems/2.3.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:91:in 'each'
	from /var/lib/gems/2.3.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:91:in 'start_container'
	from /var/lib/gems/2.3.0/gems/docker-sync-0.4.6/tasks/sync/sync.thor:166:in 'daemonize'
	from /var/lib/gems/2.3.0/gems/docker-sync-0.4.6/tasks/sync/sync.thor:48:in 'start'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in 'run'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in 'invoke_command'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in 'dispatch'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in 'start'
	from /var/lib/gems/2.3.0/gems/docker-sync-0.4.6/bin/docker-sync:14:in '<top (required)>'
	from /usr/local/bin/docker-sync:23:in 'load'
	from /usr/local/bin/docker-sync:23:in '<main>'

### Docker Driver
? (d4m or docker-machine+vbox/fusion)

### Sync strategy
unison

### your docker-sync.yml
version: "2"
syncs:
  docker-sync-myproject:
    src: '../docroot'
    sync_strategy: 'unison'
    sync_userid: '82'
    sync_prefer: 'default'
    watch_excludes: ['.*/.git', '.*/node_modules', '.*/bower_components', '.*/sass-cache', '.*/.sass-cache', '.*/.sass-cache', '.coffee', '.scss', '.sass', '.gitignore']
    sync_excludes: ['.gitignore', '.git/', '.idea/', '.DS_Store', 'node_modules/', 'bower_components/']

### OS
Linux Ubuntu 16.10

**Comment by EugenMayer** [comment]
under linux, you only can use the default, native strategy, no unison or rsync ( since it does not make sense ) see https://github.com/EugenMayer/docker-sync/wiki/docker-sync-on-Linux#dependencies

**Comment by aarjona-rootstack** [comment]
Hello, 
I'm a bit confused as to why you say it's not supported, wondering if it's a mistake. I followed that same page that says unison is supported provided I install it from source (which I did), and it works if the function reported here returns a default localhost ip (which it did 3 months ago). 

https://github.com/EugenMayer/docker-sync/commit/f83b395fc1dca1ce14ff9ff199a5fdaa20c1945e#diff-e090d1f81df1b97dda56e9dc50a1993fL58

**Comment by EugenMayer** [comment]
Well i add the one maintaining linux but unison makes no sense.

**Comment by ignatiusreza** [comment]
I'll try to fix this tomorrow.. meanwhile, you should be able to make it work by adding `sync_host_ip: '127.0.0.1'` in the sync configuration..

Also, could you share why you chose to use `unison` over `default` sync strategy?

**Comment by aarjona-rootstack** [comment]
Thank you folks.
I believe unison was picked because it's the strat shared by all 3 platforms which are used by different members of our team, so it simplifies some aspects of setup and config.

**Comment by rodrigoaguilera** [comment]
Trying the unísono strategy on Linux is on my to do list to solve permission problems. For example with UIDs that come hardcoded in some docker images.
