### ISSUE TITLE
~ resolving User directory with space in it breaks sync container startup

### ISSUE THREAD

**Issue by J-Fricke** [EugenMayer/docker-sync#446]
When using `~` to resolve the user path (useful when sharing environment with multiple users), if there is a space in the path, it breaks.
Assuming user's path is `/Users/name spaced/Documents`
Breaks
```
syncs:
  pks-web-sync:
    src: '~/Documents/'
```
Works
```
syncs:
  pks-web-sync:
    src: '/Users/name\ spaced/Documents/'
```

As an aside, it was rather random in how this came about. I was migrating one mac to another and I already had created a user of same name before starting Migration Assistant and it added ` 1` with the space to the username before creating the new account and then later deleted the second account which shared the name.

So I started with...
Mac 1:
`/Users/user`
Mac 2:
`/Users/user`

after Migration Assistant...
Mac 1:
`/Users/user`
Mac 2:
`/Users/user 1` - files and such all copied here

**Comment by EugenMayer** [comment]
Thank you for reporting this, should be rather easy to fix

**Comment by J-Fricke** [comment]
@EugenMayer Thanks, that's what I figured since the manual fix was so simple. I already updated the username directory to remove the space, so am up and working there as well.
