### ISSUE TITLE
High Sierra Beta 5: unison strategy does not work

### ISSUE THREAD

**Issue by ngoctr** [EugenMayer/docker-sync#447]
### Error/Feature Requestion/Docs
Can't start docker-sync on macOS High Sierra with the following error log
```docker-sync start --foreground
       note:  Starting in foreground mode
          ok  Starting unison for sync web-sync
          ok  web-sync container not running
          ok  creating web-sync container
     command  docker run -p '127.0.0.1::5000' -v web-sync:/app_sync -e VOLUME=/app_sync -e TZ=${TZ-`readlink /etc/localtime | sed -e 's,/usr/share/zoneinfo/,,'`} -e UNISON_EXCLUDES="-ignore='Path .*.swp' -ignore='Path */.*.swp' -ignore='Path .git' -ignore='Path .idea' -ignore='Path .awcache' -ignore='Path .happypack' -ignore='Path assets/[0-9a-f]*' -ignore='Path di-container.php' -ignore='Path docker/mysql' -ignore='Path protected/lib/Kounta/Config/cache/*.php' -ignore='Path protected/runtime'" -e OWNER_UID="48"  --name web-sync -d eugenmayer/unison
          ok  starting initial sync of web-sync
     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' web-sync
     command  unison -testserver /app_sync "socket://127.0.0.1:32769"
/usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_strategy/unison.rb:191:in `block in start_container': Failed to start unison container in time, try to increase max_attempt in your configuration. See https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration for more informations (RuntimeError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_strategy/unison.rb:187:in `loop'
	from /usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_strategy/unison.rb:187:in `start_container'
	from /usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_strategy/unison.rb:39:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_process.rb:87:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:100:in `block in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:99:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:99:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/tasks/sync/sync.thor:52:in `block in start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/tasks/sync/sync.thor:51:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/tasks/sync/sync.thor:51:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/bin/docker-sync:14:in `<top (required)>'
	from /usr/local/bin/docker-sync:22:in `load'
	from /usr/local/bin/docker-sync:22:in `<main>'
```

### Docker Driver
d4m

### Sync strategy
unison

### OS
OSX Version 10.13 Beta 5

**Comment by EugenMayer** [comment]
Cannot and will not debug this for a long time, since iam on Sierra and stay there for at least another 1 year.

If you want to get this fixed, you will need debug this yourself, sorry

**Comment by EugenMayer** [comment]
Adjust max_attempt, probably this helps, probably a false positive

**Comment by ngoctr** [comment]
Thanks @EugenMayer for the info. I was able to get it work by switching to native_osx sync strategy. No change needed.

**Comment by EugenMayer** [comment]
So it's an unison issue, probably unox or unison might not properly compile.

That's the buty of native_osx not being in need of any osx dependencies.

Thank you for reporting back

**Comment by alankent** [comment]
Someone recently told me High Sierra removed some OS calls that Unison depends on, so old Unison binaries no longer work on Mac.

**Comment by EugenMayer** [comment]
So the unison strategy will no longer work on HS? Oh, hope that changes over time, but also glad that we have native_osx, which does not use unison on OSX, but rather in the LINUX container.

I also checked if APFS does any good for d4m under HS, but actually, its still as slow, so docker-sync will also be needed for HS

**Comment by EugenMayer** [comment]
at all, since i am not going to upgrade to high sierra for at least 1 to 1,5 years, i will not be able to work on this issue at all. Are there any volunteers for that - would be great!

**Comment by zedtux** [comment]
@ngoctr do you still have the issue? I'm using docker-sync on High Sierra and all is working fine for me.

**Comment by rodrigoaguilera** [comment]
@zedtux I have being waiting to read that. I guess I will do a fresh install in the following weeks and then report back here

**Comment by EugenMayer** [comment]
Oh great if that actually has been fixed - awesome news. Sure we would need 1 or 2 more people to confirm that, but those are great news @zedtux - thanks!

**Comment by zedtux** [comment]
Just show it in action:

![docker-sync_high-sierra](https://user-images.githubusercontent.com/478564/31623803-e9548654-b2a0-11e7-949b-2dfd288aa7fe.png)

**Comment by EugenMayer** [comment]
Great! Could you run the tests once? https://github.com/EugenMayer/docker-sync/wiki/3.-Tests#automated-integration-tests ?
just the automated ones - thank you a lot

**Comment by zedtux** [comment]
@EugenMayer I will do it this evening, when I'll be back home.

**Comment by FlorianDr** [comment]
@EugenMayer, here is what I get on High Sierra (10.13):

![image](https://user-images.githubusercontent.com/17702675/31824965-f9d95500-b5b0-11e7-9739-d6f8378bb9ce.png)

**Comment by EugenMayer** [comment]
that is what we need, this tests look good! @michaelbaudino thanks :)

I would close the issue if there are no further concerns
