### ISSUE TITLE
docker-sync-stack start a given service

### ISSUE THREAD

**Issue by zedtux** [EugenMayer/docker-sync#461]
### Feature Requestion
We have a stack file composed of many services but we aren't working on all the services at the same time.

Until we find this awesome peace of software, we were using compose in a Linux VM where we were doing some `docker-compose up <service name>`.

It seems this is not possible with docker-sync-stack right now, it starts the entire stack.

So it would be great to be able to give one or many service names to start to the command line tool, and when none are given, then the actual behaviour.

**Comment by EugenMayer** [comment]
in that case, just use docker sync without stack

    docker-sync start
    docker-compose up service

**Comment by zedtux** [comment]
Thank you @EugenMayer for your comment, but then what is the purpose of `docker-sync-stack`? I mean, what is the difference using `docker-sync-stack start` or `docker-sync start`?

**Comment by EugenMayer** [comment]
docker-sync-stack starts docker-sync "the sync" containers and then, when done, it starts the docker-compose stack using `docker-compose up`

`docker-sync start` does only start the sync, so you can then start `docker-compose up` manually. Be aware, if you defined docker-compose-dev.yml as you supposed to, you should use either .env or you need to start it with `docker-compose -f docker-compose.yml -f docker-compose-dev.yml up`

But those are all things out of scope for the docs here, those are `docker-compose`  specific basics which you can find in their docs easily.

All you need to know is - you can start the "sync" yourself and then start docker-compose anytime later, also only single services
