### ISSUE TITLE
Provide deb for unison

### ISSUE THREAD

**Issue by Koc** [EugenMayer/docker-sync#462]
### Error/Feature Requestion/Docs
for now for Windows you suggest build unison from sources. It is requires install a lot of software and time. It would be better provide ready deb which we can download and install. 

### Docker Driver
doesn't matter

### Sync strategy
unison

### OS
windows 10 pro

**Comment by EugenMayer** [comment]
Feel free to package unison or docker-sync into such package format and share the link , I can include it in the docs. It will though not be an effort we do in docker-sync
