### ISSUE TITLE
Allow sync host from container

### ISSUE THREAD

**Issue by Koc** [EugenMayer/docker-sync#463]
### Error/Feature Requestion/Docs
We can sync container from host by running `docker-sync sync` but we cann't do vise versa: sync files from container to host

### Docker Driver
doesn't matter

### Sync strategy
unison

### OS
Windows 10 pro

**Comment by EugenMayer** [comment]
You skipped 70% of the needed informations and ask others to help you anyway, even though you seem to be not ingesting any effort. Thats a bold move, let's see how this turns out :)
