### ISSUE TITLE
`docker-sync-stack start` stuck when signed in with Docker for Mac

### ISSUE THREAD

**Issue by zedtux** [EugenMayer/docker-sync#464]
### Error/Feature Requestion/Docs
The tool is working perfectly until I signed in to docker hub from Docker for Mac.

Looking at the code, I found that the tool is stuck at [this line](https://github.com/EugenMayer/docker-sync/blob/0.4.6/lib/docker-sync/update_check.rb#L73) so I tried in a terminal and got the following output:

```bash
docker pull eugenmayer/unison:hostsync_0.2

Please login prior to pull:
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (zedtux@xxxx.xxx):
```

Signing out in Docker for Mac fix this issue.

### Docker Driver
d4m

### Sync strategy
default

### OS
macOS 10.12.6

**Comment by EugenMayer** [comment]
Not sure how this is a docker-sync issue at all? you obviously cannot pull images from the cli, so what should be do about it ( since you miss the credentials? )

Cannot think about anything we could do here, sounds either like a usual d4m freakout, that credentials are not shared, or you probably hit a rate limit, idnk

**Comment by zedtux** [comment]
I see your point of view, but what I think is that docker-sync shouldn't wait for ever, and give a hint about the issue.

The current behaviour is like waiting for something to happen, but it is just wait, without indication.
I had to run manually the command in order to understand what was wrong.

Maybe there is a way to check if d4m is signed in and warn the user?

**Comment by EugenMayer** [comment]
I see, go forward, find out, pull requests are very welcomed! :)

**Comment by zedtux** [comment]
I already started to have a look on how to perform this, but I don't have a 100% working solution for now.

**Comment by EugenMayer** [comment]
@zedtux post PRs i am happy to support you and guide you, no worries.

**Comment by EugenMayer** [comment]
please reopen this issue anytime you want to continue working on this. Happy to see what you have been able to come up with!
