### ISSUE TITLE
Switching image to ubuntu makes example fail

### ISSUE THREAD

**Issue by hekevintran** [EugenMayer/docker-sync#470]
### Error/Feature Requestion/Docs
I'm working from the example at https://github.com/EugenMayer/docker-sync-boilerplate/tree/master/simplest.  When I switch the image to ubuntu:14.04 I get an error: "Error opening terminal: unknown.".  I worked around this by switching the command to ['tail', '-f', '/var/www/index.html'].  Can you provide any information why just switching to ubuntu caused this?  I need to use this platform for my development.  Also is there another alternative noop command to watch or tail?  Tail requires the file actually exist and watch seems to make ubuntu not work.

### Docker Driver
Docker for Mac

### Sync strategy
native_osx

### your docker-sync.yml
same as what's in https://github.com/EugenMayer/docker-sync-boilerplate/tree/master/simplest

### OS
OS X 10.11.6

**Comment by EugenMayer** [comment]
because ubuntu obviously has no watch binary installed in the minimal variant :)

['watch', '-n3', 'cat /var/www/index.html']

Is the entry.

**Comment by hekevintran** [comment]
This is not the reason.  The watch binary is installed.  If I try to run a non-existent program named "tailo" I get a different error:

ERROR: for docker_web_1  Cannot start service web: oci runtime error: container_linux.go:265: starting container process caused "exec: \"tailo\": executable file not found in $PATH"

"Error opening terminal: unknown." must mean something else.
