### ISSUE TITLE
Docker-sync-stack start is executing Production environment

### ISSUE THREAD

**Issue by cduran433** [EugenMayer/docker-sync#471]
!!!! Important hint !!!!!

> Please do not create issues for [docker](https://docs.docker.com/) or [docker-compose](https://docs.docker.com/compose/reference) related questions. Ensure you understand the tools properly and consult their documentation first. Please understand what [docker volumes](https://docs.docker.com/engine/admin/volumes/volumes/) / [docker-compose volumes](https://docs.docker.com/compose/compose-file/compose-file-v2/#specifying-byte-values)

> Please be sure to have a look at our [documentation](https://github.com/EugenMayer/docker-sync/wiki) too, especially [configuration](https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration) and our starting point the [boilerplate](https://github.com/EugenMayer/docker-sync-boilerplate)

### Error/Feature Requestion/Docs
Error

### Docker Driver
docker-machine+vbox/fusion

### Sync strategy
unison
### your docker-sync.yml

version: "2"

options:
  compose-file-path: 'docker-compose.yml'
  compose-dev-file-path: 'docker-compose-dev.yml'
  verbose: true
syncs:
  #IMPORTANT: ensure this name is unique and does not match your other container names
  docker-mac-symfony-sync:
    src: './symfony/'
    sync_strategy: 'unison'
    sync_args:
      - "-prefer newer"
      - "-ignore='Path .git'"
      - "-ignore='BelowPath .git'"
    sync_userid: '1000'
    sync_excludes: ['app/cache/', '.gitignore', '.git/']

  docker-mac-mysql:
    src: './mysql'
    sync_strategy: 'unison'

### OS
10.11.2 (15C50

My problem is really simple, I have the below docker sync file and I have two docker-compose files, one for development and the other for production. If I execute:

docker-sync start
docker-compose -f docker-compose-dev.yml

It is working like a charm. But if I try with:

docker-sync-stack start

The docker-compose file for production is executed and my enviroment is slow in develop. How can I change that to force to use the development file (docker-compose-dev.yml)

Thanks!

**Comment by EugenMayer** [comment]
Did you read the top-level statement of this issue? please use its documentation, its explained exactly there. thank you.

Please understand, i do not want to repeat in the issues again and again, that is what the docs are for.

**Comment by cduran433** [comment]
Hello Eugene, 

I understand you and sorry for ask you the same question. Yes, I read the documentation and had my environment working .. but after update docker I face this problem, and this is why I am asking for that, because I didn't make any changes in the files and right now I am not able to work with docker-sync-stack.

Thanks

**Comment by EugenMayer** [comment]
`docker-compose -f docker-compose-dev.yml` is entirely wrong and that is also explained in the docs. `docker-compose -f docker-composer.yml -f docker-compose-dev.yml` is right. How and what, please read the documention.

You do not run the "production" stack with docker-sync, since docker-sync is for development only and never should be used in production. **Never**. 

But how to change the compose file used - see our docs in configuration.

**Comment by cduran433** [comment]
Yes, maybe I didn't explain well.. I have two files one is the original docker-compose file that I use for production and the second one is the dev file that I use to override the production and work in my laptop with a good performance. This configuration was working. docker-sync-stack clean and docker-sync-stack start and everything was working. Right now it is not possible because when I execute that the performance is really bad. I was trying to debug what is happening and I executed after docker-sync start these commands:

If i do this then is working
docker-compose -f docker-compose-dev.yml

But if I tried with the other option
docker-compose -f docker-compose.yml -f docker-compose-dev.yml

The performance is really really slow, and this is the command that docker-sync-stack is executing. 

I don't find anything related to "docker-compose -f docker-compose-dev.yml is entirely wrong and that is also explained in the docs."

Docs is the wiki of this project?

Thank you

**Comment by EugenMayer** [comment]
Paste your docker sync and both compose files here, please with proper markup so one can read them.

Your issue is in the compose.yml, you seem to have a volume for code there and that's not overlayed buy the Dev one

**Comment by EugenMayer** [comment]
Please read in the docker compose docks how the deep merge is working, especially for volume definition, try to wrap your head around it and paste a deep link to the definition here so we can talk about that later

**Comment by EugenMayer** [comment]
I think that might help you https://github.com/EugenMayer/docker-sync/pull/222

**Comment by cduran433** [comment]
Thank you for your tip.

I still having problems, when I have to overwrite volumes,  I don't understand what is happening..  the other config is overwritted but I am not able to overwrite volumes.. the rest of the config is overwritten but volumes always get the volume from the docker-compose.yml.

I keep researching and if I find something else I will write it here.

Thank you!

This is the config 
**docker-compose.yml**


`version: '2'
services:
    db:
        image: mysql:5.5
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony-vagrant
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
    php:     
        build: ./php-fpm
        expose:
            - "9000"
        volumes:
            - ./symfony:/var/www/symfony/
            - ./logs/symfony:/var/www/symfony/app/logs
        links:
            - db
            - mongodb
            - redis
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
`
**docker-compose-dev.yml**

`version: '2'
services:
    db:
        image: mysql:5.5
        volumes:
            - docker-mac-mysql:/var/lib/mysql:nocopy
    php:
        volumes:
            - docker-mac-symfony-sync:/var/www/symfony
volumes:
  docker-mac-symfony-sync:
    external: true
  docker-mac-mysql:
    external: true
`

docker-sync.yml
'
version: "2"

options:
  compose-file-path: 'docker-compose.yml'
  compose-dev-file-path: 'docker-compose.override.yml'
  verbose: true
syncs:
  #IMPORTANT: ensure this name is unique and does not match your other container names
  docker-mac-symfony-sync:
    src: './symfony'
    sync_strategy: 'unison'
    sync_args:
      - "-prefer newer"
      - "-ignore='Path .git'"
      - "-ignore='BelowPath .git'"
    sync_userid: '1000'
    sync_excludes: ['app/cache/', '.gitignore', '.git/']

  docker-mac-mysql:
    src: './mysql'
    sync_strategy: 'unison'

'

**Comment by EugenMayer** [comment]
You cannot override volume definitions, that something simply not possible with docker-compose.yml - you can only add
