### ISSUE TITLE
Changes to files inside the host do not trigger a sync (unison)

### ISSUE THREAD

**Issue by mrfelton** [EugenMayer/docker-sync#48]
With a unison sync setup, adding/modifying files within the container does not cause those files to be synced back to the host. The only thing that seems to trigger a sync from the container back to the host is touching a watched file outside of the container.

Is this expected behavior? I had expected 2way sync to automatically detect changes made in either location.

**Comment by mickaelperrin** [comment]
I am currently working on this, see #47

**Comment by EugenMayer** [comment]
also see #42 as an alternative implemantion. 2 way sync right now stands for syncing back changes from the container to the host ( noch only host to container ) when you trigger the sync. Right now it is not possible to detect when to sync "on changes" in the container, only on the host.

You can manually sync for now using

```
docker-sync sync
```

as @mickaelperrin mentioned, different angles are for now taken to takle this. I leave this issue open to avoid people creating another dupe. Later i would just close this issue and working on the other issues as the follow up

**Comment by EugenMayer** [comment]
@mrfelton with the new release, 0.0.14, a new strategy will be available, called unison-dualside implemented by @mickaelperrin . Its already merged into the master and support sync trigger from host and from container, so full transparency.
