### ISSUE TITLE
Crashes: docker-sync-stack start 

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [EugenMayer/docker-sync#49]
```
docker-sync start
```
works ok. 
```
docker-sync-stack start 
```
fails.

```
> docker-sync-stack start
/Library/Ruby/Gems/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:105:in `private': nil is not a symbol (TypeError)
	from /Library/Ruby/Gems/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:105:in `<class:Mapper>'
	from /Library/Ruby/Gems/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:5:in `<module:Compose>'
	from /Library/Ruby/Gems/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:2:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose.rb:10:in `require_relative'
	from /Library/Ruby/Gems/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose.rb:10:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.13/tasks/stack/stack.thor:5:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.13/bin/docker-sync-stack:22:in `load'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.13/bin/docker-sync-stack:22:in `block in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.13/bin/docker-sync-stack:20:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.13/bin/docker-sync-stack:20:in `<top (required)>'
	from /usr/local/bin/docker-sync-stack:23:in `load'
	from /usr/local/bin/docker-sync-stack:23:in `<main>'
```

**Comment by EugenMayer** [comment]
@Vasiliy-Bondarenko which version are you using, 0.0.13?

**Comment by EugenMayer** [comment]
@Vasiliy-Bondarenko https://github.com/xeger/docker-compose/blob/master/lib/docker/compose/mapper.rb#L105 this is due to some unexpected value you your docker-compose.yml oder docker-compose-dev.yml.

Could you post both and double-check and use http://www.yamllint.com/ to validate the yaml files? If this is all good and docker-compose cli works but not the gem, please pick up those 2 files and create an issue on https://github.com/xeger/docker-compose since this the gem failing here. Thank you!

closing here

**Comment by Vasiliy-Bondarenko** [comment]
```
> gem list | grep docker-sync
docker-sync (0.0.13)
```
all yaml files are valid.

```
docker-compose -f docker-compose.yml -f docker-compose-dev.yml up
```
works without problems...
i don't think it's a problem with docker-compose itself...

Files: [Archive.zip](https://github.com/EugenMayer/docker-sync/files/363227/Archive.zip)

**Comment by EugenMayer** [comment]
docker-compose is not docker-compose gem, those are to different things ( fist is the origina golang cli tool, second is a ruby gem wrapper ). Please open a ticket in the project i linked, so we can follow up there. I am a contributor there also

**Comment by Vasiliy-Bondarenko** [comment]
i don't really understand... but ok... :)
https://github.com/xeger/docker-compose/issues/34
