### ISSUE TITLE
There is an exception when sync remote directory is deleted

### ISSUE THREAD

**Issue by b1alpha** [EugenMayer/docker-sync#491]
#### Issue
There is an exception when sync remote directory is deleted

### Steps to reproduce
start sync
delete remote sync directory

#### Expected Result
all local files are deleted or.. all local files are copied back to remote (no docs)

#### Actual Result
most local files are deleted, and docker-sync crashes 

### Error
 success  Sync container started
     success  Starting Docker-Sync in the background
Brennons-MacBook-Pro:professional brennon.obst$ /usr/local/lib/ruby/gems/2.4.0/gems/daemons-1.2.5/lib/daemons/daemonize.rb:157:in `reopen': No such file or directory @ rb_io_reopen - /Volumes/Dev/professional/.docker-sync/daemon.log (Errno::ENOENT)
	from /usr/local/lib/ruby/gems/2.4.0/gems/daemons-1.2.5/lib/daemons/daemonize.rb:157:in `redirect_io'
	from /usr/local/lib/ruby/gems/2.4.0/gems/daemons-1.2.5/lib/daemons/daemonize.rb:112:in `daemonize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/daemons-1.2.5/lib/daemons/application.rb:105:in `start_none'
	from /usr/local/lib/ruby/gems/2.4.0/gems/daemons-1.2.5/lib/daemons/application.rb:294:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/daemons-1.2.5/lib/daemons.rb:308:in `daemonize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/tasks/sync/sync.thor:179:in `daemonize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/tasks/sync/sync.thor:48:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/bin/docker-sync:14:in `<top (required)>'
	from /usr/local/bin/docker-sync:23:in `load'
	from /usr/local/bin/docker-sync:23:in `<main>'

### Error/Feature Requestion/Docs
docker-sync start

### Docker Driver
d4m 

### Sync strategy
native_osx

### your docker-sync.yml
version: "2"
options:
  verbose: true
syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  appcode-rsync-sync: #tip: add -sync and you keep consistent names as a convention
    src: './'
    sync_host_ip: 'auto'
    sync_host_port: 10872
    sync_strategy: 'native_osx'

### OS
OSX 10.13.1

**Comment by EugenMayer** [comment]
please post the error and the configuration a way people can read wit using code tags, thanks!

**Comment by b1alpha** [comment]
Updated to use code tags, thanks for the tip will use from now on

**Comment by EugenMayer** [comment]
the error is pretty clear:
```
Brennons-MacBook-Pro:professional brennon.obst$ /usr/local/lib/ruby/gems/2.4.0/gems/daemons-1.2.5/lib/daemons/daemonize.rb:157:in `reopen': No such file or directory @ rb_io_reopen
/Volumes/Dev/professional/.docker-sync/daemon.log (Errno::ENOENT
```

So you have some weired folder configuration, the docker-sync.yml on a odd place or you have a pid-leftover, in the latter case, try deleting the .docker-sync folder `/Volumes/Dev/professional/.docker-sync`

**Comment by b1alpha** [comment]
the .docker-sync is in the project root so not so weird, clearing the .docker-sync folder fixed the issue. thx
