### ISSUE TITLE
No documentation for 2-way sync flags

### ISSUE THREAD

**Issue by b1alpha** [EugenMayer/docker-sync#492]
#### Issue
There is no documentation for how to disable 2way sync on any of the strategies. 

#### Expected
Some documentation on how to use the sync in typical development workflows

#### Use Cases
Use Case1: If I am developing and i want to push clean code to a container (re-sync)
Use Case2: If I build something on remote, and dont want those files copied to the host
Use Case3: If I remove the src folder on the remote and want a full sync

**Comment by EugenMayer** [comment]
rsync is one-way sync
unison is 2 way sync
native_osx is 2 way sync.

There are no further options

**Comment by b1alpha** [comment]
Just document that, perfect
