### ISSUE TITLE
Errors starting docker-sync

### ISSUE THREAD

**Issue by b1alpha** [EugenMayer/docker-sync#493]
### Error
docker-sync start
          ok  Starting rsync for sync appcode-rsync-sync
          ok  appcode-rsync-sync container not running
          ok  starting appcode-rsync-sync container
     command  docker start appcode-rsync-sync
          ok  appcode-rsync-sync: starting initial sync of /Volumes/Dev/professional/
     command  rsync -ap '/Volumes/Dev/professional/' rsync://127.0.0.1:10872/volume
rsync: failed to connect to 127.0.0.1: Connection refused (61)
rsync error: error in socket IO (code 10) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52/rsync/clientserver.c(106) [sender=2.6.9]
       error  Error starting sync, exit code 10
     message
     success  Rsync server started
     command  rsync -ap '/Volumes/Dev/professional/' rsync://127.0.0.1:10872/volume
rsync: failed to connect to 127.0.0.1: Connection refused (61)
rsync error: error in socket IO (code 10) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52/rsync/clientserver.c(106) [sender=2.6.9]
       error  Error starting sync, exit code 10
     message
     success  Starting Docker-Sync in the background

### Docker Driver
d4m 

### Sync strategy
rsync

### your docker-sync.yml
version: "2"
options:
  verbose: true
syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  appcode-rsync-sync: #tip: add -sync and you keep consistent names as a convention
    src: './'
    sync_host_ip: 'auto'
    sync_host_port: 10872
    sync_strategy: 'rsync'
### OS
OSX 10.13.1

**Comment by EugenMayer** [comment]
rsync cannot connect, this means that either you have an old / other sync container running with the same name or something else.

Stop all sync containers and containers and rm them

```docker kill $(docker ps -q)```

and rm them

```docker rm $(docker ps -a -q)```

No go into your app folder and then run

```docker-sync stop```

and now run

```docker-sync up```

Anything else please use the boilerplate at https://github.com/EugenMayer/docker-sync-boilerplate to reproduce "docker-sync bugs"  with the corresponding strategy. Isolate the issue, ensure you run only one container at each time, since in 99% of the cases it s configuration issue rather then a bug - this way you can reduce the complexity.

**Comment by b1alpha** [comment]
Thanks that worked great!

**Comment by jsierles** [comment]
This issue happens to us on a daily basis, and `docker ps -a -q` is the only way to fix it. Would it be quicker to have `docker-sync start` check if there's existing container? In our case, we have no containers running when this happens. I would assume docker-sync would reuse the stopped container.

**Comment by EugenMayer** [comment]
Joshua are you using rsync as the strategy?

**Comment by jsierles** [comment]
Yes we use rsync on OS X.

**Comment by EugenMayer** [comment]
@jsierles in this case you will need to put your own work into investigating and fixing this, since there is hardly anybody working on anything else then native_osx

**Comment by nathandrew01** [comment]
I ran into this problem on osx. My first guess is that port 873 is blocked on localhost. So I added EXPOSE 873 to Dockerfile but it did not change anything. I cleared out all my networks on docker. This looks like a network error.
