### ISSUE TITLE
Multiple syncs specifications not working only first one in list actually syncs

### ISSUE THREAD

**Issue by b1alpha** [EugenMayer/docker-sync#494]
### Error
multiple syncs not working, only the first one works 

### Docker Driver
d4m 

### Sync strategy
rsync

### your docker-sync.yml
version: "2"
options:
  verbose: true
syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  appcode-rsync-sync-app: #tip: add -sync and you keep consistent names as a convention
    src: './app/'
    sync_host_ip: 'auto'
    sync_host_port: 10872
    sync_strategy: 'rsync'
    notify_terminal: true

  appcode-rsync-sync-cfg: #tip: add -sync and you keep consistent names as a convention
    src: './config/'
    sync_host_ip: 'auto'
    sync_host_port: 10872
    sync_strategy: 'rsync'
    notify_terminal: true

  appcode-rsync-sync-db: #tip: add -sync and you keep consistent names as a convention
    src: './database/'
    sync_host_ip: 'auto'
    sync_host_port: 10872
    sync_strategy: 'rsync'
    notify_terminal: true

### OS
OSX 10.13.1

**Comment by EugenMayer** [comment]
you need to use different ports for each
