### ISSUE TITLE
UNISON_PREFER and UNISON_SYNC_PREFER

### ISSUE THREAD

**Issue by jerome-arzel** [EugenMayer/docker-sync#511]
### Error

In precopy it seems that the environment variable UNISON_PREFER is used.
https://github.com/EugenMayer/docker-image-unison/blob/develop/precopy_appsync.sh

This variable is not defined in native_osx, instead we have maybe the correct variable: UNISON_SYNC_PREFER

### Sync strategy
native_osx

**Comment by EugenMayer** [comment]
thank you! fixed by https://github.com/EugenMayer/docker-image-unison/commit/26dca2d3bb39815cfbd586cbc53623fc82d6b282
