### ISSUE TITLE
Much ❤️ for this code.

### ISSUE THREAD

**Issue by erlandsona** [EugenMayer/docker-sync#513]
Rails 4.2 was serving static assets like a fat pig after a thanksgiving feast and I new my coworkers had gotten nice performance boosts for running their front-end test suites using docker-sync.

I added docker-sync to a project using the default docker-sync-boilerplate and in a few minutes the Rails 4.2 project I was working on was able to serve those same static assets with 10x (+?) speedup.

Thank you.

PS: Feel free to close this whenever.

**Comment by EugenMayer** [comment]
Thanks for the heads up! A lot of people are involved into docker-sync nowdays - sure they are happy to receive those kudos!

For the speedup, can be anything from 10 to 60 times, see our performance tests in the intranet
