### ISSUE TITLE
Disable toast

### ISSUE THREAD

**Issue by pquerner** [EugenMayer/docker-sync#522]
Is it possible to disable the toast message (little info window which appears on MacOS in the top right, when the command has been successful) ?

Reason behind is, that the autosync is not working for me. (I dont know, and have no real time to debug this right now) So I started the "sync" command every 10s via "watch"

```
watch -n10 docker-sync sync
```

But the little toast message is getting quite annoying.

**Comment by EugenMayer** [comment]
https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration

"notify"
