### ISSUE TITLE
Latency in unison sync after file save

### ISSUE THREAD

**Issue by dmifedorenko** [EugenMayer/docker-sync#523]
Hello.

Docker-sync unison strategy have latency about 1-3 second for sync one file. I use docker-sync for local php symfony project to edit code in one small file and debug php response in browser. Sometimes after saving the php file on host machine I dont see changes on docker web server for several seconds. 

Is where any way to minimize latency?
May be I can change some how file watch interval? Looks like watch_args: '-v --latency=0.1' has no effect for unison.

Environment:
- MacOS Hight Sierra 10.13.3.
- Docker For Mac Version 18.01.0-ce-mac48 (22004)
- Unison strategy
- Docker-sync configuration file - [docker-sync.txt](https://github.com/EugenMayer/docker-sync/files/1666969/docker-sync.txt)
- About 22000 files in src folder to sync

**Comment by EugenMayer** [comment]
use proper excludes to minimize that file amount + better CPU + do not use the unison strategy at all, thats exactly the reason native_osx has been developed

**Comment by dmifedorenko** [comment]
Thank you for answer.

Cant minimize amount of files, it is one big project. Tried native_osx and still have latency but sync work faster then unison or rsync.

Thank you for your work. Docker-sync is a great project.
