### ISSUE TITLE
impossible to start docker-sync

### ISSUE THREAD

**Issue by christophemassin** [EugenMayer/docker-sync#526]
### Error/Feature Requestion/Docs
docker-sync start
          ok  Starting native_osx for sync config-sync
config-sync
Error response from daemon: No such exec instance: 74cf6e75f79ad51e6f02399f6d424b1ae66837be7fba0a83a94be06cd5436d4d
/Library/Ruby/Gems/2.3.0/gems/docker-sync-0.5.2/lib/docker-sync/sync_strategy/native_osx.rb:97:in `start_container': Start failed (RuntimeError)
	from /Library/Ruby/Gems/2.3.0/gems/docker-sync-0.5.2/lib/docker-sync/sync_process.rb:105:in `start_container'
	from /Library/Ruby/Gems/2.3.0/gems/docker-sync-0.5.2/lib/docker-sync/sync_manager.rb:99:in `block in start_container'
	from /Library/Ruby/Gems/2.3.0/gems/docker-sync-0.5.2/lib/docker-sync/sync_manager.rb:98:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/docker-sync-0.5.2/lib/docker-sync/sync_manager.rb:98:in `start_container'
	from /Library/Ruby/Gems/2.3.0/gems/docker-sync-0.5.2/tasks/sync/sync.thor:163:in `daemonize'
	from /Library/Ruby/Gems/2.3.0/gems/docker-sync-0.5.2/tasks/sync/sync.thor:47:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/docker-sync-0.5.2/bin/docker-sync:14:in `<top (required)>'
	from /usr/local/bin/docker-sync:22:in `load'
	from /usr/local/bin/docker-sync:22:in `<main>'

even after i've remove everything and rebuild everything, seem to work at first and then it crash , and i don't have anymore sync. it look like he can't find the instance back :/ any idea ?

### Docker Driver
? (d4m or docker-machine+vbox/fusion)

### Sync strategy
native_osx

### your docker-sync.yml
version 2

syncs:
  config-sync:
    src: "${DCK_PATH_CONFIG}"
    sync_strategy: 'native_osx'
    sync_excludes: ['.git', '.idea', 'node_modules']
    sync_prefer: 'default'
    sync_userid: '1000:33'
  website-sync:
    src: "${DCK_PATH_SITE}"
    sync_strategy: 'native_osx'
    sync_excludes: ['.git', '.idea', 'node_modules']
    sync_prefer: 'default'
    sync_userid: '1000:33'
  webextranet-sync:
    src: "${DCK_PATH_EXTRANET}"
    sync_strategy: 'native_osx'
    sync_excludes: ['.git', '.idea', 'node_modules']
    sync_prefer: 'default'
    sync_userid: '1000:33'
  webinvoice-sync:
    src: "${DCK_PATH_INVOICE}"
    sync_strategy: 'native_osx'
    sync_excludes: ['.git', '.idea', 'node_modules']
    sync_prefer: 'default'
    sync_userid: '1000:33'
  webapimobile-sync:
    src: "${DCK_PATH_API_MOBILE}"
    sync_strategy: 'native_osx'
    sync_excludes: ['.git', '.idea', 'node_modules']
    sync_prefer: 'default'
    sync_userid: '1000:33'
  webb2b-sync:
    src: "${DCK_PATH_B2B}"
    sync_strategy: 'native_osx'
    sync_excludes: ['.git', '.idea', 'node_modules']
    sync_prefer: 'default'
    sync_userid: '1000:33'
  webadmin-sync:
    src: "${DCK_PATH_ADMIN}"
    sync_strategy: 'native_osx'
    sync_excludes: ['.git', '.idea', 'node_modules']
    sync_prefer: 'default'

### OS
OSX Version 10.13.3

**Comment by christophemassin** [comment]
Moreover, when i docker-sync stop, i see the list of container that stop, as if it has no issue for starting them.

**Comment by EugenMayer** [comment]
read https://github.com/EugenMayer/docker-sync/issues/517 and probably downgrade to mac42

**Comment by raghuiamsingh** [comment]
try running 
`docker-sync clean`

and then try starting 
`docker-sync start`
