### ISSUE TITLE
Create, start and sync containers without without watching

### ISSUE THREAD

**Issue by fearlsgroove** [EugenMayer/docker-sync#53]
I'd like to be able to create and sync containers, run some cleanup around file permissions stuff and then start watching. Currently creating and starting containers only happens with `docker-sync sync`, which stops containers when stopped.

**Comment by EugenMayer** [comment]
Set watch_strategy:disable and no watch Tabak will be starten.

**Comment by fearlsgroove** [comment]
I don't want to disable watching altogether, just to be able to build the containers and do an initial sync, then exit so I know when the initial sync is done. 

My goal here is to run some cleanup tasks in a script to fix permissions issues with the mounted docker volumes. With rsync i can set the target UID but with unison I can't. I don't want to edit configuration files during the process.

**Comment by EugenMayer** [comment]
unison is about to get his feature. How to script docker-sync is written here https://github.com/EugenMayer/docker-sync/wiki/7.-Scripting-with-docker-sync

This should give you the option to run any before/after tasks, so before sync, after sync, before compose, after compose.

I hope that fits for you

**Comment by fearlsgroove** [comment]
I managed to work around my permissions/uid stuff another way. I don't know (much) ruby so scripting in ruby isn't super straightforward for me, but I'll give it a try anyway.

That said, I still think there's value in reconsidering your command line options here. I'll probably hack my way through building individual scripts to:

start: turns on the containers, does an initial sync
watch: runs start if needed and starts watching
stop: stops the containers
clean: as now

The current options seem like oddly specific combinations of use cases. Not to belabor the point or any thing :)

**Comment by EugenMayer** [comment]
@fearlsgroove even if they seem odd, docker-sync has a specific central use point:
make volume-sharing performance and easy. This is not done by "inital sync" but rather by sync+watch - thats why this is the default and will always be the default.

Splitting operations up in "sync only" and "watch" and things, might become and extra layer, but not the defaults.

Hope that make sense
