### ISSUE TITLE
Windows setup instructions need to have source compile install for ocaml

### ISSUE THREAD

**Issue by akshah123** [EugenMayer/docker-sync#531]
### Error/Feature Requestion/Docs
Instructions for windows setup at preset ask uses to install ocaml directly from ubuntu repository.

This installs ocaml version 4.02.x to be installed. However, ocaml version used to compile unison on alpine docker container is 4.04.02.  This leads to following error:

```
UNISON 2.48.4 started propagating changes at 23:58:18.64 on 11 Feb 2018
[BGN] Updating file spec/requests/some_spec.rb from /mnt/c/Users/xxxxx/Desktop/Web/application to //fdc78677d2e8//app_sync
Failed: Server: Server: Fatal error during unmarshaling (input_value: bad bigarray kind),
possibly because client and server have been compiled with differentversions of the OCaml compiler.
Fatal error: Server: Server: Fatal error during unmarshaling (input_value: bad bigarray kind),
possibly because client and server have been compiled with differentversions of the OCaml compiler.
``` 

As describe in this thread: https://unix.stackexchange.com/questions/309669/unison-fatal-error-during-unmarshaling

The problem is caused by having a different version ocaml used to compile unison even if unison's version is the same.

Once I installed ocaml 4.04.02 from source using instructions here: http://caml.inria.fr/pub/distrib/ocaml-4.04/notes/INSTALL.adoc
and using that to compile unison, above error went away.

I believe instructions should be updated to instead installing ocaml version 4.04.02 from source.

### Docker Driver
Version 17.12.0-ce-win47 (15139)

### Sync strategy
unison

### OS
Windows WSL with ubuntu 16.04.

**Comment by EugenMayer** [comment]
Very interesting finding actually - right now all wiki pages have been deleted by somebody so we cannot add anything, but i would love to see this addition, thanks for finding that one!

**Comment by sav-valerio** [comment]
Very interesting find indeed, I just properly updated the Windows related documentation.

**Comment by EugenMayer** [comment]
@sav-valerio huge thank you for working on the windows documentation so much, very appriated and very hard job actually!

Seems like you are finished, can i close this ticket ?

**Comment by sav-valerio** [comment]
No problem, happy to help!
As for now it is indeed finished, you can close the issue.

**Comment by EugenMayer** [comment]
great!
