### ISSUE TITLE
Ignoring all occurrences of directory on native_osx seems to be not working

### ISSUE THREAD

**Issue by pierzakp** [EugenMayer/docker-sync#534]
Hello,
I have reviewed all of the wiki, docs or any other resources found in the internet, I hope that I did not missed something.
I am still not able to make that all occurrences of some directories or files will be ignored using native_osx strategy. My os is macOs 10.13.3.

My docker sync file:
`version: "2"

options:
  verbose: true
  max_attempt: 90

syncs:
  test-application-sync:
    src: './src'
    sync_strategy: 'native_osx'
    notify_terminal: true
    sync_args:
      - "-ignore='Path .idea'"
      - "-ignore='Path .git'"
      - "-ignore='Path var/cache/*'"
      - "-ignore='Path var/page_cache/*'"
      - "-ignore='Path var/sessions/*'"
      - "-ignore='Path var/tmp/*'"
      - "-ignore='Path var/view_preprocessed/*'"
      - "-ignore='Path var/composer_home/cache/*'"
      - "-ignore='Regex .git'"
      - "-ignore='Regex .gitignore'"
      - "-ignore='Regex .DS_Store'"
    monit_enabled: true`

I want to ignore any .git directory inside of the project, also .gitignore and .DS_Store files.
I do not want that those files will be copied from host to volume. I can not provide whole dir, but I can limit/narrow exclusion to "app/code/*/*/.git". I tried with paths, names, different formats but did not help. Of course between each time I cleaned volume. Can someone provide some small help here?

**Comment by EugenMayer** [comment]
see https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration at `sync_excludes:` and `  watch_excludes:`

**Comment by pierzakp** [comment]
Hi, thanks you for the response.
I already reviewed this wiki.
I used sync_excludes with sync_excludes_type (Name / Path), base on sync_excludes multiple -ignore params are generated so result it is the same (or maybe I am wrong? I was looking at cli command which is executed, maybe it makes difference somewhere deeper). As far as I read watch_excludes is not supported for native_osx.

**Comment by derschatta** [comment]
Hi, I ran into this problem as well. The following format worked for me:
`sync_excludes: ['.idea', 'node_modules', '.gitignore', '.git', '.DS_Store']`

**Comment by EugenMayer** [comment]
Who in hell deleted all wiki pages... 

The point is, that you did not read the configuration page, there is https://github.com/EugenMayer/docker-sync/blob/master/example/docker-sync.yml#L75 and that explains a) what @derschatta has experienced and what you experience @pierzakp 

@pierzakp has to set it to `sync_excludes_type: none` and you @derschatta to path.

**Comment by derschatta** [comment]
Thanks for the hint. That explains it. It's a shame that the wiki is gone.  Good luck in restoring it.
