### ISSUE TITLE
Detect the OS from the info of the docker engine instead of the machine that executes ruby.

### ISSUE THREAD

**Issue by rodrigoaguilera** [EugenMayer/docker-sync#536]
### Feature Request
I am Thinking about writing some developing tool similar to lando, ddev, drupalvm, etc.
They are usually based on running a command "up" wait a bit and you can start coding.
I didn't see any of these integrating with docker-sync and I was wondering if it was even possible to run docker-sync from a container but it will actually setup and start docker-sync for the host OSX.

The first step I identified to achieve such a thing will be to check OS info from the docker engine since right now that information is taken from the OS executing docker-sync.

### Docker Driver
d4m

### Sync strategy
native_osx

### OS
OSX 10.12

**Comment by EugenMayer** [comment]
no progress, closing for now. reopen anytime when you want to continue
