### ISSUE TITLE
Error Downloading 

### ISSUE THREAD

**Issue by cduran433** [EugenMayer/docker-sync#546]
Today I started my docker-compose environment and I face this error:

`docker: Error response from daemon: manifest for eugenmayer/unison:latest not found.
`

I tried to executed directly the image using docker and it seems that the link is broken:

**docker run -it eugenmayer/unison:latest**

_docker: Error response from daemon: manifest for eugenmayer/unison:latest not found._

Do you have any information?

### Error/Feature Requestion/Docs
Error

### Sync strategy
unison

### OS
OSX

**Comment by maitre-hibou** [comment]
Same here... Seems that image doesn't exist anymore on Docker Hub.

**Comment by EugenMayer** [comment]
@cduran433 please upgrade docker sync

**Comment by EugenMayer** [comment]
@maitre-hibou and you too

**Comment by EugenMayer** [comment]
to be more presize, upgrade to 0.5.5 - all the old images will be removed due to several ( severe ) issues, so staying with 0.5.2 will be no option
