### ISSUE TITLE
Update instructions

### ISSUE THREAD

**Issue by sgurlt** [EugenMayer/docker-sync#551]
Hey,

i am currently looking from the changelog for the newest version 5.6.0, but can't find it for now. Does a changelog exist and are there any steps to be respected for the update?

Greetings
Sebastian

**Comment by EugenMayer** [comment]
Sorry, my bad. They are here ( i just have written them, so its all on me )

https://github.com/EugenMayer/docker-sync/releases/tag/0.5.6
