### ISSUE TITLE
gem install docker-sync error

### ISSUE THREAD

**Issue by hkirsman** [EugenMayer/docker-sync#561]
When I run "sudo gem install docker-sync" I get error:

    ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/terminal-notifier

Is it because Sierra doesn't allow to install software to /usr/bin by default?

**Comment by EugenMayer** [comment]
Please just fix you ruby :) This has nothing to do with docker-sync - i neither know why you are using your system ruby and even sudo to install it, but maybe you know that. In that case, please finish what you started :)
