### ISSUE TITLE
Not syncing on last High Sierra 10.13.4

### ISSUE THREAD

**Issue by sergiodebcn** [EugenMayer/docker-sync#567]
### Error/Feature Requestion/Docs
Not syncing on High Sierra 10.13.4

### Docker Info

Containers: 7
 Running: 5
 Paused: 0
 Stopped: 2
Images: 33
Server Version: 18.03.0-ce-rc4
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 2.933GiB
Name: linuxkit-025000000001
ID: FZDO:WQ6M:H3LT:OFRN:VIAR:CTRI:ZWOX:IH4V:N7PC:6UUW:4IAK:S6A3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 58
 Goroutines: 72
 System Time: 2018-04-03T21:31:01.116668272Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

### Sync strategy

default

### your docker-sync.yml

version: "2"

options:
 verbose: true
syncs:
  docker-sync:
    src: '../test'
    sync_excludes: ['.vagrant', '.idea', 'docs', 'deploy', '*scss', '*sass']

### OS
OSX High Sierra 10.13.4

I worked perfectly with version 0.5.6 and High Sierra 10.13.1, I updated osx and gem versions and now docker-sync is not syncing, someone with the same problem? thanks.
I am using Docker Edge working perfectly since two weeks. Not updated

**Comment by michalkleiner** [comment]
18.03.0-ce-rc4 is the problem. You need to go back to stable 17.09.1-ce-mac42.

**Comment by EugenMayer** [comment]
@michalkleiner thank you :)

**Comment by sergiodebcn** [comment]
I think is a good idea, to put somewhere docker recomended version, for new users. Thanks!

**Comment by sergiodebcn** [comment]
Great job, thx
