### ISSUE TITLE
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? on Windows

### ISSUE THREAD

**Issue by zersiax** [EugenMayer/docker-sync#571]
### Error
?

### Docker Driver
? Docker-machine using Hyper-V

### Sync strategy
? (unison)

### your docker-sync.yml
version: "2"
options:
    verbose: true
syncs:
    app-unison-sync: # tip: add -sync and you keep consistent names als a convention
        sync_args: ['-perms=0'] #required for two way sync ie generators, etc
        sync_strategy: 'unison' 
        sync_host_ip: '127.0.0.1' #host ip isn't properly inferred
        sync_excludes: ['.gitignore', '.idea/*','.git/*', '*.coffee', '*.scss', '*.sass','*.log']
        src: './'

### OS
? Windows 10 PRO 1803

This could very easily be user error but I'm trying to use Docker-sync to fix the docker slow performance issues on Win10. I have added the above docker-sync.yml to my project's root, after which I have started our docker environment which in turn mounts the folder that project is in. Subsequently running docker-sync start gives theerror in the issue title. I have made sure the 'without TLS'  is checked in the docker settings panel and exported the environment variable as discussed in the steps for installing docker-sync on WIndows. Not sure what it is I am missing.

**Comment by EugenMayer** [comment]
docker-sync does not support hyper-V or such setups, only WSL based

**Comment by Bryanwuero** [comment]
Guys, i have this problem too docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? 

I have days trying to solve it and nothing I have the new windows spring update version 1803 and I cant solve the problem can't run anything of docker and it keeps saying if the daemon docker running? I have the expose daemon checked and also sharing my C./ disk if anyone knows can help I appreciate it thanks!
