### ISSUE TITLE
Unable to get sync_excludes working with native_osx

### ISSUE THREAD

**Issue by jhoffmann** [EugenMayer/docker-sync#574]
### Error/Feature Requestion/Docs

I'm unable to get docker-sync working with sync_excludes and native_osx.  I've tried '.git', '.*/.git', 'Path .git', and 'Path */.git' and I still see it whenever I start up docker-sync.

What am I missing?

    $ time docker-sync start | tee sync.log
              ok  Starting native_osx for sync sugarinternal-sync
    doing initial sync with unison
    Unison 2.51.2 (ocaml 4.06.1): Contacting server...
    Looking for changes
    Reconciling changes
    Propagating updates
    UNISON 2.51.2 (OCAML 4.06.1) started propagating changes at 15:47:09.87 on 26 Apr 2018
    [BGN] Copying .agignore from /host_sync to /app_sync
    [END] Copying .agignore
    [BGN] Copying .git from /host_sync to /app_sync
    [END] Copying .git

When I examine the container to see if it's actually copying files:

    $ connect code-sync
    bash-4.4# du -sh /app_sync/.git
    345.2M  /app_sync/.git

Currently it's taking 8 minutes to do the initial sync.  The entire code folder is 831M and my app dosn't have git installed, so I'd really like to not sync that much unusable data.

### Docker Driver
d4m

### Sync strategy
native_osx

### your docker-sync.yml

    version: '2'

    options:
      compose-file-path: 'docker-compose-sync.yml'

    syncs:
      code-sync:
        src: '../code'
        sync_excludes: ['Path */.git', 'Path */cache', 'Name *.log']
        sync_userid: '1000'

### OS

OSX 10.13.4

**Comment by EugenMayer** [comment]
Search the open issues and the docs, your exclude expression is wrong
