### ISSUE TITLE
Use project root for sync

### ISSUE THREAD

**Issue by F82nrDE-3** [EugenMayer/docker-sync#592]
### Question
Hi, I wanted to ask if it is possible to use the project directory as source for the sync.

So, generally I want to do this: 
```
volumes:
   - ./:/var/www:nocopy
```
But unfortunately it isn't possible since I don't know what name to use on the declaration:

```
volumes:
  ???:
    external: true
``` 

And how would the docker-sync.yml look. Is there something I have to care about?

### Sync strategy
default

### OS
macOS 10.13.6

**Comment by EugenMayer** [comment]
this is not possible yet
