### ISSUE TITLE
Feature request: docker-sync.yml reference in .env or environment variable

### ISSUE THREAD

**Issue by phoenix-bjoern** [EugenMayer/docker-sync#597]
Right now docker-sync tries to find the configuration file in the current directory and upper directories. However, the root directory is always occupied and shouldn't take more files than necessary and it is annoying to reference the configuration file with the -c option every time.
For docker-compose we use a .env file to reference it's COMPOSE_FILE which is located in one of the lower project directories.
It would be great if we could use the same .env file and/or an environment variable ("export ...") to reference a DOCKER_SYNC_FILE to keep the project root directory clean. This way we could locate the docker-sync.yml anywhere in the projects folder.

**Comment by EugenMayer** [comment]
since docker-compose does not support putting. env into a subfolder, that's what we have to stick too also. you can tell where the docker-compose file is, but the .env file has to be there relatively to it like dotenv is defining it
