### ISSUE TITLE
Error about mapped port - how to update docker-sync?

### ISSUE THREAD

**Issue by elbsurfer** [EugenMayer/docker-sync#600]
Hello,
I just updated docker to 18.06.-ce-mac70 and since then I get this error when starting docker-sync:

`note:  You can also run docker-sync in the background with docker-sync --daemon
          ok  Starting unison for sync sw53-sync-new
          ok  sw53-sync-new container still running, restarting unison in container
     command  docker exec sw53-sync-new supervisorctl restart unison
          ok  starting initial sync of sw53-sync-new
     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' sw53-sync-new
     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' sw53-sync-new
       error  Error getting mapped port, exit code 0
     message  Template parsing error: template: :1:3: executing "" at <index (index .Networ...>: error calling index: index of untyped nil
     command  unison -testserver /app_sync "socket://:"
/Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_strategy/unison.rb:191:in 'block in start_container': Failed to start unison container in time, try to increase max_attempt in your configuration. See https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration for more informations (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_strategy/unison.rb:187:in 'loop'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_strategy/unison.rb:187:in 'start_container'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_strategy/unison.rb:39:in 'run'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_process.rb:87:in 'run'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:100:in 'block in run'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:99:in 'each'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:99:in 'run'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/tasks/stack/stack.thor:47:in 'start'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in 'run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in 'invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in 'dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in 'start'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/bin/docker-sync-stack:15:in '<top (required)>'
	from /usr/local/bin/docker-sync-stack:23:in 'load'
	from /usr/local/bin/docker-sync-stack:23:in '<main>'`

Anybody knows how I can fix this? My idea was now to update docker-sync to it's latest version, but how do I do that? I tried it with:

`brew upgrade eugenmayer/dockersync/unox`

but then I get this message: 

`Error: eugenmayer/dockersync/unox 0.2.0_1 already installed`

Thanks.

**Comment by EugenMayer** [comment]
you just missed any information you have been asked for by the issue template. Why?

**Comment by elbsurfer** [comment]
I'am sorry, I missed the part below the first text.

So I use unison as sync protocol on a mac where 10.12.6 is installed. My docker-sync.yml is this one:

`version: "2"

options:
  verbose: true
syncs:
  sw53-sync-new: # tip: add -sync and you keep consistent names as a convention
    src: './src'
    sync_excludes: ['.git', 'var/cache/*']`

Does this help?

**Comment by EugenMayer** [comment]
closing due to missing informations
