### ISSUE TITLE
Windows: docker-sync >= 0.5.8 unison-fsmonitor installed not using brew

### ISSUE THREAD

**Issue by boris-brtan** [EugenMayer/docker-sync#609]
### Error/Feature Requestion/Docs
Error/Docs
during docker-sync start, there are some prompts that doesn't work and it asks for brew installation 
```
docker-sync start
sh: 1: brew: not found
     warning  You installed unison-fsmonitor (unox) the old legacy way (i.e. not using brew). We need to fix that.
Uninstall legacy unison-fsmonitor (unox)? (y/N) y
     command  sudo rm -f /usr/local/bin/unison-fsmonitor
     warning  Could not find eugenmayer/dockersync/unox. Trying to install it now.
Install eugenmayer/dockersync/unox for you? [y/N] y
     command  apt-get install -y eugenmayer/dockersync/unox
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
       error  shopsys-framework-sync has been configured to sync with unison, but no unison available
       error  Failed to install required package. Please install it manually and try again.
```
Is there way how to install brew in WSL with functional unison-fsmonitor ?

### Docker Driver
Windows docker 18.06.1-ce

### Sync strategy
unison

### your docker-sync.yml
based on [Wiki](https://github.com/EugenMayer/docker-sync/wiki/docker-sync-on-Windows#fyi---an-example-of-a-docker-syncyml-file)
### OS
Windows 10 Pro 1803

**Comment by EugenMayer** [comment]
now brew should not get used in a windows env, thats rather a bug. fsmonitor is a osx only thing AFAIR

Feel free to investigate/PR, usually there is rather less focus on the windows branch of the core team, so if you do want to speed this up / help, i would be happy!

**Comment by boris-brtan** [comment]
> now brew should not get used in a windows env, thats rather a bug. fsmonitor is a osx only thing AFAIR
> 
> Feel free to investigate/PR, usually there is rather less focus on the windows branch of the core team, so if you do want to speed this up / help, i would be happy!

Ok, i will try to get into ruby and maybe i would be able to create some PR. Maybe just here maybe in https://github.com/bcpierce00/unison/

**Comment by Jarzebowsky** [comment]
@EugenMayer so maybe it will be easier to remove support at all for Windows cuz it's unusable at all. In previous job I had it setup and worked like a charm, after migrating to new one it just don't work and return bunch of errors. That's sad 'cause you were only one that worked that good on Docker on Windows...

**Comment by EugenMayer** [comment]
Well @Jarzebowsky what about stepping in and helping, not just expecting me to either fix it or remove it? :)

I do not use windows and i have enough duty with keeping the support up for MacOS which is my main branch - support for windows was experimental and the one implemented opted in with long time support .. well i guess that is no longer the case. Most people seem to go straight from windows to linux due to that issue, but well, that's not an option for all.

All i am saying, i am transparent what i plan to work on, and what i am not. I'am very happy though if people contribute and merging / discussing PR's.

**Comment by boris-brtan** [comment]
That's why i am now trying to get into the problematics and solve the problems for Windows.

**Comment by Jarzebowsky** [comment]
@EugenMayer I would if there is something I'm good at and up to - guess.. I'm not and that's the main point of that I can't contribute, following one is lack of time to even get into it to fix it.

@boris-brtan I'm looking forward for your PR which will make it stunning again.

**Comment by jakubwol** [comment]
It seems to be working fine in version 0.5.7 - I've added a note about it in the Wiki.

**Comment by EugenMayer** [comment]
since like either the OSX detection is broken or something else i changed with 0.5.9 - anybody digged deeper into that ?

**Comment by boris-brtan** [comment]
or it didn't work at all. since old version flushed errors `brew list unox &> /dev/null` like i think it means.
And another thing i tried to use functionality of `DOCKER_SYNC_SKIP_DEPENDENCIES_CHECK` but still it reached somehow the part for checking `ensure_all_for_mac` and problematic `UNISON.ensure`

**Comment by EugenMayer** [comment]
can someone confirm that
`pgrep -q com.docker.hyperkit` is a $? = 0 under windows? i think that is the bug we are hunting after all

**Comment by EugenMayer** [comment]
also please someone with WSL provide the exit codes for

`ps aux | grep com.docker.hyperkit | grep docker-for-mac -q`

and

`ps aux | grep com.docker.hyperkit | grep docker-for-windows -q`

and the output of

`ps aux | grep com.docker.hyperkit`

You can strip any sensible part but please leave all the generic parts in place

**Comment by EugenMayer** [comment]
i ned the exit codes for each.

after each command do `echo $?`

**Comment by boris-brtan** [comment]
WSL
```sh
user@DESKTOP-P99P4BT:/c/Users/user$ ps aux | grep com.docker.hyperkit | grep docker-for-mac -q
user@DESKTOP-P99P4BT:/c/Users/user$ echo $?
1
user@DESKTOP-P99P4BT:/c/Users/user$ ps aux | grep com.docker.hyperkit | grep docker-for-windows -q
user@DESKTOP-P99P4BT:/c/Users/user$ echo $?
1
user@DESKTOP-P99P4BT:/c/Users/user$ ps aux | grep com.docker.hyperkit
user 141  0.0  0.0  14804  1220 pts/0    S    16:32   0:00 grep --color=auto com.docker.hyperkit
user@DESKTOP-P99P4BT:/c/Users/user$ echo $?
0
```

**Comment by EugenMayer** [comment]
could you also test `pgrep -q com.docker.hyperkit`

**Comment by boris-brtan** [comment]
it is 2 because pgrep doesn't have `q` option

**Comment by boris-brtan** [comment]
hi, i think that you dont need to have WSL. It should be the same as to have linux distro, also you are able to do test on travis if you use debian image or ubuntu image with the Dockerfile that install all the tools from the guide.
```
docker run -it debian bash
```
If you want i could create Dockerfile with all of that and you can just run it with docker. It should be the same principle as with docker on mac since there will be docker that connects to docker service.

**Comment by EugenMayer** [comment]
No, that wont work, because the docker-engine is exposed differently under docker-for-windows then the native docker-engine under linux. I understand, that we are talking about a ubuntu running docker, but as under macos, its a virtualized linux kernel and that changes up things a lot, especially on the docker 4 X part.

Generally, docker-4-windows is a linux running docker - no doubt. 
But its not a "linux running docker"

If you can test this and create a dockerfile where you see the same process structure, process names as under windows WSL, that would be a huge help for sure - but i rather doubt it. Please prove me wrong ! :)

**Comment by boris-brtan** [comment]
sorry for the delay but i needed to do some work on GoogleCloud. This weekend i could hav esome spare time so i will try something like https://travis-ci.org/jborean93/travis-ci-win-ansible/jobs/447023999/config
or if you are beeter in travis configuration please try something on your own.

**Comment by boris-brtan** [comment]
for now you can skip support for windows in new versions, i need some time to learn more about the tools it uses.

**Comment by EugenMayer** [comment]
@boris-brtan thank you for the feedback!

**Comment by Jarzebowsky** [comment]
The best thing would be wait till WSL provide native support of Docker and Docker Compose inside it - which is coming in near future.

**Comment by Jarzebowsky** [comment]
> > The best thing would be wait till WSL provide native support of Docker and Docker Compose inside it - which is coming in near future.
> 
> Interesting, sorry for going off-topic, but can you link the announcement for this? I can't find anything about it.

Sure, here it is 
https://github.com/Microsoft/WSL/issues/2291#issuecomment-438388987

**Comment by zangai** [comment]
I am an Windows developer, and I rely heavily on docker-sync for my development workflow. Therefore I would gladly be able to help with keeping the windows version supported. I am however not yet sure where I should start with looking at this issue.
From the comments on this thread I get the impression that the logic which determines the platform docker-sync runs on was depending on some sort of setting which has been changed now?

**Comment by EugenMayer** [comment]
I think the core issue is, that ds considers WSL to be MacOS and tries to use macOS tools to e. g. install unison. windows should behave like a Linux with WSL in ds, but maybe the Linux detection is faulty and falls back to macOS.. that was basically my last hint

**Comment by boris-brtan** [comment]
could we start with some matrix extension for travis?
to test it on Linux, osx, windows Wsl ?
https://travis-ci.org/boris-brtan/test-travis-os/builds/483328068/config

**Comment by EugenMayer** [comment]
We have those tests already - though they are not working right now (the tests themselfs are broken) https://github.com/EugenMayer/docker-sync/issues/605 .. this could even be related to this issue

**Comment by EugenMayer** [comment]
i just released a 0.5.10-beta1 - could you verify this fixes your issue? https://rubygems.org/gems/docker-sync/versions/0.5.10.pre.beta1

**Comment by jakubwol** [comment]
I've just updated docker-sync from 0.5.7 to 0.5.10-beta1, and it seems the issue is fixed - it started without any problem.

**Comment by ignatiusreza** [comment]
@EugenMayer tested 0.5.11-beta1 with some of the docker-sync-boilerplate in ubuntu, and seems to be working..

**Comment by mferrier** [comment]
Same issue with 0.5.11.pre.beta2:
```
/Users/mferrier/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/docker-sync-0.5.11.pre.beta2/lib/docker-sync/upgrade_check.rb:59:in `check_and_warn': undefined method `check_unison_image' for #<UpdateChecker:0x00007f9d3117a270> (NoMethodError)
Did you mean?  check_rsync_image
```

**Comment by EugenMayer** [comment]
@mferrier could you open a new ticket with your configuration including?
