### ISSUE TITLE
0.5.9 not working on MAC

### ISSUE THREAD

**Issue by matutetandil** [EugenMayer/docker-sync#615]
### Error/Feature Requestion/Docs
Not working. I just installed Docker-sync and the installation process was perfect, all installed. However, when I run docker-sync, I'm getting this error (I replaced my user with xxxx:

docker-sync start
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb:308:in `to_specs': Could not find 'docker-sync' (>= 0) among 7 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/xxxx/.gem/ruby/2.4.0:/usr/local/lib/ruby/gems/2.4.0:/usr/local/Cellar/ruby/2.4.2/lib/ruby/gems/2.4.0', execute `gem env` for more information
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb:320:in `to_spec'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /usr/local/bin/docker-sync:22:in `<main>'

### Docker Driver
irrelevant

### Sync strategy
irrelevant

### OS
OSX

**Comment by EugenMayer** [comment]
You use a scoped ruby and you will need to fix it yourself, whatever your brew setup. Try doctor or whatever - that is not a general issues, of course its working under mac.

If relevant, docker-sync has not been tested under `mojave` so if that is your case, that could take a while.
