### ISSUE TITLE
.yaml file extension not supported?

### ISSUE THREAD

**Issue by ryanpcmcquen** [EugenMayer/docker-sync#617]
According to http://yaml.org/faq.html, the official extension is `.yaml`, but `docker-sync` only supports `.yml`. Are there any plans to support both types of extensions?

**Comment by EugenMayer** [comment]
not until someone patches it :)  There is simply no real reason to put this work into that, i would say

**Comment by ryanpcmcquen** [comment]
I guess just a note on the _Wiki_ would be more worthwhile than work into supporting `.yaml`.

**Comment by EugenMayer** [comment]
sure, if you find a good place for that, just be bold and add this information - there is no sense ine people try and error this

**Comment by ryanpcmcquen** [comment]
Added to the _Usage_ section of the Wiki:
https://github.com/EugenMayer/docker-sync/wiki#usage

**Comment by EugenMayer** [comment]
Thank you sir! Very nice.
