### ISSUE TITLE
Feature request: specify list of sync endpoints as command-line option

### ISSUE THREAD

**Issue by drsharp** [EugenMayer/docker-sync#618]
### Error/Feature Request/Docs

I have multiple sync endpoints and sometimes I want to start up some of them, but not all of them. However, it seems that I can only start up all or just one via the `-n <sync-endpoint-name>` flag as per https://github.com/EugenMayer/docker-sync/wiki/2.1-sync-commands

It would be great if I could pass multiple endpoints to that, or call `-n <endpoint1> -n <endpoint2>` or something like that.

This way I can decide which endpoints to start up and can choose more than one but not all of them.

### Docker Driver
d4m

### Sync strategy
default

### your docker-sync.yml
n/a

### OS
OSX 10.14

**Comment by EugenMayer** [comment]
Thanks for contributing!
