### ISSUE TITLE
Issue starting docker-sync (brew)

### ISSUE THREAD

**Issue by aandrushchenko** [EugenMayer/docker-sync#619]
Hi! Experiencing issue with starting docker-sync. Homebrew won't install required module. 

OS: Mojave 10.14.1

docker-sync start
Error: No such keg: /usr/local/Cellar/unox
     warning  Could not find eugenmayer/dockersync/unox. Trying to install it now.
Install eugenmayer/dockersync/unox for you? [y/N] y
     command  brew install eugenmayer/dockersync/unox
==> Installing unox from eugenmayer/dockersync
==> Downloading https://github.com/hnsl/unox/archive/0.2.0.tar.gz
Already downloaded: /Users/anton/Library/Caches/Homebrew/downloads/b2503a5e57457fddcbad2f236a6df2107425dec0ebbf983599a6429f3a5c2f9c--unox-0.2.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/4e/8b/75469c270ac544265f0020aa7c4ea925c5284b23e445cf3aa8b99f662690/virtualenv-16.1.0.tar.gz
Already downloaded: /Users/anton/Library/Caches/Homebrew/downloads/bda8bcde19a275fd9c84a7ec957593976e90dfd0e461a87f5698f1d2286c0197--virtualenv-16.1.0.tar.gz
==> python2.7 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/unox--homebrew-virtualenv-20181126-41973-18vc7gn/target --install-scripts=/private/tmp/unox--homebrew-virtualenv
Last 15 lines from /Users/anton/Library/Logs/Homebrew/unox/01.python2.7:
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/private/tmp/unox--homebrew-virtualenv-20181126-41973-18vc7gn/target
--install-scripts=/private/tmp/unox--homebrew-virtualenv-20181126-41973-18vc7gn/target/bin
--single-version-externally-managed
--record=installed.txt

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
error in virtualenv setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/eugenmayer/homebrew-dockersync/issues

       error  Failed to install required package. Please install it manually and try again.

**Comment by EugenMayer** [comment]
dupe https://github.com/EugenMayer/homebrew-dockersync/issues/1

**Comment by aandrushchenko** [comment]
Hi! Thanks for pointing to another issue. In my case I had to install python2.7 with home brew:
`brew install python@2`  
It solved the issue.

**Comment by vasiliy0s** [comment]
> Hi! Thanks for pointing to another issue. In my case I had to install python2.7 with home brew:
> `brew install python@2`
> It solved the issue.

Yeah! Thats works after 4 hours of time waste! Thx :)

**Comment by EugenMayer** [comment]
well the time has been wasted because people complain, and as soon as their very own issue has been fixed the effort stops - so everybody has to run through the same look again and again .. including the complain that nobody has yet fixed it generally. Like waiting for a magician i guess

Should be fixed by https://github.com/EugenMayer/homebrew-dockersync/commit/1b80a65cba2c03b602e0dca9fcdbb5404db0bf95

**Comment by vasiliy0s** [comment]
I just not so familiar with python ecosystem, and don't know how homebrew works under the hood. It's not addressed to you, @EugenMayer ) But anyway thanks for so fast reaction, man!!!
