### ISSUE TITLE
Make unison catalog build more transparent

### ISSUE THREAD

**Issue by ohcibi** [EugenMayer/docker-sync#625]
As a successor of #624 this issue is targeted at making the phase where unison builds it's catalog more transparent.

### The problem

Catalog build can take a long time on large project directories. During that phase sync does not work properly and the docker vm is under high cpu load (which might slow down/interfere with other processes)

### A solution

As speeding up the catalog build itself is out of scope or for some situations not even possible an indicator telling that the process is running and wether it is finished or not would be a nice addition to work without problems with docker-sync on larger projects.

**Comment by EugenMayer** [comment]
any progress here?

**Comment by ohcibi** [comment]
Not from my side. I can’t solve this as I don’t know enough about unison and stuff.

**Comment by EugenMayer** [comment]
One month passed passed without any progress, i guess we close this FR for now - anybody who wants to pick this up, just reopen it

**Comment by ohcibi** [comment]
@EugenMayer Ok. I thought the unison catalog build is started explicitly from docker-sync, but apparently its not.

**Comment by EugenMayer** [comment]
No this is an implicit operation unison does to "operate"
