### ISSUE TITLE
docker-sync: command not found

### ISSUE THREAD

**Issue by tiefenb** [EugenMayer/docker-sync#628]
### Error/Feature Requestion/Docs
$ gem install docker-sync

ERROR:  While executing gem ... (Errno::EACCES) Permission denied @ rb_sysopen - /usr/local/lib/ruby/gems/2.5.0/gems/docker-sync-0.5.9/Thorfile

$ sudo gem install docker-sync

Successfully installed docker-sync-0.5.9
Parsing documentation for docker-sync-0.5.9
Done installing documentation for docker-sync after 0 seconds
1 gem installed

$ docker-sync
-bash: docker-sync: command not found

### Docker Driver
d4m

### Sync strategy
native_osx

### your docker-sync.yml
-

### OS
OSX 10.14.2

**Comment by EugenMayer** [comment]
rehash or whatever you have in your shell, the usual binary cache, not ds related

**Comment by OZZlE** [comment]
$ gem install docker-sync
	Fetching: thor-0.20.3.gem (100%)
	ERROR:  While executing gem ... (Gem::FilePermissionError)
	    You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory.
	[16:16:21] /Volumes/Projects/apache/imageresize master $ sudo gem install docker-sync
	Password:
	Fetching: thor-0.20.3.gem (100%)
	ERROR:  While executing gem ... (Gem::FilePermissionError)
	    You don't have write permissions for the /usr/bin directory.
	[16:16:35] /Volumes/Projects/apache/imageresize master $ gem install docker-sync --user-install
	WARNING:  You don't have /Users/oskarmothander/.gem/ruby/2.3.0/bin in your PATH,
		  gem executables will not run.
	Successfully installed thor-0.20.3
	Fetching: gem_update_checker-0.2.0.gem (100%)
	Successfully installed gem_update_checker-0.2.0
	Fetching: backticks-1.0.2.gem (100%)
	...

restarted shell

    $ docker-sync
    -bash: docker-sync: command not found

what gives? :S

**Comment by OZZlE** [comment]
/Users/oskarmothander/.gem/ruby/2.3.0/bin/docker-sync start --config=docker-sync.yml
	          ok  Starting native_osx for sync appcode-native-osx-sync
	/Users/oskarmothander/.gem/ruby/2.3.0/gems/docker-sync-0.5.10/lib/docker-sync/sync_strategy/native_osx.rb:41:in `realpath': No such file or directory @ realpath_rec - /Volumes/Projects/apache/imageresize/app (Errno::ENOENT)
		from /Users/oskarmothander/.gem/ruby/2.3.0/gems/docker-sync-0.5.10/lib/docker-sync/sync_strategy/native_osx.rb:41:in `start_container'
		from /Users/oskarmothander/.gem/ruby/2.3.0/gems/docker-sync-0.5.10/lib/docker-sync/sync_process.rb:105:in `start_container'
		from /Users/oskarmothander/.gem/ruby/2.3.0/gems/docker-sync-0.5.10/lib/docker-sync/sync_manager.rb:103:in `block in start_container'
		from /Users/oskarmothander/.gem/ruby/2.3.0/gems/docker-sync-0.5.10/lib/docker-sync/sync_manager.rb:102:in `each'
		from /Users/oskarmothander/.gem/ruby/2.3.0/gems/docker-sync-0.5.10/lib/docker-sync/sync_manager.rb:102:in `start_container'
		from /Users/oskarmothander/.gem/ruby/2.3.0/gems/docker-sync-0.5.10/tasks/sync/sync.thor:163:in `daemonize'
		from /Users/oskarmothander/.gem/ruby/2.3.0/gems/docker-sync-0.5.10/tasks/sync/sync.thor:47:in `start'
		from /Users/oskarmothander/.gem/ruby/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
		from /Users/oskarmothander/.gem/ruby/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
		from /Users/oskarmothander/.gem/ruby/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
		from /Users/oskarmothander/.gem/ruby/2.3.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
		from /Users/oskarmothander/.gem/ruby/2.3.0/gems/docker-sync-0.5.10/bin/docker-sync:14:in `<top (required)>'
		from /Users/oskarmothander/.gem/ruby/2.3.0/bin/docker-sync:23:in `load'
		from /Users/oskarmothander/.gem/ruby/2.3.0/bin/docker-sync:23:in `<main>'

**Comment by OZZlE** [comment]
where does "app" come from?

**Comment by OZZlE** [comment]
works if I do:

    echo 'export PATH="/Users/[MY_USER]/.gem/ruby/2.3.0/bin:$PATH"' >> ~/.bash_profile
    source ~/.bash_profile

**Comment by jaryroxas** [comment]
if you are on a mac dont use sudo, instead add --user-install

gem install docker-sync --user-install

**Comment by yosoyfunes** [comment]
It worked for me

```
sudo gem install docker-sync -n /usr/local/bin
```

**Comment by nomedia** [comment]
> It worked for me
> 
> ```
> sudo gem install docker-sync -n /usr/local/bin
> ```

work for me too

**Comment by raghuiamsingh** [comment]
this is what works for me (also a recommended solution)
`gem install docker-sync --user-install -n /usr/local/bin`
