### ISSUE TITLE
Wrong link to ocaml

### ISSUE THREAD

**Issue by kristl78** [EugenMayer/docker-sync#632]
### Error Docs
https://github.com/EugenMayer/docker-sync/wiki/docker-sync-on-Windows#9-compile-and-install-ocaml

You have to change this line:
Before doing this please check out first the **_Unison_** release changelog and ensure that the OCaml version that you are going to install is compatible. **_(https://github.com/bcpierce00/unison/releases)_**

To this:
Before doing this please check out first the **_OCaml_** release changelog and ensure that the OCaml version that you are going to install is compatible. **_(https://github.com/ocaml/ocaml/releases)_**

**Comment by EugenMayer** [comment]
@kristl78 ah, i see - be bold, change it in the wiki. Be a contributor and thank you a lot for pointing that out!

**Comment by EugenMayer** [comment]
@kristl78 you might have misunderstood me - i wanted you to be bold and change the wiki page to your suggestion. Just do it :)

**Comment by kristl78** [comment]
@EugenMayer: Ah!!! Sorry... I did it! :-)

**Comment by EugenMayer** [comment]
great! :)

**Comment by kristl78** [comment]
We are so thankful for this amazing repo!   
  

  
Thank you a lot for this great work!   
  

  
Best regards,   
  
Kristina   
  
  
  

  
  
  
  
  
>
