### ISSUE TITLE
unox checking always failed on 0.5.10

### ISSUE THREAD

**Issue by donnykurnia** [EugenMayer/docker-sync#635]
!!!! Important hint !!!!!

> Please do not create issues for [docker](https://docs.docker.com/) or [docker-compose](https://docs.docker.com/compose/reference) related questions. Ensure you understand the tools properly and consult their documentation first. Please understand what [docker volumes](https://docs.docker.com/engine/admin/volumes/volumes/) / [docker-compose volumes](https://docs.docker.com/compose/compose-file/compose-file-v2/#specifying-byte-values)

> Please be sure to have a look at our [documentation](https://github.com/EugenMayer/docker-sync/wiki) too, especially [configuration](https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration) and our starting point the [boilerplate](https://github.com/EugenMayer/docker-sync-boilerplate)

### Error/Feature Requestion/Docs
Error

### Docker Driver
docker-machine+vbox

### Sync strategy
unison

### OS
OSX

In the version `0.5.10` of docker-sync, there are checking whether unox is installed via brew or not. But whenever I run docker-sync, it will complaint 

```
     warning  Could not find eugenmayer/dockersync/unox. Trying to install it now.
```

or after I do

```
brew reinstall unox
```

now it complaint

```
     warning  You installed unison-fsmonitor (unox) the old legacy way (i.e. not using brew). We need to fix that.
```

When I check the history, I saw this commit:
https://github.com/EugenMayer/docker-sync/commit/cbf2758567e834b5e188f0ba5974e0a973ce10ab

What bugging me is that brew checking should only affect mac user, so the checking condition should be

`@available = Environment.mac? && (defined?(Bundler) ? Bundler.clean_system(cmd) : system(cmd))`

I try this in my macbook and now docker-sync can run.

I'll add new pull request for this.

**Comment by cybrox** [comment]
On OSX, this just causes an endless loop.

```
docker-sync start
     warning  Could not find eugenmayer/dockersync/unox. Trying to install it now.
Install eugenmayer/dockersync/unox for you? [y/N] y
     command  brew install eugenmayer/dockersync/unox
Warning: eugenmayer/dockersync/unox 0.2.0_1 is already installed and up-to-date
To reinstall 0.2.0_1, run `brew reinstall unox`
     warning  Could not find eugenmayer/dockersync/unox. Trying to install it now.
Install eugenmayer/dockersync/unox for you? [y/N] ...
```

I've downgraded to `0.5.9` for now.

**Comment by EugenMayer** [comment]
@cybrox what is "this" - this PR or vaniall 0.5.10?

**Comment by argent-smith** [comment]
Hi. Got the same behaviour.

```
⟩ docker-sync stop; docker-sync start --foreground
     warning  Could not find eugenmayer/dockersync/unox. Trying to install it now.
Install eugenmayer/dockersync/unox for you? [y/N] y
     command  brew install eugenmayer/dockersync/unox
Warning: eugenmayer/dockersync/unox 0.2.0_1 is already installed and up-to-date
To reinstall 0.2.0_1, run `brew reinstall unox`
     warning  Could not find eugenmayer/dockersync/unox. Trying to install it now.
Install eugenmayer/dockersync/unox for you? [y/N] y
     command  brew install eugenmayer/dockersync/unox
Warning: eugenmayer/dockersync/unox 0.2.0_1 is already installed and up-to-date
To reinstall 0.2.0_1, run `brew reinstall unox`
          ok  Stopping sync container appcode-sync
          ok  Stopping sync container appfiles-sync
       note:  Starting in foreground mode
     warning  Could not find eugenmayer/dockersync/unox. Trying to install it now.
Install eugenmayer/dockersync/unox for you? [y/N] y
     command  brew install eugenmayer/dockersync/unox
Warning: eugenmayer/dockersync/unox 0.2.0_1 is already installed and up-to-date
To reinstall 0.2.0_1, run `brew reinstall unox`
     warning  Could not find eugenmayer/dockersync/unox. Trying to install it now.
Install eugenmayer/dockersync/unox for you? [y/N] y
     command  brew install eugenmayer/dockersync/unox
Warning: eugenmayer/dockersync/unox 0.2.0_1 is already installed and up-to-date
To reinstall 0.2.0_1, run `brew reinstall unox`
...
```

**Comment by GGolovenko** [comment]
I've got the same bug.

**Comment by akinobu-suzuki** [comment]
I've got the same bug.

**Comment by EugenMayer** [comment]
we tried to fix it with the 0.5.11-beta version. 
Please manually install it and report back if it gets fixed, thanks!

**Comment by petrmatulik** [comment]
0.5.11-beta is working for me and fixed it. Thanks so much!

**Comment by EugenMayer** [comment]
@petrmatulik are you running windows or linux?

**Comment by petrmatulik** [comment]
I'm running on Mac. But after this update, changed files don't sync automatically. After every change, I must run docker-sync sync. Sorry for the late answer.

**Comment by exotec** [comment]
How do I install the GIT Version?

**Comment by EugenMayer** [comment]
@exotec 

```
gem uninstall docker-sync
gem install docker-sync -v 0.5.11-beta3
```

@petrmatulik please restart your Mac once please (yes i mean that) and try again. If it happens again, please use the boilerplate https://github.com/EugenMayer/docker-sync-boilerplate in the "default" folder and try if it syncs there. If not even the latter works, please open a new issue describing your case. Thanks!

**Comment by exotec** [comment]
@EugenMayer thanks a lot! the beta installation is now running. I'm very new with docker, can you tell me please why the sync process only works for me with:
`$ docker-sync start`

my docker-compose.yml:
```
version: '2'

services:
  db:
    image: mariadb:latest
    command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    volumes:
      - db-native-osx-sync:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: typo3
      MYSQL_USER: typo3
      MYSQL_PASSWORD: typo3

  typo3:
    depends_on:
      - db
    image: martinhelmich/typo3:latest
    volumes:
      - typo3-native-osx-sync:/var/www/html/typo3conf:nocopy
    ports:
     - "80:80"
    links:
      - "db:typo3-database"
    restart: always

# that the important thing
volumes:
  db-native-osx-sync:
    external: true
  typo3-native-osx-sync:
    external: true

```
my docker-sync.yml:
```
version: "2"

options:
  verbose: true

syncs:
  typo3-native-osx-sync:
    src: './typo3conf'
    sync_userid: '1000'
  db-native-osx-sync:
    src: './mysql'
```

my commands:
1. $ docker-sync start
says at the end:
```
     success  Unison server started
     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' typo3-native-osx-sync
     command  unison '/Users/weber/Desktop/docker-tests/typo3/typo3conf' -auto -batch -prefer '/Users/weber/Desktop/docker-tests/typo3/typo3conf' -copyonconflict socket://192.168.99.100:32787
          ok  Synced /Users/weber/Desktop/docker-tests/typo3/typo3conf
      output  
     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' db-native-osx-sync
     command  unison '/Users/weber/Desktop/docker-tests/typo3/mysql' -auto -batch -prefer '/Users/weber/Desktop/docker-tests/typo3/mysql' -copyonconflict socket://192.168.99.100:32788
          ok  Synced /Users/weber/Desktop/docker-tests/typo3/mysql
       utput  | mysql
     success  Starting Docker-Sync in the background
```
2. docker-compose up -d
$ docker-compose up -d
```
Creating network "typo3_default" with the default driver
Creating typo3_db_1 ... done
Creating typo3_typo3_1 ... done
```
I think this looks good, but my folders only syncs when I now run 
`$ docker-sync start`

**Comment by GGolovenko** [comment]
I discovered that unison-fsmonitor symlink is not created on my mac.
I resolved this issue with command:
`brew unlink unox && brew link unox`
After that symlink was created and 0.5.10-beta1 is working fine

I found related issue here: https://github.com/hnsl/unox/issues/24

**Comment by EugenMayer** [comment]
@exotec off-topic, please open a new issue and please consult the wiki before you do so - and the boilerplate.
@exotec thank you for the report. Which OS do you have?
@GGolovenko ah that issue again - well yes, AFAIU link is something the user "uses" or not. It's usually done, but not when the target exists, then you have to enforce it. That is what happened for you. I think this all comes due to brew layout changes or an MacOS upgrade where the old symlink is broken but exists. Maybe the error is also missleading by telling 

`eugenmayer/dockersync/unox` is missing. Maybe we should talk about the expected "location - but this is rather hard to termine. Maybe an additional check to check if it is a broken symlink would help .. you are in for a PR for this? :)
