### ISSUE TITLE
Thoughts: Move tests to Circel.Ci

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-sync#644]
I think its just the better option for us, it has dedicated linux and mac support, where we could do this cross matrix tests fairly well ( AFAIK travis can do mac too? )

I got an OpenSource license for docker-sync for CircleCI, so we would have the full package.
@ignatiusreza any thoughts on that ?

**Comment by ignatiusreza** [comment]
I agree.. CircleCI used to be painful to use, but since the release of CircleCI 2.0, it becomes incredibly easy to use..

**Comment by ostrolucky** [comment]
Posted here because it's kinda related: It looks travis integration with GH is broken in this repo? There is no CI status for new PRs.

**Comment by EugenMayer** [comment]
stale, closing
