### ISSUE TITLE
Allow docker-sync to specify docker-compose.*.yml files 

### ISSUE THREAD

**Issue by AngelAlvarado** [EugenMayer/docker-sync#645]
Hi,

I'd like to use custom docker-compose files with docker-sync. I've learned it's possible to use a production and a dev compose file (docker-compose, docker-compose.dev). However, I have custom compose files for a development environment which I run with docker-compose as `$ docker-compose -f docker-compose.yml -f docker-compose.[app|space|dev].yml`

I read the docs and some issues related to my question but could was not able to understand how to do this.

can I somehow tell docker-stack which compose files to use?

References:

https://github.com/EugenMayer/docker-sync/issues/41
https://github.com/EugenMayer/docker-sync/issues/41
https://docker-sync.readthedocs.io/en/latest/getting-started/configuration.html#docker-compose-dev-yml

**Comment by EugenMayer** [comment]
you can do that, but just wihtout docker-sync-stack .. you rather use `docker-sync start` and then `docker-compoer -f ... -f .. -f .. up`
