### ISSUE TITLE
Feature Request: Allow for explicit OS-independent sync_strategy: 'default'

### ISSUE THREAD

**Issue by cytopia** [EugenMayer/docker-sync#649]
### Feature Requestion
Allow for explicit `sync_strategy: 'default'`

#### Use-case

I want to set a sane OS-independent default value for the `sync_strategy`, that can still be changed by users via `.env`.

So I would add:

`.env`:
```bash
SYNC_STRATEGY=default
```

and in `docker-sync.yml`:
```yml
...
syncs:
  default-sync:
    sync_strategy: '${SYNC_STRATEGY}'
...
```

This way, users could rely on a very sane default and still change `$SYNC_STRATEGY` in their `.env` file which is not under git control.  `docker-sync.yml` on the other side could be under git control and should therefore not be changed by users.

So users could change `.env` and set for example `unison`:

`.env`:
```
SYNC_STRATEGY=unison
```
This would then allow me to always have the `docker-sync.yml` in git and controlled by the repository and only the `.env` is something that the user controls.

#### Current case

Currently in order to use the default sync strategy, the whole `sync_strategy` block must be omitted, therefore the above shown case to move the configuration to the `.env` file would not be possible.

**Comment by EugenMayer** [comment]
I see, that is a really good point, i did not think about the actual override case.

**Comment by cytopia** [comment]
@EugenMayer are you still considering to implement the override feature for the use case stated above?

**Comment by EugenMayer** [comment]
Hello @cytopia i'am not working on it myself atm, but i would for sure consider merging a PR for this if it is strict on topic (and does not change defaults )

**Comment by ostrolucky** [comment]
I think Linux users will pretty much always want native strategy. This is why setting sync strategy is currently very contraproductive, because when it's set to eg. rsync, it will apply to Linux hosts as wel. @EugenMayer what do you think about ignoring sync_strategy when native strategy is available?

**Comment by EugenMayer** [comment]
@ostrolucky beside i do not understand the need of not native under linux, i do not want to limit the usage of it either. So while i understand that ignoring it might be an interesting / probably more often implied default, i would, if offered, want to offer an opt-out flag to still apply the strategy. Until that is not in place ( or an idea for that ) - explicit strategy selection should be our default behavior IMHO

**Comment by EugenMayer** [comment]
Any movement on this - i think this could really make sense to a lot of people, helping teams with different OSes all over the place.

**Comment by ostrolucky** [comment]
I'm not using docker-sync myself anymore personally, so no movement from my side

**Comment by EugenMayer** [comment]
closing since there seems to be no interest in implement this

**Comment by cytopia** [comment]
@EugenMayer 
> closing since there seems to be no interest in implement this

I'm interested in having this implemented since 2019. Can u please reopen

**Comment by EugenMayer** [comment]
@cytopia if you want to start working on that, feel free to open a PR and i'am happy to open this issue. 

But mostly this is open for a magic person to pick this up since 3 years. I think this is at least for now unlikely, right
