### ISSUE TITLE
[idea] cli to setup docker-sync.yml

### ISSUE THREAD

**Issue by ChoiByungWook** [EugenMayer/docker-sync#650]
### Error/Feature Requestion/Docs
Right now it seems the best way to setup a repository to use docker-sync is by cloning https://github.com/EugenMayer/docker-sync-boilerplate and modifying it or to create docker-sync.yml file based on the [configuration](https://github.com/EugenMayer/docker-sync/blob/master/example/docker-sync.yml).

I was wondering if maybe it would be possible to generate this docker-sync.yml file or something through cli... such as:

`docker-sync init
`

Just an idea. Cool tool!

**Comment by EugenMayer** [comment]
sure, we had this effort/idea one already, but nobody actually put work into it, so it was disbanded at some point.

generally the idea is great, would you like to tackle this?

**Comment by ChoiByungWook** [comment]
I would love to, however I'm not too sure what legal implications I'm under, as I am employed, if I contribute code to this project.

:(

Still, I would love to see something like this get implemented, as it would be helpful for people starting and also speed up setting up docker-sync in a repository. Can we keep this issue up for now?

**Comment by EugenMayer** [comment]
if you are doing it in the free time, there are no legal issues. if you allowed to work on in in the office hours, then contributions will be all GPL anyway

**Comment by EugenMayer** [comment]
As usual, i keep this issue open for 30 days for someone to start working on it, if anybody desires. 
If nobody has yet picked up the work i expect that the interest or timing just does not fit and close the issue - reopen it anytime though, if you want to start working on that.

**Comment by EugenMayer** [comment]
30 days passed and we had no further progress here. I close this issue for now - should anybody continue to work on this, i would love to reopen it anytime.
