### ISSUE TITLE
[question] ability to sync multiple srcs to single container

### ISSUE THREAD

**Issue by ChoiByungWook** [EugenMayer/docker-sync#651]
### Error/Feature Requestion/Docs
I have two code srcs that I want synced in the same container. It seems I can only specify a single src for my docker-sync.yml to look into. Right now my directory looks something like...

/workspace
 -/repo1
  -/docker-sync.yml
  -/src
 -/repo2
  -/src

The container that is generated from repo1 uses code from both repo1 and repo2. One approach to enable this from my end is to make the src -> workspace, however I feel that is wrong especially because of the amount of excludes I would have to add.

I tried looking in the issues and couldn't find one, so apologies if someone already had this question.

What is the general guidance here? Is there something similar to sync_excludes, however it is sync_includes?

Thanks!

**Comment by EugenMayer** [comment]
you should be able to use multiple syncs, there should be no limitation to that except that you cannot nest them

**Comment by michalkleiner** [comment]
I'd add that possibly the "architecture" of your folder structure is not ideal for this use case. Where the sources live is one thing, how they are used in the project is another thing — possibly look into symlinks or hardlinks? Would docker-sync work with symlinked files?

**Comment by ChoiByungWook** [comment]
The architecture of this folder structure most likely can't change because in the example above, repo2 would be a library/code that is shared among multiple repos, repo1 being an example.

I don't know if symlinking would be the best thing here.

I think the ideal solution from my point of view is to allow for the docker-sync to take in both repo1/src and repo2/src as the directories to take in sync.

@EugenMayer, what would be the best approach here? Would it be to have multiple sync strategies pointing to the same container? One for repo1/src and one for repo2/src?

Let me know if there is anything I can clarify.

**Comment by michalkleiner** [comment]
Fair enough. As EugenMayer already pointed out, if the folders are not nested, you can have multiple syncs.

**Comment by EugenMayer** [comment]
this one seems to be closed by now?
