### ISSUE TITLE
[question] move DockerSync container contents to my_app container

### ISSUE THREAD

**Issue by ivakyb** [EugenMayer/docker-sync#653]
Architecture of docker-sync is a great idea

![](https://docker-sync.readthedocs.io/en/latest/_images/native_osx.png)

I wanna simplify this arch and transfer DockerSync container contents to my_app container. 

My question is **where should I start from**?

As far as I understand need to 
* install unison and run daemon with proper config in container
* run container with volume mount with `-v`

There should be more cunning..

**Comment by EugenMayer** [comment]
Sorry, i have no idea what the actual question is.

"i want to simplify it" .. "where to start".

I think you have to dig far deeper, understand the whole architecture, cullprints and design decisions before you can aim to simplify it in this regard. And if you happen to find a good way, please let us know for sure.

You start from the docs here, then you go to the d4m docs, docker docs and then read the code, understand OSXFS, unison, inode events vs fsevents and steer you way down to whatever you want to simplify.

**Comment by ivakyb** [comment]
Thank  you for response.

I want to understand why do we need container **app-sync**? Looks like we can run `unison` in **my_app** container.

**Comment by EugenMayer** [comment]
Well then read the code and the docs in the order describe above :)
