### ISSUE TITLE
Docker compose file version

### ISSUE THREAD

**Issue by GJBoth** [EugenMayer/docker-sync#659]
Hi,

I'm using docker on a gpu so I require docker-compose file version 2.3 to use --runtime=nvidia. However, I couldn't use dockers-sync, as it says only version 2 is supported. Using 2.3 in the docker-compose together with 2 for the docker-sync file works though. I couldn't find anything in the documentation; maybe make a note?

**Comment by EugenMayer** [comment]
2.3 should work just fine, your local docker-compose is used anyway - version 3 is not supported

**Comment by GJBoth** [comment]
If I set it to 2.3 in the docker-sync.yml I get an error saying it's not supported...

**Comment by EugenMayer** [comment]
you totally got that one wrong - `docker-sync.yml` version is not the `docker-compose.yml` - so keep the docker-sync.yml is what it is 2 - use 2.3 in `docker-compose.yml`

**Comment by GJBoth** [comment]
That indeed works! I couldn't find anything in the documentation about it and I was hesitant about using two different 'versions' in a single applications, but good to hear that should work. Thanks for the quick help!
