### ISSUE TITLE
Question: NFS

### ISSUE THREAD

**Issue by michalkleiner** [EugenMayer/docker-sync#661]
Hello,

just wanted to ask a quick question — anyone here tried https://github.com/me-io/docker-machine-mac-nfs-mount and could share their results compared to docker-sync?

I understand this is not a forum, but we should review other approaches and learn from them where there's anything to benefit from.

Thanks
MK

**Comment by EugenMayer** [comment]
What we did is https://docker-sync.readthedocs.io/en/latest/miscellaneous/alternatives.html#nfs

So i tested it and compared the performance. You could use the setup instructions / benchmark instructions in https://docker-sync.readthedocs.io/en/latest/miscellaneous/performance.html to test / try yourself

**Comment by michalkleiner** [comment]
Thanks @EugenMayer, will try and test that repo/approach so we can add it to the comparison. If anyone else already has done so, feel free to share your results and insights.
