### ISSUE TITLE
 error  Error getting mapped port, exit code 125 on docker-sync-stack start

### ISSUE THREAD

**Issue by ravijpyadav** [EugenMayer/docker-sync#662]
After setup and create sync files, I'm getting below error, can you please help?

docker: Error response from daemon: driver failed programming external connectivity on endpoint appcode-unison-sync (63cae51b9e3401b869bd620713500dd72fdbee2b0adf56a4f1a75858c76bdf37): Error starting userland proxy: mkdir /port/tcp:127.0.0.1:32807:tcp:172.17.0.2:5000: input/output error.
          ok  starting initial sync of appcode-unison-sync
     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' appcode-unison-sync
     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' appcode-unison-sync
       error  Error getting mapped port, exit code 125
     message  Template parsing error: template: :1:3: executing "" at <index (index .Networ...>: error calling index: index of untyped nil
     command  unison -testserver /app_sync "socket://127.0.0.1:"
Traceback (most recent call last):
        15: from /usr/local/bin/docker-sync-stack:23:in `<main>'
        14: from /usr/local/bin/docker-sync-stack:23:in `load'
        13: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/bin/docker-sync-stack:15:in `<top (required)>'
        12: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        11: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        10: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         9: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         8: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/tasks/stack/stack.thor:46:in `start'
         7: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_manager.rb:110:in `run'
         6: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_manager.rb:110:in `each'
         5: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_manager.rb:111:in `block in run'
         4: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_process.rb:85:in `run'
         3: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_strategy/unison.rb:39:in `run'
         2: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_strategy/unison.rb:211:in `start_container'
         1: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_strategy/unison.rb:211:in `loop'
/var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_strategy/unison.rb:216:in `block in start_container': Failed to start unison container in time, try to increase max_attempt (currently 20) in your configuration. See https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration for more informations (RuntimeError)

**Comment by richardsondx** [comment]
@ravijpyadav did you figured out a solution?
@EugenMayer  How come this ticket was closed?
