### ISSUE TITLE
Support for local Kubernetes cluster

### ISSUE THREAD

**Issue by StalkAlex** [EugenMayer/docker-sync#663]
Is there any way to use Docker-sync with built-in Kubernetes cluster in Docker for Mac? 

It's not a problem to start sync for that project folder, problem is to tell kubernetes to use new named  volume created by docker-sync.

Thanks!

**Comment by EugenMayer** [comment]
This will not be possible by design of k8s and aligns with what you would need for a shared storage in k8s, which cannot be a host folder by design
