### ISSUE TITLE
How to run one service only ?

### ISSUE THREAD

**Issue by MatthD** [EugenMayer/docker-sync#666]
### Error/Feature Requestion/Docs

I am curently facing this:

- I have many services that I need to start in specific order to be sure it's ok ìnstall, start, fixtures`I am using command like `docker-compose run service1`and `docker-composer run service2` 

What is the right way with docker-sync to start only one service inside the cli ? 

### Docker Driver
d4m

### Sync strategy
native_osx

### OS
Mac OS 10.14.5

**Comment by EugenMayer** [comment]
start 'docker-sync start' and then use your docker compose Foo as usual
