### ISSUE TITLE
No initial merge / sync

### ISSUE THREAD

**Issue by hevx** [EugenMayer/docker-sync#678]
Hello,

I put a simple demo webapp in a container and want to access it for development from my host. Inside the container the app is build and running. When introducing docker-sync it seems to behave like a simple bind mount. My external directory is somehow mounted over the directory inside the container and the webapp doesn't run anymore because files and settings are missing. There is for example no vendor dir, that was build during the container build. When I add files they are synced. What I want is, that initially all files are merged into my host directory as well. (My host directory contains the source files without vendor and so on). Of course I'm not really going to sync the vendor directory itself but I take it as example.
When mounting the volumes I tried both with and without ":nocopy"

### Docker Driver
Docker version 19.03.2, build 6a30dfc

### Sync strategy
native_linux and unison both don't work

### OS
Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64 GNU/Linuxversion: 2

### docker-sync.yml
options:
  verbose: true
  max_attempt: 30
syncs:
  drupal-sync:
    src: './drupal'
    sync_strategy: 'unison'

### docker-compose.yml
version: "3.3"

services:
  drupal:
    build:
      context: ./docker/drupal/
    restart: always
    ports:
      - 32080:80
    volumes:
      - drupal-sync:/var/www/html/MYAPP/drupal:nocopy

**Comment by EugenMayer** [comment]
Under linux, you should not use unison. When setup correctly with the default strategy, it is a simple bind mount and is entirely unrelated to docker-sync at all - it's a native bind mount by docker core.

Test this with https://github.com/EugenMayer/docker-sync-boilerplate/tree/master/default

**Comment by hevx** [comment]
Yes, I read that in your doc about native_linux and I tried to overcome this with the unison approach, but even this behaves like a simple bind mount (but I see unison is syncing files). It looks like unison does a bind mount and then uses it's own methods for syncing on top. I tried native_linux as well and it works like a bind mount with the "problem" described.

For clarification, the problem with a bind mount is, that I can't access and work on data that are already built inside the container, as my mounted directory would be mounted over the one inside the container and breaks the application inside. (That's of course normal linux bind mount behavior).

So I wanted to use docker-sync to overcome this problem. I don't see many alternatives to access data inside the container under linux?

It should be possible to put the data on a normal volume and then access the volume from the host. But this means fiddling around with permissions and perhaps more and the docker docu states no non-docker process shouldn't access those data. But anyways perhaps it would be a method that could be implemented in docker-sync to overcome the described problem?

Or are there other methods, my unison config is broken or I'm just not getting it?

**Comment by EugenMayer** [comment]
Sorry this is an entirely docker-sync unrelated issue. Docker-sync has never been designed to do what you just stated - it is not "sync from container to host" rather the other way arround.

You do not start with a "build in the container" which you then sync to your sho
