### ISSUE TITLE
[how to fix] Can't run docker-sync after upgrading to MacOS 10.15 (Catalina)

### ISSUE THREAD

**Issue by moon-deer** [EugenMayer/docker-sync#683]
It's a report and reminder how to fix it for those who will be searching for this issue.
After OSX upgrade you will see that docker-sync start is not working.
Unfortunately I don't remember what was exactly the reason ruby version 2.6 (to be specific: `ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]`) appeared, but the thing is, you will see that : 

### Error
~~ docker-sync start
~~ zsh: /usr/local/bin/docker-sync: bad interpreter: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: no such file or directory

And you will also see that you have 2 versions of ruby, you will try to switch between them and this won't help.

The only thing that helped in my case is to:
uninstall ruby,
then install it again (`\curl -sSL https://get.rvm.io | bash -s stable --ruby`),
then install this specific version `rvm install "ruby-2.3.8"`
make it default `rvm use 2.3`
and reinstall docker-sync `gem install docker-sync`

### Docker Driver
Docker Desktop 2.1.0.3 (38240), the latest version

### Sync strategy
native_osx or unison doesn't matter

### OS
OSX 10.15 (Catalina)

**Comment by GordenZhang** [comment]
It happened to me too!

**Comment by EugenMayer** [comment]
https://github.com/EugenMayer/docker-sync/issues/679

**Comment by EugenMayer** [comment]
if you use system ruby - i cannot help you :)

**Comment by GordenZhang** [comment]
I just want to use this tool, and I'm not a ruby developer :(

**Comment by EugenMayer** [comment]
Sorry, this is controlling your development environment, not being a ruby developer. Following the macOS best practices, homebrew and such does not make you a ruby developer, it helps you avoiding issues.

Do not touch system ruby/system python is a golden macOS rule.

You can do it with docker-sync, but do not expect any troubleshooting especially after doing a major OS update.

**Comment by GordenZhang** [comment]
I can solve the ruby version problem, but I don't think it's a good way to use a tool.
I build a docker image with unison and inotify-tools,  and it solved my problem.

**Comment by EugenMayer** [comment]
Until you upgrade next time, and the inotify-tools are broken since the headers are missing :)

anyway, glad you solved your issue, be it by using docker-sync or by not using it, whatever works best for you.

**Comment by EugenMayer** [comment]
@jungleran thank you for confirming!

**Comment by daBayrus** [comment]
@moon-deer here's what i did after docker-sync was broken after upgrading to Catalina
```
xcode-select --install
gem install docker-sync
```

**Comment by renanbastos93** [comment]
> @moon-deer here's what i did after docker-sync was broken after upgrading to Catalina
> 
> ```
> xcode-select --install
> gem install docker-sync
> ```

I did only work with these commands
```bash
xcode-select --install
sudo gem install docker-sync -n /usr/local/bin
```

I using MacOS Catalina

**Comment by raghuiamsingh** [comment]
instead of `sudo` the he command should have been 
`gem install docker-sync --user-install -n /usr/local/bin`
