### ISSUE TITLE
Docker lowercase issue since updating mac to catalina

### ISSUE THREAD

**Issue by JuliusThms** [EugenMayer/docker-sync#685]
First of all, thanks for the great tool @EugenMayer!

### Error/Feature Requestion/Docs
```
docker-sync start
          ok  Starting native_osx for sync app-sync2
          ok  app-sync2 container not running
          ok  creating app-sync2 container
          ok  Starting precopy
     precopy  docker run --rm -v "app-sync2:/app_sync" -v "/hiddenRoot:/host_sync" -e HOST_VOLUME=/host_sync -e APP_VOLUME=/app_sync -e TZ=$(basename $(dirname `readlink /etc/localtime`))/$(basename `readlink /etc/localtime`) -e UNISON_SRC="/host_sync" -e UNISON_DEST="/app_sync" -e UNISON_ARGS="-ignore="Path .git" -ignore="BelowPath .git"  -prefer /host_sync -numericids -auto -batch" -e UNISON_WATCH_ARGS="-repeat watch"  --name app-sync2 eugenmayer/unison:2.51.2.1 /usr/local/bin/precopy_appsync
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
```

### Docker Sync

docker-sync --version
0.5.11

Issue exists also with the newer once, tested all.

### Docker Driver
Docker version 19.03.2, build 6a30dfc

### OS
Mac Catalina

**Comment by EugenMayer** [comment]
Did you maybe pick a case insensitive filesystem?

**Comment by JuliusThms** [comment]
It's APFS with Mac Catalina

**Comment by EugenMayer** [comment]
Case sensitive or not?

**Comment by JuliusThms** [comment]
Sorry, i don't know exactly what's the question

**Comment by EugenMayer** [comment]
Is your filesystem case sensitive or not was, what i was asking

**Comment by JuliusThms** [comment]
Yes, but the mounts a all lowercase; and before Catalina it worked well.

**Comment by EugenMayer** [comment]
Case sensitive is considered to be a fairly bad idea under OSX. I will not actively work on this issue, but you can provide a patch if you desire. This is just an very uncommon usecase.

**Comment by EugenMayer** [comment]
Also please paste your entire configuration so we can review at leas that, thnaks

**Comment by JuliusThms** [comment]
The filesystem configuration comes from OSX and the catalina update. 

docker-compose.yml

php:
      build: ubuntu-php72
      container_name: blub
      environment:
        - PROJECT_DIR=/test
        - PHP_UID=${PROJECTS_ROOT_UID}
        - PHP_GID=${PROJECTS_ROOT_GID}
        - DEBUG=false # true, to have more info from the entry point
      working_dir: /test
      volumes:
        - data:/data:cached
        - app-sync:/test
        - ./ubuntu-php72/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      cap_add:
        - ALL

volumes:
  data:
  app-sync:
    external: true

docker-sync.yml

version: '2'
options:
  verbose: true
syncs:
  app-sync:
    src: '/test'
    sync_args:
      - '-ignore="Path .git"'
      - '-ignore="BelowPath .git"'

**Comment by JuliusThms** [comment]
@EugenMayer 

I tried both case- insensitive and sensitive APFS. 
Both not working. Since the upgrade to Mac Catalina, the data is mounted through /Volumes/.. or /Users/. Is this maybe a problem? (real_path)?

**Comment by JuliusThms** [comment]
@EugenMayer 
Any idea?

**Comment by EugenMayer** [comment]
i do not have Catalina nor i'am planing to install it ATM, since all other Catalina users seem to have no issues right now.

This means, you need to tackle this issue on your own right now. and use the docs and the debugging tools described here to understand your individual issue.

Try to understand if the examples in the boilerplate do work for you: https://github.com/EugenMayer/docker-sync-boilerplate and if yes, you already know this is not a direct docker sync issue, nor an OS issue, it's a complex configuration or different kind of issue.

Maybe this helps

**Comment by EugenMayer** [comment]
@JuliusThms you might test https://github.com/EugenMayer/docker-sync/issues/687#issuecomment-545385827 but i am not sure this is your issue at all, since you are not using the unison strategy

**Comment by JuliusThms** [comment]
@EugenMayer 

Sorry for the late response.
I figured it out. The problem was quite simple, but i didn't see this at the beginning.

The sync_arg where wrong.

`sync_excludes: ['.git', '.idea']
    watch_excludes: ['var/']
    #sync_args:
    #  - '-ignore="Path .git"'
    #  - '-ignore="BelowPath .git"'`

**Comment by EugenMayer** [comment]
Great, thanks for the feedback

**Comment by JParkinson1991** [comment]
Looking at the UNISON_ARGS environment variable passed in the docker build command it seems like this could be a problem with escaping double quotes in the sync args.

A very simple fix could be to replace these with single quotes when building the docker run command.

@EugenMayer what do you think? Also can you point me to the file that handles building this command?

**Comment by EugenMayer** [comment]
Since the cmd is passed several levels, all quote types are used and it is the usual quote escaping "hell" - there is yet no way to fix this even more, we would need to remove bash and use a proper implementation using go for those arg tunneling

**Comment by JuliusThms** [comment]
@JParkinson1991 
The weird thing is, before i upgraded to Catalina, the configuration worked.
That's why i didn't check it.

**Comment by JParkinson1991** [comment]
@JuliusThms 
Digging around this this morning (i am on Catalina) and it seems the error, is nothing to do with the actual casing of the command, it is just a generic (despite being specific in the wrong places) error thrown when docker cannot parse a run command.

I have implemented some changes locally that escapes any double quotes _"_ in the recieved sync arguments that appears to be fixing the problem! Check out my these logs

```
# docker-sync.yml
# # # # 

version: '2'

options:
    compose-file-path: 'docker-compose.yml'
    compose-dev-file-path: 'docker-compose.override.yml'
    project_root: config_path

syncs:
    app-sync:
        monit_enable: true
        notify_terminal: true
        src: './app'
        sync_userid: 82
        verbose: true
        sync_args:
            - '-ignore="Path .git"'
            - '-ignore="BelowPath .git"'
```

```
# Pre Patch (nothing escaped)
# # # # 

          ok  Starting native_osx for sync app-sync
          ok  app-sync container not running
          ok  creating app-sync container
          ok  Starting precopy
     precopy  docker run --rm -v "app-sync:/app_sync" -v "/app:/host_sync" -e HOST_VOLUME=/host_sync -e APP_VOLUME=/app_sync -e TZ=$(basename $(dirname `readlink /etc/localtime`))/$(basename `readlink /etc/localtime`) -e UNISON_SRC="/host_sync" -e UNISON_DEST="/app_sync" -e UNISON_ARGS="-ignore="Path .git" -ignore="BelowPath .git"  -prefer /host_sync -numericids -auto -batch" -e UNISON_WATCH_ARGS="-repeat watch" -e OWNER_UID="82" -e MONIT_ENABLE="true"  --name app-sync eugenmayer/unison:2.51.2.1 /usr/local/bin/precopy_appsync
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
Traceback (most recent call last):
        13: from /usr/local/bin/docker-sync:23:in `<main>'
        12: from /usr/local/bin/docker-sync:23:in `load'
        11: from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.5.11/bin/docker-sync:14:in `<top (required)>'
        10: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
         9: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
         8: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         7: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         6: from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.5.11/tasks/sync/sync.thor:47:in `start'
         5: from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.5.11/tasks/sync/sync.thor:163:in `daemonize'
         4: from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_manager.rb:102:in `start_container'
         3: from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_manager.rb:102:in `each'
         2: from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_manager.rb:103:in `block in start_container'
         1: from /Library/Ruby/Gems/2.6.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_process.rb:105:in `start_container'
/Library/Ruby/Gems/2.6.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_strategy/native_osx.rb:98:in `start_container': Precopy failed (RuntimeError)
```

```
# Post patch (escaped sync_args)
# # # # 

          ok  Starting native_osx for sync app-sync
          ok  app-sync container not running
          ok  creating app-sync container
          ok  Starting precopy
     precopy  docker run --rm -v "app-sync:/app_sync" -v "/app:/host_sync" -e HOST_VOLUME=/host_sync -e APP_VOLUME=/app_sync -e TZ=$(basename $(dirname `readlink /etc/localtime`))/$(basename `readlink /etc/localtime`) -e UNISON_SRC="/host_sync" -e UNISON_DEST="/app_sync" -e UNISON_ARGS="-ignore=\"Path .git\" -ignore=\"BelowPath .git\"  -prefer /host_sync -numericids -auto -batch" -e UNISON_WATCH_ARGS="-repeat watch" -e OWNER_UID="82" -e MONIT_ENABLE="true"  --name app-sync eugenmayer/unison:2.51.2.1 /usr/local/bin/precopy_appsync
doing initial sync with unison
Unison 2.51.2 (ocaml 4.06.1): Contacting server...
Looking for changes
Reconciling changes
Propagating updates
UNISON 2.51.2 (OCAML 4.06.1) started propagating changes at 09:04:46.12 on 24 Oct 2019
[BGN] Copying autoload.php from /host_sync to /app_sync
[END] Copying autoload.php
# trimmed
UNISON 2.51.2 (OCAML 4.06.1) finished propagating changes at 09:05:51.18 on 24 Oct 2019
Saving synchronizer state
Synchronization complete at 09:05:51  (8 items transferred, 0 skipped, 0 failed)
chown ing file to uid 82
real    2m 29.57s
user    0m 3.69s
sys     0m 10.10s
          ok  Starting container
     command  docker run -d -v "app-sync:/app_sync" -v "/app:/host_sync" -e HOST_VOLUME=/host_sync -e APP_VOLUME=/app_sync -e TZ=$(basename $(dirname `readlink /etc/localtime`))/$(basename `readlink /etc/localtime`) -e UNISON_SRC="/host_sync" -e UNISON_DEST="/app_sync" -e UNISON_ARGS="-ignore=\"Path .git\" -ignore=\"BelowPath .git\"  -prefer /host_sync -numericids -auto -batch" -e UNISON_WATCH_ARGS="-repeat watch" -e OWNER_UID="82" -e MONIT_ENABLE="true"  --name app-sync eugenmayer/unison:2.51.2.1
50fb46ac3f5e4513d97201870b1716d9aa1f6c7c94775dad1ad2d4b966ee7d55
          ok  starting initial sync of app-sync
     success  Sync container started
     success  Starting Docker-Sync in the background
```

@EugenMayer 
Fixes are available in the following commits
https://github.com/JParkinson1991/docker-sync/commit/2c6d4daf3c36c7e6b0c0297e8dcce8e1c2280d98
https://github.com/JParkinson1991/docker-sync/commit/b2851d23674d28b2d27c33fce281ec60c0aaade3

I still need to look at the rsync strategy, few questions querries etc so wont commit now

I think that [rsync.rb#L61](https://github.com/JParkinson1991/docker-sync/blob/2c6d4daf3c36c7e6b0c0297e8dcce8e1c2280d98/lib/docker-sync/sync_strategy/rsync.rb#L61) needs changing to
```
args = @options['sync_excludes'].map { |pattern| "--exclude='#{pattern.to_s.gsub "'", "\'"}'" } + args
```

There is also [rsync.rb#L64](https://github.com/JParkinson1991/docker-sync/blob/2c6d4daf3c36c7e6b0c0297e8dcce8e1c2280d98/lib/docker-sync/sync_strategy/rsync.rb#L64)
Im not a ruby developer by any means but assume this needs to be checked if it is array and then escaped as well. Some pointers on this would be appreciated as syntax wise ive got no idea!
