### ISSUE TITLE
nginx-proxy mount doesn't work with docker-sync

### ISSUE THREAD

**Issue by iskren-dimov** [EugenMayer/docker-sync#690]
### Error/Feature Requestion/Docs
I would like to use [nginx-proxy](https://github.com/jwilder/nginx-proxy) with docker-sync, but in order to do so I need to do the following mount:
/var/run/docker.sock:/tmp/docker.sock:ro

When I do the mounting the nginx-proxy container still doesn't "see" the file mounted file. Since this is a file being mounted, not a directory, probably it's not handled properly.

Any recommendations are welcome.

### Docker Driver
Docker for Mac

### Sync strategy
native_osx

### your docker-sync.yml
syncs:
  nginx-sync:
    notify_terminal: true
    sync_strategy: 'native_osx'
    src: '/var/run/docker.sock'

### OS
macOS Catalina 10.15

**Comment by EugenMayer** [comment]
Docker-sync is a sync, not a mount. You cannot mount a socket this way and it was never designed to do so. Use volume mounts for that

**Comment by EugenMayer** [comment]
Closed due to timeout
