### ISSUE TITLE
docker-sync start when already started raises an exception

### ISSUE THREAD

**Issue by anlek** [EugenMayer/docker-sync#695]
### Error
When you run `docker-sync start` and the sync is already running, you get an error:
```
tasks/sync/sync.thor:159:in `daemonize': undefined method `empty?' for nil:NilClass (NoMethodError)
```

![image](https://user-images.githubusercontent.com/11052/68409526-34ecbf00-0155-11ea-88d0-cc7473350077.png)

In the earlier version, if you called `docker-sync start` when it was already running, it would respond with **"Sync already running"** (or something like that).

### docker-sync version
0.5.13

### Docker Driver
N/A

### Sync strategy
N/A

### your docker-sync.yml
N/A

### OS
MacOS 10.14.6

**Comment by martmull** [comment]
I have got the same error since this morning

**Comment by dimonixx** [comment]
Me too

**Comment by Maxooo** [comment]
Same behavior here after the Mac OSX Catalina (`10.15.1` - build `19B88`) update.

**Comment by Deconstrained** [comment]
I am convinced I have found the cause of the issue,

The value is expected to default to an empty string (ostensibly) but it's coming through as nil for whatever reason.

PR #698 addresses this by explicitly setting a default.

**Comment by EugenMayer** [comment]
This makes pretty much sense -this was introduced in the last release and we forgot to care about the proper defaults. Thanks for your effortT

**Comment by Maxooo** [comment]
Thank you @Deconstrained for your work and @EugenMayer for the new `v0.5.14` version which works perfectly now. Your investment in this project is well appreciated and makes us win so much time with Docker on Mac every-day. 🙏

**Comment by EugenMayer** [comment]
The main driving force is the community right now, I just take time to coordinate / stuff together. So I forward all the credits to you gents and lads :)
