### ISSUE TITLE
Reference to Wrong Changelog During self-update

### ISSUE THREAD

**Issue by jonmchan** [EugenMayer/docker-sync#699]
https://github.com/EugenMayer/docker-sync/wiki/5.-Changelog

### Error/Feature Requestion/Docs
When allow docker-sync-stack to update itself, the following message is presented:
```
Gems updated: docker-sync
     success  Successfully updated, please restart docker-sync and check the changelog at https://github.com/EugenMayer/docker-sync/wiki/5.-Changelog
```

The wiki is out of date and tells you to go to https://docker-sync.readthedocs.io/en/latest/ and you go to the changelog there at https://docker-sync.readthedocs.io/en/latest/miscellaneous/changelog.html to be only told to go to yet another place - https://github.com/EugenMayer/docker-sync/releases... 

Suggestion: just make the message state to go to:

```
https://github.com/EugenMayer/docker-sync/releases
```

not:
```
https://github.com/EugenMayer/docker-sync/wiki/5.-Changelog
```

**Comment by EugenMayer** [comment]
Yeah sorry .. as time goes by... makes a lot of sense.
