### ISSUE TITLE
native_osx sync not working

### ISSUE THREAD

**Issue by x0rzkov** [EugenMayer/docker-sync#701]
Hi,

Hope you are all well !

I have an issue with docker-sync and docker-compose; I would like to edit prestashop's files from a docker volume but it does not sync in both ways. I get files locally from the volume **app** but no way to update the docker volume if I edit any files locally.

Here is the repository:
https://github.com/x0rzkov/docker-prestashop1.7.x-php7-fpm

To reproduce the issue:
```bash
docker-compose up -d
docker-sync start
touch ./htdocs/index.php
```

Maybe I am getting something wrong, so thanks in advance for your insights and inputs about that problem.

Cheers,
X

**Comment by EugenMayer** [comment]
this is the wrong file https://github.com/x0rzkov/docker-prestashop1.7.x-php7-fpm/blob/master/docker-sync.yml#L5

**Comment by x0rzkov** [comment]
still not working, I pushed the changes ^^

**Comment by EugenMayer** [comment]
Please use https://github.com/EugenMayer/docker-sync-boilerplate and understand how the configuration works, work from there to adjust to your case

**Comment by EugenMayer** [comment]
I would also invite you to read https://docker-sync.readthedocs.io/en/latest/ , very much https://docker-sync.readthedocs.io/en/latest/getting-started/configuration.html this one.

**Comment by x0rzkov** [comment]
after reading it, still not working :-(

is there a limit to the number of files to watch ?

**Comment by letrungkien** [comment]
@x0rzkov 
Maybe try to change this from `app` to `app-sync` and see if it's working...
https://github.com/x0rzkov/docker-prestashop1.7.x-hidden-service/blob/master/docker-sync.yml#L10

> ensure this name is unique and does not match your other container names

**Comment by x0rzkov** [comment]
thanks solved the issue

**Comment by EugenMayer** [comment]
@letrungkien Thank you for helping!

**Comment by letrungkien** [comment]
@EugenMayer happy to help
