### ISSUE TITLE
Sync Loop on log file

### ISSUE THREAD

**Issue by bharendt** [EugenMayer/docker-sync#705]
### Error

When docker sync is started in the background, which is default since 7e324508c12103621af42774f8045479867c7ee8
rsync logs by deault to `./.docker-sync/daemon.log` in the local directory, enabled in d9187726986e1175b24babcfed009af27c5977cd. 

If the local directory or file is synced, this information is logged to that log file, which causes the log file to be synced itself, which causes another write to the log file and so on. This ends up in a "sync loop" which consumes remarkable CPU resources (depending on the size of the log file which is always appended).

This can be avoided by excluding that log file from syncing in the config file (in `sync_excludes`), but it might make sense to exclude it already by default or mention it in the default config.

Related: #505 and #369

### Docker Driver
d4m

### Sync strategy
rsync

### OS
OSX

**Comment by EugenMayer** [comment]
good catch. Providing a exclude default would make a good sense here - are you up for a PR for that little but significant change?

Thank you for the effort!

**Comment by yoseph1998** [comment]
@EugenMayer Created an MR fixing this issue. https://github.com/EugenMayer/docker-sync/pull/816

Can I get some help testing the rsync strategy changes? (if not, it may take me a couple days before I can test that locally)

**Comment by EugenMayer** [comment]
rsync can be tested effortless with https://github.com/EugenMayer/docker-sync-boilerplate/tree/master/rsync

**Comment by yoseph1998** [comment]
Tested rsync locally and found an issue. PR created

**Comment by EugenMayer** [comment]
@yoseph1998 thanks! Merged and going to release with 1.0.2 ASAP
