### ISSUE TITLE
Check os version is >= 1.0

### ISSUE THREAD

**Issue by badosu** [EugenMayer/docker-sync#708]
### Error/Feature Requestion/Docs

If not running `docker-sync` under bundler the gem `os` version is not checked, I had to do quite a bit of digging to find out I had 0.9.6 version installed instead of 1.x and receiving this error:

```
in `freebsd?': undefined method `freebsd?' for OS:Class (NoMethodError)
```

This might not be a priority as I noticed there are no frequent issues of this kind, but I thought of pointing it out as an improvement.

**Comment by EugenMayer** [comment]
Thank you a lot, that is a neat find. Will fix that
