### ISSUE TITLE
How does native_osx work with OSXFS and is still native speed fast?

### ISSUE THREAD

**Issue by edwardchen** [EugenMayer/docker-sync#712]
### Error/Feature Requestion/Docs
Hi! I've been looking around the docs to understand how docker-sync is fast even though it still uses OSXFS.

I found this page, but it's been deprecated.
https://github.com/EugenMayer/docker-sync/wiki/How-does-native_osx-work-with-OSXFS-and-is-still-native-speed-fast%3F

I was wondering if you guys could explain this for me. I'm very curious!

**Comment by EugenMayer** [comment]
https://docker-sync.readthedocs.io/en/latest/advanced/how-it-works.html would be your go-to :)
