### ISSUE TITLE
strange behaviour between docker-sync and docker-sync-stack

### ISSUE THREAD

**Issue by chaloum** [EugenMayer/docker-sync#717]
I've got a few containers that are working, Nginx, Drupal and MariaDB,  all good

I've got my code as in a folder on my Mac which I want to sync.

If I start the containers, all good and the website comes up.

If I run docker sync it goes through the process of syncing and doesn't show any errors.  the website displays but no new or updated files are actually synced

If I down the containers and rerun using docker-sync-stack start, the files are actually sync but I can't access the site and get, directory index of "/var/www/html/" is forbidden,

any ideas what I'm doing wrong?

thanks

**Comment by chaloum** [comment]
after two days of not working, it's working.

**Comment by EugenMayer** [comment]
Stalled
