### ISSUE TITLE
macOS Catalina: Fatal error: Fatal error during unmarshaling (input_value: ill-formed message),

### ISSUE THREAD

**Issue by inPhoenix** [EugenMayer/docker-sync#719]
Following error is happening when the command below is executed:

`docker-sync start`

`Fatal error: Fatal error during unmarshaling (input_value: ill-formed message),
possibly because client and server have been compiled with different versions of the OCaml compiler.
     success  Starting Docker-Sync in the background`

I tried to uninstall and install docker-sync by the following commands but the error remains.
```
gem uninstall docker-sync
gem install docker-sync
docker-sync clean
```

### Version
unison version 2.51.2 (ocaml 4.07.0)
docker-sync version: 0.5.14
### Sync strategy
unison

### OS
MacOS Catalina 10.15.3 (19D76)

**Comment by EugenMayer** [comment]
please see https://github.com/EugenMayer/docker-sync/issues/687

**Comment by inPhoenix** [comment]
Yeah. I looked at it. 
I did the proposed solution: 
`gem update docker-sync`

But the issue remains.

**Comment by EugenMayer** [comment]
This is an unison issue and has nothing to do with docker-sync - docker sync needs you to run unison. The unison you run locally does either not match the remote or it is broken by itself during the upgrade.

Also see https://github.com/EugenMayer/docker-image-unison#usage how to compile against your own ocalm version, if you need to.

do the usual brew prune magic, uninstall un/ install unison, check the used local ocalm, check against the remote one and the act according your needs :)
