### ISSUE TITLE
add ruby 2.0 dependency

### ISSUE THREAD

**Issue by fibigerg** [EugenMayer/docker-sync#72]
I am trying to start the boilerplate project from here https://github.com/EugenMayer/docker-sync-boilerplate

`docker-sync-stack start
/Library/Ruby/Gems/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:105:in `private': nil is not a symbol (TypeError)
	from /Library/Ruby/Gems/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:105:in `<class:Mapper>'
	from /Library/Ruby/Gems/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:5:in `<module:Compose>'
	from /Library/Ruby/Gems/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:2:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose.rb:10:in `require_relative'
	from /Library/Ruby/Gems/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose.rb:10:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.15/tasks/stack/stack.thor:5:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.15/bin/docker-sync-stack:23:in `load'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.15/bin/docker-sync-stack:23:in `block in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.15/bin/docker-sync-stack:21:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.15/bin/docker-sync-stack:21:in `<top (required)>'
	from /usr/local/bin/docker-sync-stack:23:in `load'
	from /usr/local/bin/docker-sync-stack:23:in `<main>'`

Docker for Mac: version: win-beta-v1.12.0-rc5-beta21-68-g5b59d37
OS X: version 10.11.3 (build: 15D21)
logs: /tmp/0D3FC0FD-7C1E-4CF5-9BE7-AA033B364868/20160731-124903.tar.gz
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux

Thanks for help!

**Comment by fibigerg** [comment]
Oh, sorry for duplicate.

Can you add dependency on docker-compose v0.8.4 with Ruby 2.0 support? (see https://github.com/xeger/docker-compose/issues/34)

Thanks

**Comment by EugenMayer** [comment]
yes this is needed, sorry i missed that the last time. Thanks for the hint once again

**Comment by EugenMayer** [comment]
fixed
