### ISSUE TITLE
Update `thor` dependency to 1.0 stable

### ISSUE THREAD

**Issue by Fire-** [EugenMayer/docker-sync#720]
Hi friends,

It looks like docker-sync is currently using a pre-1.0 version of [`thor`](/erikhuda/thor), which is incompatible with other development-centric projects like [`solargraph`](/castwide/solargraph).

Could you look into updating the dependency?

```
    docker-sync (~> 0.5.14) was resolved to 0.5.14, which depends on
      thor (>= 0.20.0, ~> 0.20)

    solargraph (~> 0.38) was resolved to 0.38.5, which depends on
      thor (~> 1.0)
```

**Comment by EugenMayer** [comment]
We should be able to do this without bigger issues, yes

**Comment by EugenMayer** [comment]
thor has been upgraded
