### ISSUE TITLE
docker-sync clean can't delete volume if they are still in use.

### ISSUE THREAD

**Issue by gagarine** [EugenMayer/docker-sync#73]
If the docker-sync's volume are still attached to a containers (even stooped), it will not remove those volume:

```
➜  git:(dev) ✗ docker-sync clean
Error response from daemon: No such container: code-sync
Error response from daemon: No such container: code-sync
Error response from daemon: Unable to remove volume, volume still in use: remove code-sync:
volume is in use - [0bf8bf2d470b484fd736cd245134bf75e294bd5eb664625688f649a57d54533c,
a266be7316732935631a3abc834cdf58e438385ff8fd6f201237a23a19a18109]
  success  Finished cleanup. Removed stopped, removed sync container and removed there volumes
```

I guess this is a safeguard, but what are the use cases as you should still have your files on your local file system.

Perhaps we can add a --force flag. Or a confirmation dialogue can be the default behavior:

```
➜  git:(dev) ✗ docker-sync clean --force
Volume still in use - [0bf8bf2d470b484fd736cd245134bf75e294bd5eb664625688f649a57d54533c,
a266be7316732935631a3abc834cdf58e438385ff8fd6f201237a23a19a18109]

Are you sure you want to delete those volume (y/n): 
```

**Comment by EugenMayer** [comment]
this is not a docker-sync issue, its how docker works. You cannot delete volumes if contaieners are  running using them, thats just not possibe - can implement this

**Comment by gagarine** [comment]
Ok. Thanks for your reply.

**Comment by baohx2000** [comment]
Just as a hint for others who run into this, even if the container is no longer running, it might still be linked to the volume, so you will have to `docker rm {container}` on all of the ones linked. You can then safely `docker-sync clean` and start everything up again.
