### ISSUE TITLE
Travis not run for PRs

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-sync#735]
Not sure why this happens yet

**Comment by EugenMayer** [comment]
@ostrolucky could you, in the meantime, fix the current issue in the master branch being a regression because we removed memorizing? https://travis-ci.org/github/EugenMayer/docker-sync/jobs/679675774#L400

I will try get PR building up and running

**Comment by EugenMayer** [comment]
PRs are activates already .. odd 
![DeepinScreenshot_select-area_20200426131352](https://user-images.githubusercontent.com/136934/80305862-e0e79c80-87bf-11ea-9de8-166d3625b6b4.png)

**Comment by EugenMayer** [comment]
Actually, it does build https://travis-ci.org/github/EugenMayer/docker-sync/pull_requests it does not decorate?

**Comment by ostrolucky** [comment]
Yeah I know it runs, just status check is missing, which is why I didn't notice previous failures. I'll fix those memoization issues, but locally I have much more failures, as ci setup looks to be optimized for linux hosts only.

**Comment by EugenMayer** [comment]
Ok PR decoration works now, so we are good to go here. Thanks for fixing the memorizing issue right away
