### ISSUE TITLE
Can we ignore a subdirectory of an excluded directory in sync_excludes?

### ISSUE THREAD

**Issue by Kwadz** [EugenMayer/docker-sync#737]
Is it possible to ignore a subdirectory of a directory excluded in `sync_excludes` from being excluded by docker-sync?

For example:

`sync_excludes: ['.git', 'vendor', '!vendor/bin']`

**Comment by EugenMayer** [comment]
https://github.com/EugenMayer/docker-sync/issues/107 should help you, i think the short answer is, apparently not :)

**Comment by Kwadz** [comment]
Thanks @EugenMayer, apparently it should be possible using `ignorenot` in `sync_args`, according to the [_Ignoring Paths_ section of Unison's documentation](https://www.cis.upenn.edu/~bcpierce/unison/download/releases/stable/unison-manual.html#ignore). I didn't test it though.
