### ISSUE TITLE
Feature request: check COMPOSE_FILE when setting default compose-file-path

### ISSUE THREAD

**Issue by patsplat** [EugenMayer/docker-sync#738]
### Feature Request
docker-compose allows the COMPOSE_FILE env to set the default docker-compose file:

https://docs.docker.com/compose/reference/envvars/#compose_file

- Would like docker-sync to check for and respect COMPOSE_FILE while setting the default compose-file-path.
- Would like docker-sync to split COMPOSE_FILE key to handle multiple entries as needed

This new logic would replace this line:

https://github.com/EugenMayer/docker-sync/blob/a982915580910456aabc20c324bd71efd1662d7f/lib/docker-sync/compose.rb#L11

Let me know what you think ;-)

Thanks!

**Comment by patsplat** [comment]
Created https://github.com/EugenMayer/docker-sync/pull/739

**Comment by patsplat** [comment]
Pulling the discussion up from the PR, since it makes more sense here.

- _docker-compose_ allows one to use the `COMPOSE_FILE` env variable to replace the default `docker-compose.yml` with one or more alternatives
- This can be useful in team workflows where the services being developed are not mature enough to be in the base `docker-compose.yml` for all developers

There is similar functionality already in _docker-sync_

- The _docker-sync_ `compose-file-path` and `compose-dev-file-path` provides similar functionality
- If these variables are set, these files are required to exist
- When these variables are set to an environment variable that variable must also exist

I was unable to figure out a way to allow developers to `opt-in` to a new set of services without first asking all developers to update their environments.

Options considered included:
- revising `dotenv` to allow defaults when substituting variables.
  - In this approach, the dev file would be forked on some engineers machines
  - Would lead to some duplication of docker-sync volume config
- using `COMPOSE_FILE` and drop use of `docker-sync-stack`
  - this is what I'm currently doing
  - I miss `docker-sync-stack start`
    - `docker-sync start && docker-compose up` is not so bad
    - is only work for the developers opting in to the new features
- adding support for `COMPOSE_FILE` for `docker-sync-stack`
  - in practice many of my colleagues re already using `COMPOSE_FILE`
  - increasing compatibility between docker-sync and docker-compose seemed worthwhile
  - would let me continue using `docker-sync-stack start`
  - hence this issue and PR

**Comment by patsplat** [comment]
@EugenMayer happy to have the conversation here or on the PR.  Let me know what works best.

**Comment by EugenMayer** [comment]
will be fixed using #795
