### ISSUE TITLE
Starting the stack is way slower since d4m 2.4

### ISSUE THREAD

**Issue by NilsEvers** [EugenMayer/docker-sync#755]
Starting up the stack with `docker-sync-stack start` has become way slower for me since updating docker desktop to version 2.4.

They fixed a lot of performance/cpu consumption issues lately, e.g. an issue caused by too many file events.
Maybe some of these changes are related.

Is anyone else experiencing the slower startup?

### Docker Driver
Docker Desktop Community (d4m) 2.4.00 (48506)

### Sync strategy
native_osx

### OS
macOs Catalina (10.15.6)

**Comment by head1328** [comment]
See https://docs.docker.com/docker-for-mac/release-notes/#docker-desktop-community-2400

Perhaps "Docker Desktop now uses gRPC-FUSE for file sharing by default. ..." causes this issue? Is it a good idea to use docker-sync together with gRPC-FUSE?

**Comment by EugenMayer** [comment]
please try 

```
Docker Desktop now uses gRPC-FUSE for file sharing by default. This uses much less CPU than osxfs, especially when there are lots of file events on the host. To switch back to osxfs, go to Preferences > General and disable gRPC-FUSE.
```

and report if that speeds it up

**Comment by EugenMayer** [comment]
generally, the pro of gRPC-FUSE is less cpu usage - not performance. This means going full native without docker sync should result to less cpu usage, but horrible performace.

But guys please add some benchmark values, it is fast to determine those, see

https://docker-sync.readthedocs.io/en/latest/miscellaneous/performance.html
specifically https://docker-sync.readthedocs.io/en/latest/miscellaneous/performance.html#id5

so run 

```
docker exec -it nativeosx_app-unison_1 time dd if=/dev/zero of=/var/www/test.dat bs=1024 count=100000
```
while you do nothing else 

The reason i cannot do this myself any longer is, i'am no longer using a Mac for development. Doing those benchmarks in the CI will most probably not make any sense

**Comment by NilsEvers** [comment]
Your right! I haven't noticed that gRPC-FUSE was on by default. I mean it is still listed under their experimental features...
With gRPC-FUSE turned off performance is back to normal.

**Comment by metaskills** [comment]
Hey y'all! Hope everyone is well and really appreciate this work. I've been participating on this Docker roadmap issue (https://github.com/docker/roadmap/issues/7) and have been reporting that gRPC-FUSE is incredible slow (and gotten worse) over the past few updates for a basic Rails projects. See benchmarks here. https://github.com/customink/docker-rails-lambda#benchmark

QUESTION: I've been turning off gRPC-FUSE in Docker's preferences lately to allow Docker to run faster for Rails projects. After a few days of pulling my hair out... I noticed that `docker-sync` only works when this is turned on. **Does docker-sync only work with gRPC-FUSE and how can I use it when that experimental feature is turned off?**

**Comment by NilsEvers** [comment]
This is not a docker-sync issue but related to D4M v2.5.0. File events only get picked up, when gRPC FUSE is turned on (https://github.com/docker/for-mac/issues/5046).

Before that, it was the other way around.

Every release breaks something new at the moment.

**Comment by metaskills** [comment]
@NilsEvers Thank you for the comment and knowledge. Also, the sadness... cry/laugh times.

**Comment by metaskills** [comment]
I think I can confirm this bug is still present in v3.0.0

**Comment by qhenkart** [comment]
With gRPC-Fuse on, all services are remounted whenever another service is started or restarted. With my setup, we have so many micro services that the entire system times out because each service causes all of the others to remount.

Let's say I have 2 services both with a watcher and on verbose mode

service #1 starts and is running as expected

now I start service #2, in service #1: I see it detect every single file in the directory get removed before it was added again causing the watcher to restart several times to read the unnecessary file changes

This is happening for every service, and is causing incredible slow down. The lack of isolation between the containers is probably contributing the the extremely slow speeds

**Comment by toooni** [comment]
I had the feeling (no hard evidence) that I've had more issues with docker-sync not being fast enough especially when checking out branches with a lot of changes. So I stumbled upon this issue and tried disabling gRPC-FUSE. Unfortunately docker-sync stopped working. The initial sync was fine (I reset docker twice to the factory settings) but after that no changed files were updated anymore.
After turning gRPC-FUSE back on. It worked again. Did anyone experience the same? Or any clues on what I've done wrong?

**Comment by NilsEvers** [comment]
I don't know the current state regarding this issue, but your problem seems like Docker is not generating any file events again. I've kept gRPC-FUSE on since they broke it on every new release. They fixed one gRPC-FUSE related issue and broke another...

**Comment by EugenMayer** [comment]
Any current advice for the users? enable or disable gPRC-FUSE. Any hints @NilsEvers ?
