### ISSUE TITLE
Performance issue with unison

### ISSUE THREAD

**Issue by nevster123** [EugenMayer/docker-sync#757]
### Error/Feature Requestion/Docs
When using unison, if the computer has been left idle for sometime the disk access with unison becomes slow just like it is not being used. To resolve this I restart docker for mac and docker-sync, which alleviates the problem.

Is this a known issue and if so, do you have a solution.

Thankyou 

### Docker Driver
d4m

### Sync strategy
unison

### OS
OSX Version 10.15.7 Catalina

**Comment by EugenMayer** [comment]
this is an usual bug with unox and cannot be fixed with docker-sync. File-watchers under OSX are very very fragile - using native_osx should be the better choice
