### ISSUE TITLE
native_osx not syncing host to container

### ISSUE THREAD

**Issue by nevster123** [EugenMayer/docker-sync#758]
If changes are made in docker container then they are updated on host
If changed on host then does not affect container.

### Docker Driver
d4m

### Sync strategy
native_osx

### OS
OSX Version 10.15.7

**Comment by EugenMayer** [comment]
Use the https://github.com/EugenMayer/docker-sync-boilerplate to reproduce your issue and describe how and what you did.

**Comment by nevster123** [comment]
It seems to be working now

docker-sync.yml

version: "2"
options:
  verbose: true
syncs:
  app_sync:
    src: ./htdocs
    sync_strategy: 'native_osx'
  app_sites_sync:
    src: ./sites-enabled
    sync_strategy: 'native_osx'
  db_sync:
    src: ./mysql
    sync_strategy: 'native_osx'

docker-compose.yml

version: '3'
services:
  app:
    build: build/
    volumes:
      - app_sync:/var/www/html:nocopy
      - app_sites_sync:/etc/apache2/sites-enabled:nocopy
    ports:
      - 8080:8080
    working_dir: 'var/www/html'

  db:
    image: mysql:5.7
    volumes:
      - db_sync:/var/lib/mysql:nocopy
