### ISSUE TITLE
What documentation-changes does unison-unox require (migration guide)

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-sync#76]
Which extra configuration does unox need in comparison to unison-onsided? We need this in the docs as a migration guide and as a fat-notice in the changelogs.

@mickaelperrin could you sum it up?

**Comment by mickaelperrin** [comment]
In comparison with `unison-onesided`,  `unison-unox` needs `unox` to be installed.

    wget -O /usr/local/bin/unison-fsmonitor https://raw.githubusercontent.com/hnsl/unox/master/unox.py && chmod +x /usr/local/bin/unison-fsmonitor

unox removes also some parameters:
- sync_host_port
- unison-dualside_host_ip
- unison-dualside_host_server_port

and introduce a new one:
- max_inotify_watches. The use of `max_inotify_watched`will prompt for `sudo` password as it needs to run the container with privileged mode and modify host file configuration.

**Comment by mickaelperrin** [comment]
Just added the command to install unox in the raise error message for easy install.

`max_inotify_watches` is already documented in the example `docker-sync.yml` file.

**Comment by mickaelperrin** [comment]
Updated the help message to use `curl` which is default on Mac rather than `wget` which needs Mac Ports

**Comment by EugenMayer** [comment]
@mickaelperrin i have written up https://github.com/EugenMayer/docker-sync/wiki/Migration-Guide .. please review and fix whatever you think needed. If you are fine, just close this issue

**Comment by mickaelperrin** [comment]
Mm it looks like there is confusion between unison the original one (yours) which has been renamed unison-onesided and unison-dualside which has been removed in favor of unox.

I will improve this tomorrow.
