### ISSUE TITLE
Python's pip3-install installs old version of docker-sync, unable to upgrade

### ISSUE THREAD

**Issue by pnbecker** [EugenMayer/docker-sync#766]
### Error/Feature Requestion/Docs
If you install docker-sync using pip-install in version 3, on many systems docker-sync in version 0.0.11 will be installed. Upgrades using pip-install fails. If you install docker-sync using pip-install in version 2 (python 2) the newest version will be installed.

### Docker Driver
Docker for Desktop Mac, docker on ubuntu

### Sync strategy
does not apply to the problem

### your docker-sync.yml
does not apply to the problem

### OS
mac OS Big Sur, Ubuntu 20.04

Many more information can be found in #762, https://stackoverflow.com/questions/66571964/hombrews-gem-installs-old-version-of-a-ruby-gem and https://stackoverflow.com/questions/66571964/hombrews-gem-installs-old-version-of-a-ruby-gem.

**Comment by pnbecker** [comment]
@EugenMayer was this just closed or handled somehow?

**Comment by EugenMayer** [comment]
@pnbecker there is no effort since 7 months to fix this, so i assume it is neither critical enough nor painful enough to get solved.

Closed this issue simply because it is open way to long without any progress, sorry

**Comment by pnbecker** [comment]
@EugenMayer While I understand this, I'm afraid you're the only who can fix this. I expect a problem in the provisioning of the versions and not in the code. And I guess you're the only one having access to that.

**Comment by EugenMayer** [comment]
@pnbecker what are you suggesting

**Comment by pnbecker** [comment]
I'm more a java guy. We use Sonatype to provide software versions. I don't know how pip work exactly. But there must be a reason, that the old version of docker-sync gets precedence before the newer version. Are there any settings? Is there any kind of version pinning? What do you use to provide python packages?

**Comment by EugenMayer** [comment]
I do not think this is python related, it is ruby related. If you use ruby3, there is no docker-sync compatible release except the very old one, which did not properly define the ruby version constrain

**Comment by EugenMayer** [comment]
releases like 0.0.4 are not bound to any upper ruby version, I somehow need to republish them

**Comment by EugenMayer** [comment]
Anything newer then https://rubygems.org/gems/docker-sync/versions/0.0.15 has no ruby version upper limit, so if someone uses ruby 3.0, which docker-sync is not compatible with, the person gets 0.0.15

**Comment by pnbecker** [comment]
@EugenMayer Great that you found that! Thank you!

**Comment by EugenMayer** [comment]
will be fixed by #795

**Comment by EugenMayer** [comment]
close since #795 has been fixed
