### ISSUE TITLE
Document 'edge-cases' for unison-unox

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-sync#77]
Edge-cases are: 

a) if a lot of fs-changes happen in a short time ( like comopser install ) at some point fsevents might be lost and not all changes are synced
b).. ?

@mickaelperrin can you add things you know here?

**Comment by mickaelperrin** [comment]
This is indeed the main issue. But a simple stop / start of `docker-sync` resolves all missing files.

Since the `stable` release of Docker for Mac, it looks like the stability of `unison` has increased and I didn't remember to have to restart `docker-sync`.

**Comment by gagarine** [comment]
For a) can we detect that and automatically restart docker-sync ?

**Comment by mickaelperrin** [comment]
Well, some updates about this.

I don't think there is a safe way to do an auto restart of docker-sync when such an issue occured. There is indeed a message about a partial sync that is emitted by unison, but how do you know if some syncs won't happen during restart ? 

However, just did a new full scaffolding of a Drupal install with the latest Docker for Mac, and didn't get this issue... and looks like it was even faster than usual... So maybe we won't have this edge case anymore ? Wait and see...

**Comment by EugenMayer** [comment]
Lets be reactive, i am seconding @mickaelperrin . If this issue becomes relevant enough, we have enough data to see, when it can be detected. I am closing this issue for now, reopening it if needed
