### ISSUE TITLE
docker-sync doesn't recognize restart command and will not update

### ISSUE THREAD

**Issue by cgorevin** [EugenMayer/docker-sync#770]
### Error/Feature Requestion/Docs
I'm running into an issue when I run `docker-sync start` in which I'm prompted to update my `docker-sync` version. When I select "yes", I receive an "update successful" message that advises me to run the command `docker-sync restart`. When I run this command, I get an error asking if I meant the `docker-sync start` command. Then the next time I boot up docker-sync, I receive the same update message. My colleague is also experiencing this issue. `gem update docker-sync` and `gem update --user-install docker-sync` are similarly unsuccessful. While this isn't a blocker, per se, it is a recurrent annoyance. Any suggestions?

<img width="795" alt="docker-sync_update" src="https://user-images.githubusercontent.com/26980161/121067649-4d8de280-c799-11eb-81f3-7f5d5d267e63.png">
<img width="702" alt="docker_sync_restart" src="https://user-images.githubusercontent.com/26980161/121067656-51216980-c799-11eb-89ac-450ebc5c214d.png">
<img width="324" alt="Screen Shot 2021-06-07 at 11 03 57 AM" src="https://user-images.githubusercontent.com/26980161/121067640-48309800-c799-11eb-81f8-de8e7fff091f.png">
![image](https://user-images.githubusercontent.com/26980161/121067834-8a59d980-c799-11eb-9535-0447bead6597.png)

### Docker Driver
Unsure of where to find this info. Here's my `docker info` output:
```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 13
  Running: 10
  Paused: 0
  Stopped: 3
 Images: 50
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 11
 Total Memory: 11.7GiB
 Name: docker-desktop
 ID: 
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 189
  Goroutines: 209
  System Time: 2021-06-07T18:10:40.468442434Z
  EventsListeners: 5
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Sync strategy
native_osx

### your docker-sync.yml
```yml
version: "2"
options:
  verbose: true
syncs:
  default-sync:
    src: './'
    sync_strategy: 'native_osx'
    notify_terminal: true
    sync_excludes:
      - tmp
      - .git
      - node_modules
      - log
      - public/system
```

### OS
macOS Big Sur, v 11.3.1

**Comment by EugenMayer** [comment]
Is this still an issue with the newer releases?

**Comment by cgorevin** [comment]
Yes, since I can't update to the newer releases.

**Comment by EugenMayer** [comment]
Please update manually by uninstalling the gem and installing again. This is most probably and issue with your running docker-sync in your system ruby or a ruby where you do not have proper permissions to replace the gem
