### ISSUE TITLE
Allow alternative implementations of unison-fsmonitor

### ISSUE THREAD

**Issue by d4rky-pl** [EugenMayer/docker-sync#775]
### Error/Feature Requestion/Docs
There's an [alternative implementation of unison-fsmonitor](https://github.com/autozimu/unison-fsmonitor) which uses Facebook `watchman` and it's insanely faster compared to [eugenmayer/dockersync/unox](https://github.com/hnsl/unox) (we're talking <1s vs 2-5s for each update). Unfortunately to use it I had to modify the code of `docker-sync` to prevent it from forcing me to remove it and installing `unox` instead.

It would be amazing if we could somehow disable the `unox` check, either with --flag or even ENV var.

**Comment by d4rky-pl** [comment]
Great, the moment I created the issue it crashed 😢 

```
Failed: Server: Server: Fatal error during unmarshaling (input_value: unknown custom block identifier),
possibly because client and server have been compiled with differentversions of the OCaml compiler.
Fatal error: Server: Server: Fatal error during unmarshaling (input_value: unknown custom block identifier),
possibly because client and server have been compiled with differentversions of the OCaml compiler.
```

I guess more research is needed to ensure this alternative implementation can be used properly but it would still be great to have it as an option

**Comment by EugenMayer** [comment]
Happy to review an PR for that. I tested watchman and it has other drawbacks - it will by no means be a clean win / one sided

**Comment by d4rky-pl** [comment]
@EugenMayer what option would you prefer - a flag when starting `docker-sync`, an ENV var or detecting alternative `unison-fsmonitor` from homebrew?

Also - what were those other drawbacks, if you can recall them, so I can keep an eye on them?

**Comment by d4rky-pl** [comment]
@EugenMayer if we're going to go with detecting alternative `unison-fsmonitor` from homebrew, I can also add a warning that says it detected something other than `unox` and `unox` is the recommended solution

**Comment by EugenMayer** [comment]
is #776 enough to get this running already, is the implementation interface of the alternative just feature complete with the other?

Could you post some benachmarks / ideas / motivation so we can move this into the documentation as an option for people to try / optimize. I'am yet not sure what troubles i had back then, so what downtime watchman had, but things might change and we might need to find, if any, the weakspot and the sweespot.

I would really love to add this to the docs, what do you think?

**Comment by d4rky-pl** [comment]
The #776 is enough to make this running, the whole instruction to enable it is basically:

```
brew install eugenmayer/dockersync/unox
brew uninstall autozimu/homebrew-formulas/unison-fsmonitor
```

and it seems to work as a drop-in replacement. I'm not show how to run benchmarks on this one since what speeds up the most is `unison` itself, specifically how long it takes until it gets to the `Looking for changes` part (and that one does not include any timing information)

### Unox

https://user-images.githubusercontent.com/284395/125573498-70af5a68-ed4d-4924-a985-010e0d34d6b1.mp4

### unison-fsmonitor

https://user-images.githubusercontent.com/284395/125573666-e529c5f9-4181-4c0b-9e90-bf4ba2375063.mp4

The drawback I did notice is that if you modify files too fast the changes sometimes do not get synced until another change gets created (so it's still not ideal for things like npm/yarn install). For us this is acceptable since we're using docker-sync mostly for syncing our own changes only but it merits adding a caveat.

BTW I only now realized but this alternative implementation is just using Rust fsevents implementation and NOT watchman - it was linking to watchman docs which is why I got confused (and I'm using watchman everywhere because of webpack so I already had it installed) but I double-checked the source code and it's just plain Rust.

**Comment by d4rky-pl** [comment]
To be more specific, it's not about files getting modified too fast, it's about files modified when unison hits the reconciliation phase. This might also be happening with unox (I would need to run more tests)

**Comment by d4rky-pl** [comment]
@EugenMayer I think we can add this to the Getting Started > Advanced / optional section of the docs for now:

```
.. caution::

    Starting with docker-sync 0.7.0 if you're using unison, you can also install [an alternative](https://github.com/autozimu/unison-fsmonitor) to unox. It seems to be faster and more performant but it has not been fully battle-tested yet.
```

I can add it to the PR, just give the word :)

**Comment by Ewarren7** [comment]
@d4rky-pl to clarify, I assume this is mainly beneficial when using this with the sync strategy for a project set to `unison`? Or is this also beneficial for `native_osx` strategy that uses unison in the sync container?

**Comment by EugenMayer** [comment]
@d4rky-pl as you suggested, only for unison strategies, not native-OS X
