### ISSUE TITLE
Fail of docker-sync update

### ISSUE THREAD

**Issue by isudakoff** [EugenMayer/docker-sync#779]
### Error Requestion
```shell
$ docker-sync-stack start
     warning  There is an update (0.6.0) available (current version 0.5.14
). Please update before you continue
Shall I update docker-sync to 0.6.0 for you? Y
Updating installed gems
Updating docker-sync
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
       error  Unable to update docker-sync
```

I tried to Google it, but have no results. Sudo also don't help to me.

After rerun of the command update checking doesn't run and I can just run my docker.
But after closing the tab and first run of docker-sync-stack start command in new tab this process repeat.

### Docker Driver
d4m:
Docker Desktop 3.6.0
Docker Engine 20.10.8
Docker Compose v2.0.0-rc.1

### Sync strategy
unison

### your docker-sync.yml
does not apply to the problem

### OS
OSX: macOS Big Sur 11.5

**Comment by EugenMayer** [comment]
Obviously an issue with your ruby installation, you are using system ruby which is a problem in itself and needs extra care and for sure `sudo`. You can consult any MacOS ruby guide on why to not to use system ruby for custom gems and all this, that would be out of scope for docker-sync.

I would properly uninstall docker-sync from system ruby and install it to an RVM ruby. Or if you do not want, uninstall it and install it again ot the system ruby
