### ISSUE TITLE
Folder Path isn't quoted. It causes errors if there are spaces

### ISSUE THREAD

**Issue by manuel-leveugle** [EugenMayer/docker-sync#783]
### Error/Feature Requestion/Docs
Hello

Folder Path isn't quoted. It causes errors if there are spaces
```
ok  starting initial sync of my-volume-sync
command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' my-volume-sync
command  unison -testserver /d/Test "socket://127.0.0.1:61174"
command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' my-volume-sync
command  unison -ignore='Name .docker-sync' -ignore='Name .idea' -ignore='Name var' -ignore='Name vendor' '/d/Test' auto -batch -prefer '/d/Test' -copyonconflict -perms=0 socket://127.0.0.1:61174"
```

Line in error is this line
```
command  unison -testserver /d/Test "socket://127.0.0.1:61174"
```

Thank you for your help

### Docker Driver
Docker Desktop

### Sync strategy
unison

### your docker-sync.yml
version: "2"

options:
  verbose: true
syncs:
  my-volume-sync:
    src: '.'
    sync_args: ['-perms=0']
    sync_excludes: ['.docker-sync', '.idea', 'var', 'vendor']
    sync_host_ip: '127.0.0.1'
    sync_strategy: unison
    watch_excludes: ['.docker-sync', '.idea', 'var', 'vendor']

### OS
Windows

**Comment by EugenMayer** [comment]
Hello @manuel-leveugle - are you going to move this forward or what is your go at this?

**Comment by manuel-leveugle** [comment]
Hello @EugenMayer, sorry, i didn't see your message sooner. I have already create a PR for this issue.
Are you able to reload Travis test which did not launch?

**Comment by EugenMayer** [comment]
merged and fixed, thank you!
