### ISSUE TITLE
syncthing as an alternative sync strategy

### ISSUE THREAD

**Issue by donnykurnia** [EugenMayer/docker-sync#786]
### Alternative Sync strategy: syncthing

I just tried https://syncthing.net/ in my local docker dev environment for a laravel project.

Here is the pros and cons that I experienced:

Pros
- sync both way, continuously
- web GUI to monitor the sync status, pause, restart, share, etc
- can run as docker container, so the setup pretty much similar with docker-sync. In my setup, I run it like this:
  - run syncthing in host
  - run a syncthing container with named volumes
  - use the syncthing container named volumes in the project container

Cons
- no easy way to configure it using configuration file. My attempt to sync is done using web gui.

Have anyone else tried this? Could this be someday replace the unison strategy?

**Comment by EugenMayer** [comment]
Closing as non critical issue / feature and i'am not going to work and further nice to have features for now. Be sure to reopen this issue if you want to work on this issue yourself and provide a PR. Happy to review those
