### ISSUE TITLE
Passing Through Options to `docker-compose`

### ISSUE THREAD

**Issue by KidA78** [EugenMayer/docker-sync#787]
### Error/Feature Requestion/Docs
I've created a profile in `docker-compose` that I'd like to be able to turn on when using `docker-sync-stack start` 
How might I be able to do this?

### OS
Mac OS Catalina

**Comment by EugenMayer** [comment]
I would say, this is not possible. we are using an abstraction to trigger docker-compose and that abstraction does not support that. created #788 but be sure to notice, i will not work on that myself, someone else will need to step in. Maybe you?

**Comment by EugenMayer** [comment]
will be closed with #795
