### ISSUE TITLE
Apple m1 docker-sync-stack start error block in start_container

### ISSUE THREAD

**Issue by gabriImparaProgrammare** [EugenMayer/docker-sync#791]
Hi,

please explain me step by step, i'm not so expert.
i have apple m1

This is my docker-sync.yml

![Screenshot 2022-01-17 at 17 09 05](https://user-images.githubusercontent.com/97903301/149803979-273b01e5-5d05-43a1-b2b5-de35d02b1fad.png)

if i do docker-sync-stack start i have this issue:

![Screenshot 2022-01-17 at 17 12 29](https://user-images.githubusercontent.com/97903301/149804380-6d41183d-16ed-4524-9389-de4e8cbdbf17.png)

i have already try to set max_attempts high, like 100, but that isn't the problem
what i have to do?

**Comment by EugenMayer** [comment]
- https://docker-sync.readthedocs.io/en/latest/index.html
- https://github.com/EugenMayer/docker-sync-boilerplate

**Comment by gabriImparaProgrammare** [comment]
> thank you, i read your documentation, but i can't find a solution to my problem.
Could you check my code and help me??

**Comment by EugenMayer** [comment]
unclear question
