### ISSUE TITLE
feature: auto start option for `docker-sync sync`

### ISSUE THREAD

**Issue by te-johan** [EugenMayer/docker-sync#793]
I'm using docker-sync on mac to speed up my builds. unfortunately the sync process is not fast enough for my work flow.
Between saving a file until I call make needs to sync immediately.

So I use the 'dummy' watch_strategy together with unison with the preference to always keep the source files.
In my make files I call `docker-sync sync` before and after building and it works great.

However there is no good way to know if `docker-sync start` has been called. `docker-sync list` does not show anything and the return values from the docker-sync commands are always zero regardless if any errors occurred.
I propose to add an option for `docker-sync sync` to run start if it is not already running.

**Comment by EugenMayer** [comment]
Closing as non critical issue / feature and i'am not going to work and further nice to have features for now. Be sure to reopen this issue if you want to work on this issue yourself and provide a PR. Happy to review those
