### ISSUE TITLE
Feature Requestion: add update command

### ISSUE THREAD

**Issue by alielmajdaoui** [EugenMayer/docker-sync#798]
### Error/Feature Requestion/Docs
I want to start a sync container using the "docker-sync start ..." command, and I got a message that if I want to update the current `docker-sync` to `0.7.1`. When I replied with `y`, I get this error

```
Shall I update docker-sync to 0.7.1 for you? y
Updating installed gems
Updating docker-sync
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
       error  Unable to update docker-sync
```

I found some posts on how to solve the file permission issue but I couldn't find any command to update `docker-sync`.
The only way to get the update question again is to restart `docker-sync` daemon and run that start command.

### OS
MacOS Big Sur

**Comment by EugenMayer** [comment]
Closing as non critical issue / feature and i'am not going to work and further nice to have features for now. Be sure to reopen this issue if you want to work on this issue yourself and provide a PR. Happy to review those
