### ISSUE TITLE
push the unison-unox image to eugenmayer/unison:unox and eugenmayer/unison

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-sync#80]
@mickaelperrin how do i get the unox dockerfile for now, so i can push it?
You should then reference it as default in the new unison strategy

**Comment by EugenMayer** [comment]
@mickaelperrin waiting for you for the image

**Comment by mickaelperrin** [comment]
Are your talking about that https://github.com/mickaelperrin/docker-unison-unox ? Do you need anything else ?

**Comment by mickaelperrin** [comment]
Just changed the default image from `eugenmayer/unison:unox` to `eugenmayer/unison`

**Comment by EugenMayer** [comment]
thanks! pushed on eugenmayer/unison:unox for now. I cannot replace the stable now for now, since we did not yet release. I would suggest you probably change back to eugenmayer/unison:unox and we keep it this way until 0.1.1 - so one release after. Otherwise people will have trouble with older versions
