### ISSUE TITLE
Enforcing one-way sync

### ISSUE THREAD

**Issue by ardabeyazoglu** [EugenMayer/docker-sync#806]
### Error/Feature Requestion/Docs
Is there any way to run one-way sync from source? So any edit inside the container will not override the source. Can't see from documentation.

### Docker Driver
docker linux

### Sync strategy
unison or native linux

### OS
ubuntu 20.04

**Comment by EugenMayer** [comment]
closed as outdated. Beside that, there is really no reason we should invest in features for docker-sync under linux - one should not use docker-sync for those environments
