### ISSUE TITLE
Bug: Wrong Unison image is pulled on M1 Mac

### ISSUE THREAD

**Issue by yoseph1998** [EugenMayer/docker-sync#810]
### Error/Feature Requestion/Docs
When starting docker sync on an M1 Mac the wrong image is pulled. The AMD unison image is pulled by default regardless of architecture. Instead the ARM image should be pulled for ARM architecture machines.

### Docker Driver
Rancher Desktop with moby and dockerd

### Sync strategy
default (on osx)

### your docker-sync.yml
```
version: "2"
syncs:
  app-sync:
    src: './'
```

### OS
OSX Monterey 12.5.1

### Reference:
Original issue opened in unison repository https://github.com/EugenMayer/docker-image-unison/issues/28

**Comment by yoseph1998** [comment]
@EugenMayer https://github.com/EugenMayer/docker-sync/pull/811

**Comment by EugenMayer** [comment]
Started working on the migration the new image on #813

**Comment by EugenMayer** [comment]
@yoseph1998 could you test the branch on your M1?

Since there are currently no CI engines available to run MacOS on M1, nor any MacOS offering CI that runs docker-for-mac (license issues), i cannot test docker-sync on it's home platform in the CI and thus rely on the community to do that testing - i do no longer own a mac.

**Comment by yoseph1998** [comment]
Sure I can do so, I’ll let you know when I test it, give me a few hours.

FYI only Docker Desktop is license restricted. The CLI and Engine are still open source and don’t carry any restrictions for commercial use. Rancher Desktop is currently the number 1 alternative to set everything up (virtual machine for the Linux daemon on Mac, cli and connecting it all).
