### ISSUE TITLE
What's the "extra care" for using unison on OSX with sleep/hibernate.

### ISSUE THREAD

**Issue by ppggff** [EugenMayer/docker-sync#828]
I found the doc say one of the Cons of unison is:
 "The daemon on OSX needs extra care for sleep/hibernate."

So what is the "extra care"? How to fix it? There is no issue related to it.

**Comment by Housik** [comment]
@ppggff May be it is releted to this Docker for Mac issue -> https://github.com/docker/for-mac/issues/3455#issuecomment-1064614213

**Comment by EugenMayer** [comment]
the extra care is rather 'do not expect it to work after sleep/hibernate'

**Comment by ppggff** [comment]
Thanks a lot
