### ISSUE TITLE
One unison image for singlesided and unox

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-sync#83]
@mickaelperrin since dualsided has been removed, the question is, if we either remove the deps we introduced or rather make one image for the unox and onesided version (one singel)

**Comment by EugenMayer** [comment]
For now as for #79 i pushed the current unison image to eugenmayer/unison:onesided

**Comment by mickaelperrin** [comment]
Actually, I think they can share the same image. I will investigate this and confirm it.

**Comment by mickaelperrin** [comment]
I confirm both images could be merged. However, I wonder the use case of this image, shouldn't it be marked as deprecated like dualside ?

**Comment by EugenMayer** [comment]
well u mean, the extended one - well u are most probably right. Lets turn this the other way, can we combine unison-singlesided and unison-unox (i guess yes)

**Comment by timstallmann** [comment]
Hi y'all -- I'm seeing `unison was invoked incorrectly (too many roots)` on the new `0.1.0` branch -- could this be related to the docker image?

**Comment by mickaelperrin** [comment]
Thanks for reporting, please open a new Issue and provide your config file, the ouput of the log and the result of `docker ps -a | grep eugenmayer`. I will have a look at it.

**Comment by EugenMayer** [comment]
@mickaelperrin i currently do plan to remove unison-singlesided since it is just "stuff to maintain but not used at all" - what do you think, i would throw that one out with 0.2.0

**Comment by mickaelperrin** [comment]
@Eugenmayer it's ok for me. I think you're right, keep only unison unox.

**Comment by EugenMayer** [comment]
closing, since we will remove one-sided in 0.2.0
