### ISSUE TITLE
Disabling docker-compose menu 

### ISSUE THREAD

**Issue by jpdery** [EugenMayer/docker-sync#839]
In a somewhat recent update of docker compose, the following menu has been added

`v View in Docker Desktop   o View Config   w Enable Watch`

I find it very annoying and the only way to disable it is to launch docker-compose wit the `--menu=false` flag. 

However, using docker sync, I was not able to find a way to pass this argument to docker compose. 

Is it possible ?

Thanks

**Comment by EugenMayer** [comment]
I do not think we have such an option yet. You can create a new bash script called "docker-compose" in your PATH, that redirects all calls to `docker compose --menu=fals $@` to "hack this for you case.
