### ISSUE TITLE
How "-prefer newer" works

### ISSUE THREAD

**Issue by gagarine** [EugenMayer/docker-sync#84]
The `-prefer newer` unison's flag is based on files date? The code-sync containers doesn't have the same time zone than my local machine. Can this cause a problem?

**Comment by EugenMayer** [comment]
@mickaelperrin you are the expert here, cannot judge uppon this. 

I would suggest it matters of course.

**Comment by gagarine** [comment]
This can explain why I was getting conflict.

Perhaps we should start the docker-sync container with
`-v /etc/localtime:/etc/localtime:ro`

**Comment by EugenMayer** [comment]
Interesting point, you mean, setting the sync-container time to the one of OSX. Maybe instead of mounting it, we can pass a ENV var, an read it before we start the container or even make this a configuration variable ( in addition )

**Comment by mickaelperrin** [comment]
I didn't find any documentation about how `-prefer newer` works.  I will give a look to the C code but actually we should ensure that the unison container share the same time and timezone with the host.

I will provide a patch to ensure this.
