### ISSUE TITLE
Deletes not syncing (rsync)

### ISSUE THREAD

**Issue by kylehendricks** [EugenMayer/docker-sync#91]
Delete's don't seem to be syncing into the volume.

To reproduce:
1. Start docker-sync with a volume syncing via rsync
2. Delete a file on the host machine
3. Check if the delete is reflected inside the volume container.

**Comment by mickaelperrin** [comment]
Deletes are tricky with rsync, see #37 to the drawbacks of using the additionnal `--delete`parameter.

Unison handles this better.

**Comment by kylehendricks** [comment]
Ah.  Should have searched.  Thanks!
