### ISSUE TITLE
docker-sync-stack start

### ISSUE THREAD

**Issue by gcstang** [EugenMayer/docker-sync#92]
Does this support the docker-compose.yml and docker-compose-dev.yml setup ?

I get this when trying it with that setup.

`/Library/Ruby/Gems/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:105:in `private': nil is not a symbol (TypeError)
	from /Library/Ruby/Gems/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:105:in `<class:Mapper>'
	from /Library/Ruby/Gems/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:5:in `<module:Compose>'
	from /Library/Ruby/Gems/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:2:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose.rb:10:in `require_relative'
	from /Library/Ruby/Gems/2.0.0/gems/docker-compose-0.8.3/lib/docker/compose.rb:10:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.15/tasks/stack/stack.thor:5:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.15/bin/docker-sync-stack:23:in `load'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.15/bin/docker-sync-stack:23:in `block in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.15/bin/docker-sync-stack:21:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.15/bin/docker-sync-stack:21:in `<top (required)>'
	from /usr/local/bin/docker-sync-stack:23:in `load'
	from /usr/local/bin/docker-sync-stack:23:in `<main>'`

**Comment by EugenMayer** [comment]
Upgrade your Ruby to 2.0+ this is a known issue of 0.0.6

**Comment by gcstang** [comment]
It say's I'm on 2.0
ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]

**Comment by EugenMayer** [comment]
please see https://github.com/EugenMayer/docker-sync/issues/72 this is related to your issue and it is fixed by a ruby upgrade

**Comment by EugenMayer** [comment]
this said, ensure, the place you run docker-sync-stack start, the ruby version is not changed using rbenv or similar

**Comment by gcstang** [comment]
Same issue on newer version, had to follow this to install it on my Mac 
curl -L https://get.rvm.io | bash -s stable --autolibs=enabled --ruby
rvm use 2.3.0 --default

`/Users/myuser/.rvm/gems/ruby-2.3.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:105:in `private': nil is not a symbol (TypeError)
	from /Users/myuser/.rvm/gems/ruby-2.3.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:105:in `<class:Mapper>'
	from /Users/myuser/.rvm/gems/ruby-2.3.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:5:in `<module:Compose>'
	from /Users/myuser/.rvm/gems/ruby-2.3.0/gems/docker-compose-0.8.3/lib/docker/compose/mapper.rb:2:in `<top (required)>'
	from /Users/myuser/.rvm/gems/ruby-2.3.0/gems/docker-compose-0.8.3/lib/docker/compose.rb:10:in `require_relative'
	from /Users/myuser/.rvm/gems/ruby-2.3.0/gems/docker-compose-0.8.3/lib/docker/compose.rb:10:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/myuser/.rvm/gems/ruby-2.3.0/gems/docker-sync-0.0.15/tasks/stack/stack.thor:5:in `<top (required)>'
	from /Users/myuser/.rvm/gems/ruby-2.3.0/gems/docker-sync-0.0.15/bin/docker-sync-stack:23:in `load'
	from /Users/myuser/.rvm/gems/ruby-2.3.0/gems/docker-sync-0.0.15/bin/docker-sync-stack:23:in `block in <top (required)>'
	from /Users/myuser/.rvm/gems/ruby-2.3.0/gems/docker-sync-0.0.15/bin/docker-sync-stack:21:in `each'
	from /Users/myuser/.rvm/gems/ruby-2.3.0/gems/docker-sync-0.0.15/bin/docker-sync-stack:21:in `<top (required)>'
	from /usr/local/bin/docker-sync-stack:23:in `load'
	from /usr/local/bin/docker-sync-stack:23:in `<main>'`

**Comment by EugenMayer** [comment]
please post your docker-sync.yml and docker-compose-dev.yml thanks

**Comment by gcstang** [comment]
Had to change extension to .txt instead of .yml to attach them here.

[docker-sync.txt](https://github.com/EugenMayer/docker-sync/files/404291/docker-sync.txt)
[docker-compose-dev.txt](https://github.com/EugenMayer/docker-sync/files/404292/docker-compose-dev.txt)

**Comment by EugenMayer** [comment]
please join https://gitter.im/EugenMayer/docker-sync so we can chat a bit

**Comment by EugenMayer** [comment]
could you also add your docker-compose file please. Feel free to obfuscate whatever you need, but keep it is original as possible

**Comment by gcstang** [comment]
[docker-compose.txt](https://github.com/EugenMayer/docker-sync/files/404300/docker-compose.txt)

**Comment by EugenMayer** [comment]
in the end it was the expected ruby version below 2.0 issue, just combined with a local system "which ruby to pickup" issue

**Comment by lussoluca** [comment]
Hi EugenMayer,
could you please describe in detail how to resolve the issue?

Thanks
