### ISSUE TITLE
Odd issue with second sync in docker-sync.yml

### ISSUE THREAD

**Issue by gcstang** [EugenMayer/docker-sync#93]
With this configuration they folders and subcontent is on the sync container but the second sync "site-sync" only has one subfolder when it's volume is shared with the tomcat container.
On physical and sync container the second sync has:
/usr/local/sites/starter/logs
/usr/local/sites/starter/security

But only the logs directory is on the tomcat container, is there some issue that isn't showing or another way to troubleshoot it?

`
syncs:
  tomcat-sync:
    src: '/Users/myusername/ocpdev/GitRepositories/application/build/deployments/starter/webapps/localhost/ROOT/'
    dest: '/usr/local/tomcat/webapps/ROOT'
    sync_host_ip: 'localhost'
    sync_host_port: 10872
  site-sync:
    src: '/Users/myusername/ocpdev/GitRepositories/application/site/'
    dest: '/usr/local/sites/starter'
    sync_host_ip: 'localhost'
    sync_host_port: 10873
`

**Comment by EugenMayer** [comment]
Please Post your dicker Sync and dev compose file,thanks

**Comment by EugenMayer** [comment]
in the end it was the expected ruby version below 2.0 issue, just combined with a local system "which ruby to pickup" issue

**Comment by EugenMayer** [comment]
woops, wrong issue

**Comment by EugenMayer** [comment]
i guess that one does not happen anylonger, according to a gitter chat
