### ISSUE TITLE
Unison sync seems to hang silently on launch for large amount of time

### ISSUE THREAD

**Issue by timstallmann** [EugenMayer/docker-sync#94]
Consistently after running `docker-sync clean` the first time I run `docker-sync start` it takes 20-30 minutes to spin up and actually start syncing. Output hangs on the following message:

`command  unison -ignore='Path .git' -ignore='Path .docker' -ignore='Path cache' -ignore='Path db' -ignore='Path bin' -ignore='Path vendor' /my-path -auto -batch socket://localhost:10873/ -debug all`

After about 30 minutes of spin-up time the service finally starts responding and syncs appropriately. Before that time no files have been synced.

Any thoughts on this? I can shell into the unison container and see that the unison process is running but just not responding.

This is using the `eugenmayer/unison` image, most-recent docker-sync version.

**Comment by EugenMayer** [comment]
@timstallmann how large is the folder you are syncing?

**Comment by timstallmann** [comment]
@EugenMayer fairly large -- 4 gigs. Any thoughts on ways to speed up the initial unison start-up time?

**Comment by EugenMayer** [comment]
@mickaelperrin is unison expected to sync that long with unison?

@timstallmann try rsync, this probably should be a lot fast.

Are those large files or just a lot of file. Could you make a file count?

**Comment by timstallmann** [comment]
@EugenMayer it's a lot of small files (52,273 to be exact).. we're using unison because of the necessity for two-way sync

**Comment by timstallmann** [comment]
But I could probably tweak our config to sync one of the files directories which has the large # of files and doesn't need 2-way sync using rsync and the remainder via unison.

**Comment by EugenMayer** [comment]
We have to issues with this amount of files: 
 a) sync takes long
 b) fswatch to trigger new sync, could have troubles with this amount of files

To work on:
a) cannot be more performant, if you cannot exclude any files using the sync_excludes
b) cannot be fixed, if you cannot exclude any files from being watched using watch_excludes

I am not sure we can help you with anything like this in docker-sync - you are probably dealing with hard limits of either fswatch or of unison, fswatch expected.

Probably the new unison+unox ( fswatch replaced by unox ) can work better with those, but i do not really expect this. Its rather there to be a full transparent 2 way sync, which the current unison is not. @mickaelperrin can probably later comment on this

**Comment by mickaelperrin** [comment]
Which version of `docker-sync` are you running ?

FYI, I am syncing around 30k files / 350MB  in around 15 seconds, with latest release (unison with unox).

Did you try with verbose option off ? Could you paste your config file ?

**Comment by timstallmann** [comment]
@mickaelperrin I am usually running version 0.0.15 with verbose mode off, just turned it on to try to debug this issue. Moving the largest files directory out of unison and into rsync seems to solve the problem, so my guess is this is just a performance issue with unison?

**Comment by mickaelperrin** [comment]
Unison needs to build a `catalog` on the first run. I didn't work with heavy files curently. What's the largest file you use in your repo ?

**Comment by timstallmann** [comment]
@mickaelperrin I don't think any one file is very large, it's just a large number of images and whatnot....

**Comment by mickaelperrin** [comment]
OK, thanks for reporting, I will try to reproduce on my side, and will update this if found any way to tackle this.

**Comment by timstallmann** [comment]
Thanks! For now talking through it with you and @EugenMayer has at least helped figure out a workaround. Thanks so much for being so responsive!! 😸

**Comment by EugenMayer** [comment]
@mickaelperrin be aware that he is most probably yet using unison-singleside since unox has yet not been released. Maybe let him try using deploy_locally and use the current master ( not heavily tested yet though )

**Comment by mickaelperrin** [comment]
Mmmm didn't get the point that unox wasn't already released :) However, I am not sure it will improve the initial sync, but that's sure for later syncs it will work far far better than fswatch + unison.

**Comment by EugenMayer** [comment]
@timstallmann docker-sync 0.1.0 https://github.com/EugenMayer/docker-sync/releases/tag/0.1.0 has just been released, you should try this with your case. Use unison as a strategy. Report back how it works out in your case, thanks!

**Comment by mickaelperrin** [comment]
However, note that it won't improve initial sync performance. See the [Unison FAQ](https://alliance.seas.upenn.edu/~bcpierce/wiki/index.php):

> I want to use Unison to synchronize really big replicas. How can I improve performance?

> When you synchronize a large directory structure for the first time, Unison will need to spend a lot of time walking over all the files and building an internal data structure called an archive. There is no way around this: Unison uses these archives in a critical way to do its work.

**Comment by EugenMayer** [comment]
@timstallmann any feedback on this, i would otherwise just close this issue

**Comment by timstallmann** [comment]
@EugenMayer I think we can close! Just added a note to the bottom of https://github.com/EugenMayer/docker-sync/wiki/4.-Performance so other folks who encounter this issue are aware it's not a bug. Feel free to move if there's a better place in the wiki for it.

**Comment by EugenMayer** [comment]
@timstallmann its a good spot, though i guess we need to add it to strategies at least also, so people are guided. Thanks for the feedback!

**Comment by mickaelperrin** [comment]
@timstallmann Thanks for editing the wiki and adding your use case.

However, I am not sure that the number of files is the keypoint in your problem. As I previsously said, I sync more than 30k+ files in less than one minute. 

The main difference with your usecase seems to be the **total weight** of the repository (4GB / vs 350MB). 

@EugenMayer did you encounter also a such delay with your (presumingly) large code base ?

**Comment by EugenMayer** [comment]
I am syncing more or less 33654 with a size of 559M right now, in about 35 seconds initially, so i cannot say, that i run into the same issues as @timstallmann does. Its a combination of files and numbers most probably

**Comment by timstallmann** [comment]
Ok! Just updated the wiki to flag that this requires both large #s of files and large total size

**Comment by mickaelperrin** [comment]
@timstallmann Thanks 👍

**Comment by nicolas-albert** [comment]
Hi,
5 years later I find this issue because I have the same unison issue.
This is not a good news for me, because I want to mirror a slow AKS (Azure Kubernetes) azure-file (smb share) to a local disk.
The slow IO with azure-file also kills the first replication time.
I guess I will find an other solution !
